### ISSUE TITLE
Enhancement: Ability to switch locals (easily) on a per table basis

### ISSUE THREAD

**Issue by tmorehouse** [wenzhixin/bootstrap-table#1029]
Ideally, it would be nice to beable to have a an option parameter to set the prefered locale for a table as it is instantiated. i.e.

    $table.bootstrapTable({ locale: 'es-SP'});

Rater than changing the default for all tables, it would be nice to be able to do it per table. An extra option plus maby a new "allowed method" would be nice.

For now I have been doing this:

	// Function to switch locales
	$.fn.bootstrapTable.prototype.setLocale = function(locale) {
		var short_local = locale.replace(/-.*/,'');
		if ($.fn.bootstrapTable.locales[locale]) {
            // first see if locale exists as is
			$.extend(this.options, $.fn.bootstrapTable.locales[locale]);
		} else if ($.fn.bootstrapTable.locales[short_locale]) {
            // then try looking for two letter locale (i.e. en or es or fr)
			$.extend(this.options, $.fn.bootstrapTable.locales[short_locale]);
		} else {
            // else fall back to en-US
			$.extend(this.options, $.fn.bootstrapTable.locales['en-US']);
		}
	};
        // Add it to the allowed methods
	$.fn.bootstrapTable.methods.push('setLocale');

But it is not the ideal solution.  It would be perfect is we could pass a locale as an option to the constructor.

The reasoning for the check of the two letter code is that In my case, I have cloned `en-US` as `en` and `fr-FR` as `fr`, etc,  because my application allows for two character and 5 character language selections (i.e. can't find `fr-CA`? then try `fr` (which is equal to `fr-FR` in my case:)

	$.fn.bootstrapTable.locales['en'] = $.fn.bootstrapTable.locales['en-US'];
.	$.fn.bootstrapTable.locales['fr'] = $.fn.bootstrapTable.locales['fr-FR'];
	$.fn.bootstrapTable.locales['es'] = $.fn.bootstrapTable.locales['es-SP'];

etc

**Comment by dabros** [comment]
@tmorehouse 

Please see http://bootstrap-table.wenzhixin.net.cn/documentation/ (locales)

The method shown there referances including multiple locale.js files, then using something like this to switch

```javascript
$.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales['en-US']);
// $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales['zh-CN']);
// ...
```

I suggest creating a function that calls that line with desired locale

I havent tested, but if it DOESNT switch already instantiated tables, try triggering refresh actions (like switch to card view and back).

If that fails, making look at bootstrap-table.js and search for 'locale' - might be you can call extend on instantiated table or similar then trigger view refresh to show updated locale text

Another question is what does locale actually change for you, in your instance?

**Comment by tmorehouse** [comment]
With most locale based modules that I am using (tinymce, and other i18n based modules, once eacn easily switch languages based on the two letter code (i.e. `en`) or 5 letter regiona based locale code (i.e. `en-GB` or `en_GB`, where `-` and `_` can be used interchangeably. 

In my application I have a global configuration mdoulke which defines teh language that the user has been set to.

The HTML page has `<html lang="<code>">` at the top, and any other modules either grab from this value or read the configuration module to get it.  When instantiating a tinyMCE editor, all I have to do is pass the parameter option `{ locale:'fr_CA' }`and that's all I need to worry about. IF the language file `fr_CA` doesn't exist, it tries `fr`, and if that fails it defaults back to the default language.

The documented way of changing locales using $.fn.extend on the boostrapTable object (or by extending the options passed to `$table($.extend({}, options, $fn.boostrapTable.locales['fr-CA']))` is a little kludgey.  Passing a simple option parameters of `local: 'en-GB'` when instantiating the bootstrapTable would be much more elegant (and assumes the local modules have been pre-loaded, with out the language file automargically switching the default by `$.fn.extend($.fn.bootstrapTable.DEFAULTS, $fn.bootstrapTable.locales['<code>]);`

**Comment by tmorehouse** [comment]
I would also suggest that each locale module alias itself to a full lower case and underscore based codes as well:

    $.fn.bootstrapTable.locales['en-us'] =
        $.fn.bootstrapTable.locales['en_us'] = 
            $.fn.bootstrapTable.locales['en_US'] =
                $.fn.bootstrapTable.locales['en-US'];

**Comment by tmorehouse** [comment]
And, the other nice thing, one could use data attributes on hte base table to set the local to use. (i.e. `<table data-toggle="table" data-locale="fr-CA"></table>`)

**Comment by dabros** [comment]
That may be, but changing the locale code that are already deployed is likely Not going to happen, code is already out there that will then be broken, and ive dealt with highly multi-lingual websites and can tell you that various API and code do Not always share same codes

Better to just make mapping array inside a function, and/or transform lang code you pass in there, and call to the $.extend() then

I see no reason why $.extend is at all wrong. From a design point it makes far More sense as that exactly what the locale overrides are - an extension of the standard behaivour. To do it otherwise also requires you to be passing the lang code every single instantiation, which i can assure you from working with many ajax applications can cause far more trouble.

Far better for you to call 1 function when bootstrap-table.js is loaded, then have that cascade until you decide to change your mind and set it again. The $.extend approach may be a little limited if you change after setting the first time (i havent tested so am just guessing), but it makes more sense in many ways.

Do you need tables with different locales?

Do you need to use data-attributes as somehow $.extend cant be called???

Both are exotic use cases, and i just cant see the second even happening.


It would cause more issues to force attribute approach, there is no need for duplicate approaches of attribute and $.extend(default), and there is a consistent lang code scheme already - it just doesnt happen to match yours exactly, so just work on that with a wrapper function.

**Comment by tmorehouse** [comment]
I wouldnt call it exotic.  Every other option that bootstrapTable takes can be passed as either a data attribute or an option to the contructor, whould should setting the locale be different?

When using bootstrap-table-locales-all.js, the "default" local ends up being the one thst appears last in the js file.

Adding an option to set the locale wouldnt break existing code.  One could still use the `$.extends()` method if one prefers, and the maintainers can leave the `$.fn.bootstrapTable.DEFAULTS.locale` option undefined, which also would not break existing code.

I just see the presence of a new option, which could be checked durign the `.init()` phase (or constructor/new phase), that would then check for the existance of the `locale` definition `$.fn.boostrapTable.locales['<locale>']` and if it is defined then apply it to the table insatnce options (i.e. do the `$.extend()`), and if not found then just use whatever locale is the "default" (which is the last loaded loclale definition, i.e. do nothing on init/new).

**Comment by djhvscf** [comment]
@tmorehouse can you create a PR or fiddle to see your changes related to locales logic??

**Comment by tmorehouse** [comment]
PR #1033
