### ISSUE TITLE
Working with Angular

### ISSUE THREAD

**Issue by Mansyn** [wenzhixin/bootstrap-table#1064]
I love this table. But I've ran into a few problems while implementing it in an Angular application. I've found work-arounds for most of the issues, but using a custom toolbar causes errors. I believe it's because your changing the the toolbar's DOM, and that messes with it's scope in Angular. I get 'Cannot read property 'childNodes' of undefined' errors. I'd really like to see a better way of getting a custom toolbar to fit other than using negative margins on an outside element.

**Comment by dabros** [comment]
@Mansyn - can you provide any more detail or (far better) jsfiddle?

**Comment by minyodev** [comment]
I encountered this issue as well. I get 'Cannot read property 'childNodes' of undefined errors' while using custom toolbar. When I do the code in https://github.com/wenzhixin/bootstrap-table-examples/blob/master/options/custom-toolbar.html its ok. But when I tried to put ngView (because i want to use ngResource) to my code, i started getting the said error.. I love this table as well. Hoping this issue will be fixed.

**Comment by wenzhixin** [comment]
@minyodev , you can use our extension: https://github.com/wenzhixin/bootstrap-table/blob/master/src/extensions/angular/bootstrap-table-angular.js, and the problem I think the author @dbkaplun maybe can help you.

**Comment by wenzhixin** [comment]
Any update?

**Comment by robertoforlani** [comment]
$timeout(function(){
    $("#table").bootstrapTable({....});
});
