### ISSUE TITLE
Reset searchText

### ISSUE THREAD

**Issue by wakaguaka** [wenzhixin/bootstrap-table#1184]
Hello,
I currently have menu links that triggers a bootstrap-table.
The idea is that by clicking any menu link, the searchText should reset to an empty string.

Every menu link has  different attribute values (filters):
$('#dtEntrada').bootstrapTable({
    searchText: ''
});
$('.fixed-table-toolbar').find('.search > :input').val('');                                  
$('#dtEntrada').bootstrapTable('refresh', {
    url: '@Url.Action("GetEntradas", "Generador")' + '?idfamilia=' + idfam + '&idmarca=' + idmrc,
    cache: false
});

By doing the above when there is the call to retrieve the list of products the searchText is still concatenated of the previous menu filtered: https://localhost:44301/Generador/GetEntradas?idfamilia=&idmarca=3&search=00&order=asc&limit=10&offset=0

Any suggestions?

**Comment by wenzhixin** [comment]
I think you can try:
```
$('#dtEntrada').bootstrapTable('refresh', {
url: '@Url.Action("GetEntradas", "Generador")' + '?idfamilia=' + idfam + '&idmarca=' + idmrc,
query: {search: ''}
});
```
or use `refreshOptions`?

**Comment by wakaguaka** [comment]
query: {search: ''} & 
$('.fixed-table-toolbar').find('.search > :input').val('');
did the trick combined.

Thanks

**Comment by dvelayos** [comment]
hi! i've tried this, but with no results. maybe the no-url approach is the problem?

fiddle: https://jsfiddle.net/e3nk137y/2557/

(put something on the search input, press the reset search button, the input search is cleared and the table is refreshed, but no data is shown; tried with 'refresh' and 'refreshOptions'). it's weird, because on the fiddle there is no effect, but on my webpage (much more complex) the rows comes again but with an data corruption effect (it's combined with editable extension and the cell's data are shown as '< href="')

should i pass ALL table options to the refreshOptions method?

**Comment by wenzhixin** [comment]
Create a new issue @dvelayos .
