### ISSUE TITLE
Showing data as key value 

### ISSUE THREAD

**Issue by ezazwar1** [wenzhixin/bootstrap-table#1207]
Hello 

what i actually hav a single row echoed out but i want to show its value as key/value pair just like a table with a heading like a normal table 
![image](https://cloud.githubusercontent.com/assets/13368631/8849635/d8681cf4-315e-11e5-8b33-90e9933c6843.png)
rather displaying in this fashion i want to show it as normal table not in card view cause this is a large table  i want to display it on one go

**Comment by dabros** [comment]
Look at almost any of the examples, your obviously copied code with cardView or detailView set to ture (not the default)

Also optionally use showToggle to switch between

http://bootstrap-table.wenzhixin.net.cn/documentation/

http://issues.wenzhixin.net.cn/bootstrap-table/#options/boolean-options.html

**Comment by ezazwar1** [comment]
@dabros  actually the problem is that i want to show all the fields in one go and i am unable to do that cause there is a horizontal scrollbar which shows up and i dont want that so is there a way around to show the heading as key and value and showing these values as <tr><td>key</td><td>value</td></tr>

**Comment by dabros** [comment]
@ezazwar1 

If there are too many columns to view at one time, then there are too many columns to view at one time - you just cant have it as a standard table then. 

You really need to provide any example of what your wanting would actually look like, as its still a little vague exactly what you want to achieve.

If default card view doesnt suit your needs, there are some options that 'maybe' able to solve this for you, by allowing you to compress the data.

The most like and most simple is to use css class .card-view that is used in all div wrappers for key:value pairs in cardView.

Add the following style in the scope of any bootstrap table

```css
.card-view {
  width: 50%;
  display: inline-block;
}
```

Its just an example that i quickly mocked up using http://issues.wenzhixin.net.cn/bootstrap-table/#methods/toggleView.html by seeing the html cardView generated.

The easiest way to show the fields you want might a combination of showColumns option (to enable/disable columns using dropdown button), setting the table to open in cardView and looking at the html generated when in cardView. The simple 50% width is just example, you can work much more responsive way to layout the divs by searching for responsive css examples online if needed.

You might also look into onPostBody and related callbacks in case you need to inject html or run other js to achieve desired result, but you should be fine without unless needing widely responsive styling, or per-column sizing and such (you should be able to find visible columns and column names from callback parameters, then use jquery selecter to find all div wrappers matching desired index)

On the other hand, since a little vague question, maybe these layout options help?

Checkout the detailView and detailFormatter options in the documentation (link in my last post), there should also be a way to have detailView open by default, maybe this solves?

More likely though, you would need to look at formatter option for columns, the formatter example shows a little of this: http://issues.wenzhixin.net.cn/bootstrap-table/#options/format.html

Using formatters and maybe also group columns might solve this. A formatter could allow you to take the object itself as parameter and print X attributes in each column, with whatever other text or html you wanted. You would have to be a little careful if wanting sortable columns, but a single-search-box above table (not per column) would still work fine.

**Comment by ezazwar1** [comment]
![image](https://cloud.githubusercontent.com/assets/13368631/8899106/b09eca46-344d-11e5-934d-d48f7ddec58b.png)

i want an output like this but if i dont use the card view i get a long list of columns with a scrollbar

**Comment by dabros** [comment]
then use the showColumn options and data-visible="false" (or visible:false in columns if declaring them in js code) - columnWidth and other options exist too.

**Comment by wenzhixin** [comment]
I have added an example: http://jsfiddle.net/wenyi/e3nk137y/2556/

**Comment by ezazwar1** [comment]
but it doesnt look alike to normal wenzhixin bootstrap table

**Comment by dabros** [comment]
@ezazwar1 - we have given you all you need to make a fiddle to at least try to achieve what you want, as we cant help you anymore until you know what you want and/or at least look at the options we have detailed.

ShowColumns, formatters and columnWidth are what control the content of the cells and which columns are shown, and how wide they are.

Give us a fiddle where you at least attempt to use them if you need more help
