### ISSUE TITLE
show me how to use data-ajax and data-ajax-options

### ISSUE THREAD

**Issue by ezazwar1** [wenzhixin/bootstrap-table#1236]

**Comment by dabros** [comment]
Since you asked so nicely and gave absolutely 0 context, or referanced that you have done any effort whatsoever on this yourself

http://bootstrap-table.wenzhixin.net.cn/documentation/

This shows using url:
http://bootstrap-table.wenzhixin.net.cn/getting-started/

If needed a more tailored approach: 
http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-ajax.html
https://github.com/wenzhixin/bootstrap-table-examples/blob/master/options/custom-ajax.html

To my understanding, if data="url" is used, thats ajax. Ajax options allows you to override function used to retrieve, and ajaxOptions is just jquery ajax options

http://api.jquery.com/jquery.ajax/

Btw - This is an issues forum, which means you have to have at least tried to use the product to solve your clearly defined issue. 

This is a free open-source project, be clear in what you need and share what you tried to do so far to achieve it, expected output, ect. 

we arnt paid to be mind readers (or at all)

**Comment by dabros** [comment]
The stackoverflow http://stackoverflow.com/help/how-to-ask sums up best in my opinion - the same standards apply to ANY issues forum where people arnt being paid to answer your question, but instead volunteering their time to helping complete strangers.

http://stackoverflow.com/help/how-to-ask

**Comment by ezazwar1** [comment]
![image](https://cloud.githubusercontent.com/assets/13368631/9003830/173a377e-378f-11e5-958d-1dd8f07452b4.png)
i tried a lot but i am unsuccessful

**Comment by dabros** [comment]
Why doesnt just using the 'data-url' approach work?

See the examples, there are also the old examples:  http://bootstrap-table.wenzhixin.net.cn/examples/#basic

**Comment by ezazwar1** [comment]
Actually i have to implement abort method of the ajax so thats y i want ajax request

**Comment by wenzhixin** [comment]
I think you can use `ajaxOptions` @ezazwar1

**Comment by wenzhixin** [comment]
any update?

**Comment by joomlaA1** [comment]
hello guys
can i see an example code of data-ajax-options is use? (is it like this: <table data-ajax-options="{data:{type:'I'}} >")
because i can't make it work.. thanks

**Comment by dabros** [comment]
@joomlaA1 - read the posts here and follow links

See the working example that uses ajaxRequest set via js, not passing through as string. Setting ajaxOptions via js should work, though i cant imagine it not working, maybe just different index scheme or override rather than merge.

And also, saying "i cant make it work" means nothing to us, doesnt even say that you hit F12 to see if errors, or what data was sent with the request (debugging on server side)

You need to debug and provide more info for anyone to be able to help, and it does help if you read the posts and see the fully working example, and then explain how exactly that doesnt solve your issue.

**Comment by joomlaA1** [comment]
hello

@wenzhixin @dabros @djhvscf 

please

can i see data-ajax-options in action?

the "just place inside the table tag" example, not the js example

i tried like this

\<table data-url="url/path/path" 
data-ajax-options="{ data : { type : 'I' } } "\>
</table>

data-url is working it tried. 
data-ajax-options is not.

(is it correct? i used data-url + data-ajax-option)

can i see your "just place inside the table tag" example on data-ajax-options?
(one that would pass a "data" like i tried)

thanks

**Comment by joomlaA1** [comment]
hello @wenzhixin

**Comment by wenzhixin** [comment]
seemsthat do not support data attribute. @joomlaA1

**Comment by joomlaA1** [comment]
thanks wen...

**Comment by wenzhixin** [comment]
OK, let's close this issue.
