### ISSUE TITLE
Custom toolbar- search not working and keep refreshing ! 

### ISSUE THREAD

**Issue by naimhiq** [wenzhixin/bootstrap-table#1239]
Hello guys, 

I am trying to implement the custom search in bootstrap table but the table is just keeping refreshing when I search for data. Here is the example http://growtogether.se/CustomBootstrap/customTolbar.html 

Can you please tell me what am I doing wrong  ? 

Thanks in advanced !

**Comment by dabros** [comment]
@naimhiq - that is an odd one. Ive looked carefully and can only see one differing option, the data-unique-id="3"

Can you please make this into a fiddle so we can help rule out any external factors and strip back the code and re-run if needed?

Thanks

**Comment by naimhiq** [comment]
@dabros 
Thanks a lot for helping out. Well I have updated the json data with more rows but that seems not an effect. I created a Jsfiddle  here  http://jsfiddle.net/naimlatifi/o298vp3a/  but I am getting errors for some js files and json data. 

Any clue ? 

Thanks in advanced !

**Comment by naimhiq** [comment]
Hi @dabros, 

Thanks a lot for helping out. I have added more rows for the table but that seems that is not an issue. 

I have provided here the jsfiddle http://jsfiddle.net/naimlatifi/wqv9ry34/5/ 


I really appreciate your help to make this work

**Comment by dabros** [comment]
@naimhiq - so that demo/example you linked earlier is definetly setup to use server side filtering, thats the purpose of queryParam and responseHandler, to send extra parameters and handle the server side response, which might include pagination data and similar.

I dont have a working example using your custom search box for client-side searching, but if you are sticking to client-side then just use data-search="true". You set it to false in your fiddle, but set it back to true and you can use the provided search box for seamless client-side searching.

Other than that, if you want to stick to client-side look into the data-search-text parameter, and using the 'ok' button handler to set that to the content of your custom text box.

To be very clear, **queryParam** and **responseHandler** are only of use if using **server-side** filtering, in which case you cant really mix client-side code into there.

**Comment by wenzhixin** [comment]
Just like @dabros said, the important thing is that your server don't return the correct results when you do a search, you can look at our example: http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-toolbar.html. When you enter 0 and then click the OK button, the request is: http://issues.wenzhixin.net.cn/examples/bootstrap_table/data?offset=0&limit=5&search=0, and the result is what we want:
```

{
  "total": 143,
  "rows": [
    {
      "id": 0,
      "name": "Item 0",
      "price": "$0"
    },
    {
      "id": 10,
      "name": "Item 10",
      "price": "$10"
    },
    {
      "id": 20,
      "name": "Item 20",
      "price": "$20"
    },
    {
      "id": 30,
      "name": "Item 30",
      "price": "$30"
    },
    {
      "id": 40,
      "name": "Item 40",
      "price": "$40"
    }
  ]
}
```

**Comment by naimhiq** [comment]
Yeap, thanks a lot and fixed it with client-side ;)
