### ISSUE TITLE
per-cell custom styles

### ISSUE THREAD

**Issue by rfc1036** [wenzhixin/bootstrap-table#1301]
I am trying to set a gradient on some cells, but bootstrap-table resets the cell style as soon as it is loaded:

````
<td style="background: linear-gradient(to right, #00F000 35%, #FFF 0%)">34,7%</td>
````

How can I prevent bootstrap-table from overriding my custom cell styles?

**Comment by dabros** [comment]
read the doco and look at examples

In particular, the formatter properties for both row and cell:

http://bootstrap-table.wenzhixin.net.cn/documentation/

http://issues.wenzhixin.net.cn/bootstrap-table/#options/format.html

You could use a wrapper object if you cant affect td itself, apply max width (and negative margin if needed) then the gradient.

Though since the cell object is passed in u should be able to call .parent() or similar - something you would have to play with yourself (just use console.log and try some jquery accessors like .parent() if looks promising.

**Comment by wenzhixin** [comment]
Just like @dabros said, you can apply it like this:
```
<style>
. gradient  {background: linear-gradient(to right, #00F000 35%, #FFF 0%); }
</style>
<td class="gradient">34,7%</td>
```
