### ISSUE TITLE
[QUESTION] Is it possible to add a div that surrounds all the divs with class="card-view" ?

### ISSUE THREAD

**Issue by rogelio-blanco** [wenzhixin/bootstrap-table#1328]
Hi all,

I would like to add a div that includes all the divs with class "card-view", is this possible?   Please check the code below 

```
<td colspan="5">
    <div class="card-view-group"> <!-- I would like to add this -->
        <div class="card-view"><span class="value">test1</span></div>
        <div class="card-view"><span class="value">test2</span></div>
        <div class="card-view"><span class="value">test3</span></div>
    </div>
</td>
```

**Comment by wenzhixin** [comment]
No, but you can set the class to `td` instead:
```
<td colspan="5" class="card-view-group">
</td>
```

**Comment by rogelio-blanco** [comment]
It will be nice if we can wrap all the divs, because that make it flexible to create nice vcards and add a better look and feel of the card, for example if I want to do a border to separate cards is not possible and I will see it as a column with rows.

**Comment by dabros** [comment]
@rogelio-blanco  - unless you can detail a more convincing use case, stick to using callbacks like seen in http://issues.wenzhixin.net.cn/bootstrap-table/index.html

You can see toggle.bs.table appears to be triggered each time, as well as other callbacks.

For your use case, provide a fiddle that (in callback functions) injects extra html to acheive something like what you are explaining, even if just a $.prepend, or if using $.find(..) to $.append those to your new wrapper.

Then show how a wrapper contributes - because to add more complexity to the generated html, you need a use case or a reason.

It would be a simple pull request, but we need some point for doing it, as the exotic use-cases can use callbacks - we need a good example to prove its use.

**Comment by rogelio-blanco** [comment]
Thanks for the help, I will come back with the use case and hope that can be helpful for somebody else :)

**Comment by wenzhixin** [comment]
OK, I will consider your advice @rogelio-blanco, remember any pull request is welcome.

**Comment by wenzhixin** [comment]
Added `<div class="card-views"></div>"
