### ISSUE TITLE
shared searchbar between two tables

### ISSUE THREAD

**Issue by jfrydendall** [wenzhixin/bootstrap-table#1347]
Is it possible to have two (more than one) tables on one page which shares a common search bar/ toolbar?

I have two tables on top of each other with almost identical data. Having two tables so close to each other with both having an individual search bar does not look pretty. I would like to just have one search bar on top of the two tables which allows me to search both tables. Is that possible in the current setup?

**Comment by dabros** [comment]
@jfrydendall - i started a fiddle to look at this, and id say it definetly is possible, but perhaps very difficult to do unless you rely on server-side pagination/searching.

http://jsfiddle.net/dabros/5u6zohup/

The fiddle is incomplete, because i need more specificity too about whether client or server-side. 

<br/>
Without changing core code, seems client side more difficult, though options exist to maybe:

A. update the value of 'search-text' and then call 'refresh' method (recommended but untested), or
B. have hidden search boxes that update thier contents on 'change' of global (not recommended), or
C. maybe dissect the bootstrap-table.js code for searching and find another parameter exposed that could be updated, then follow with a 'refresh' or similar call

http://bootstrap-table.wenzhixin.net.cn/documentation/#methods

<br/>

But if server side, then i would point to this great example:
http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-toolbar.html

The code here i talked about a little in #1239 (which is prob worth reading regardless, as it also highlights some issues using custom client-side search boxes).

That code should be open to being modified to apply to both tables, passing the queryParam through and calling refresh on both - just copy that table twice, with the queryParam data-attribute option, and then see if you even need to do more than just add a second 'refresh' call on $(ok)


<br/>

In any case, this should be ample to get you playing with it yourself, and if you cant understand it at all then you prob need to first rethink the issue and look at creating a layout that compliments better, as there is no standard functionality for global context search boxes.

**Comment by dabros** [comment]
Okay, so i did a little more playing, and my approach A for client-side is a bust

http://jsfiddle.net/dabros/5u6zohup/1/


        var text = $.trim($(event.currentTarget).val());

        // trim search input
        if (this.options.trimOnSearch && $(event.currentTarget).val() !== text) {
            $(event.currentTarget).val(text);
        }

        if (text === this.searchText) {
            return;
        }

Thats in boostrap-table.js, in the .onSearch function, and likely that or a similar line cause this to not work.

That means it will likely always use event.target, which is likely the default search box.

This really just leaves you with either oberwriting this functionality (can you overwrite the prototype outside of bootstrap-table.js - i have no real experience with plugins but maybe a plugin-type approach is an option), OR the more awkward approach of using callbacks to keep the search box invisible but present, and update both search boxes contents on global search text changes...

**Comment by jfrydendall** [comment]
@dabros - thank you very much for feedback. I tried the first option and I could not get that to work either. 
From your last comment, I am not getting my hopes to high on finding an elegant solution to the problem.

I will probably settle on the filter control extension http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/filter-control.html on both tables and drop the toolbar. This leaves more room for the tables, however, a bit more troublesome filtering.

However, for future reference could a global search function for fast filtering on multiple tables be a cool feature?

**Comment by dabros** [comment]
@jfrydendall - i didnt think of filter-control extension as no experience with it, i havent used this for any projects in a while and i actually made my own similar functionality almost exact same time this came out ; )

In terms of future requirements 
   - global search bar, no.
   - ability for custom **client-side** search bar, i would definitely like to see that

@wenzhixin @djhvscf  - can one of you pls add feature-request tag, as not first time a custom client-side search bar been requested, and i can definitely see its use.

**Comment by dabros** [comment]
related to #1306 , as well as other topics linked in both that and #1354

**Comment by wenzhixin** [comment]
related to #1265

**Comment by xnext40** [comment]
@wenzhixin, thx for feature request! you work is great.
I have 3 projects based on dynamic tables(billing system, bank deposits end etc....).
community waiting release this feature !!!

**Comment by guermatsamir** [comment]
Hi everyone, thank you for your job
i have a problem with "advanced toolbar", the search form is generated but the search does not work in every input of the form.

      data-locale="fr-FR"
                data-search="true"
                data-show-multi-sort="true"
                data-height="500"
                data-show-columns="true"
                data-show-export="true"
                data-toolbar="#toolbar"
                data-pagination="true"
                data-advanced-search="true"
                data-id-form="formSearchCsTable"
                data-id-table="csTable"

**Comment by guermatsamir** [comment]
Hi everyone, thank you for your job
i have a problem with "advanced toolbar", the search form is generated but the search does not work in every input of the form.

      data-locale="fr-FR"
                data-search="true"
                data-show-multi-sort="true"
                data-height="500"
                data-show-columns="true"
                data-show-export="true"
                data-toolbar="#toolbar"
                data-pagination="true"
                data-advanced-search="true"
                data-id-form="formSearchCsTable"
                data-id-table="csTable"
