### ISSUE TITLE
Custom form on advanced search

### ISSUE THREAD

**Issue by BenevidesLecontes** [wenzhixin/bootstrap-table#1354]
Hi guys! Thanks for this awesome plugin. I want to use advanced search extension and i want to use custom form on this. Any solution or documentation for this?

**Comment by dabros** [comment]
@BenevidesLecontes  advanced search extension???

First look at examples and doco, most examples use server-side searching&pagination&sorting (all the same thing) but some use client side, the key is data-side-pagination.

If you want to use a custom search box, as has been answered repeatedly now (please search first before posting, remembering to remove the issue:is-open filter if searching direct in github) if you want custom search form, you pretty much stuck with server-side searching.

But if your purpose is 'advanced search', and you want to be able to pass in and use extra search param (queryParam) then thats what you would use anyway.

#1239
#1347 

I already said in those everything else i might have said here - read through them as they about slightly different issues but are actually asking the exact same thing - how to use custom search ui.

Also #1351 maybe useful, as well as others i cant recall but you can find by searching if needed.

**Comment by BenevidesLecontes** [comment]
@dabros thanks for your reply and my sorry for bad explanation about my issue. I read these threads early but i can't find my solution. I will try to explain again, by default bootstrapTable create a form with "th" field names, what i want to do is changing this field names and use custom inputs and selects on modal popup. Can i create a custom modal and call when i click on advanced search button? 
I have a fiddle with my table and default advanced search form created by bootstrapTable, any help will be rewarding.

**Comment by dabros** [comment]
@BenevidesLecontes - please break up your paragraphs and maybe explain exactly what this '"th" field names' form is..?

What it does sound like is an exact match to the custom toolbar example (http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-toolbar.html) which is also linked and explained in #1239 and breifly in #1351 

The only difference is instead of custom toolbar, you want this as a **modal**?

To do so (which as mentioned a dozen times means server-side pagination and searching), do the following steps:

  1. Use that fiddle or create another (using custom toolbar example) and have whatever UI you want in it.
  2. Update the queryParam function in the custom toolbar example to find Your custom UI and create param list from it
  3. look at $(ok).click(function(){..})) in the same example, and use whatever ui button or element you wanted to trigger a 'refresh' call.
  4. If you set the queryParam settings to the correct function, and that function retrieves the param correctly, AND you have actual server-side code (see #1351) that returns the filtered results... Then thats it

Cant really be clearer than that, as clear example of custom UI and queryParam and all other code examples you need to do this, linked here or inside linked posts above.

**Comment by BenevidesLecontes** [comment]
@dabros thanks for your help, using this links, I managed to do what i want. Thanks again.

**Comment by dabros** [comment]
Not certain when exactly this added, but came across referance to toolbar-extension with advancedSearch option

http://bootstrap-table.wenzhixin.net.cn/extensions/#table-toolbar

@BenevidesLecontes - would appreciate more detail on what you did, in part for future referance and to help anyone else that comes across this in search or referance link.

**Comment by djhvscf** [comment]
Close this issue because it was solved
