### ISSUE TITLE
Cookie extension not working with default settings

### ISSUE THREAD

**Issue by mrpotts** [wenzhixin/bootstrap-table#1359]
Both getCookie and setCookie changes the cookie name to lowercase before getting/setting it. However, **by default the cookie names are camelcase**, so the match always fails. Thus, none of the features work (except for `bs.table.columns`, which is lowercase by default).
One is forced to pass the `cookiesEnabled` option with all lowercase names to make it work.

**Comment by djhvscf** [comment]
Here you can see that we use toLowerCase function in order to do the validation
https://github.com/wenzhixin/bootstrap-table/blob/master/src/extensions/cookie/bootstrap-table-cookie.js#L49

https://github.com/wenzhixin/bootstrap-table/blob/master/src/extensions/cookie/bootstrap-table-cookie.js#L67

I think this is not a bug

**Comment by mrpotts** [comment]
I know, in fact it's the validation that fails. The problem here is that we're validating a lowerCase string against a string that *may not* be lowerCase (by default it's not!). What happens is that `$.inArray( 'bs.table.sortOrder'.toLowerCase(), ['bs.table.sortOrder'])` returns -1, so the sortOrder is *never saved*.

**Comment by djhvscf** [comment]
Ok, I understand what you are saying.. Let me fix this. @mrpotts
