### ISSUE TITLE
Adding one group to another group

### ISSUE THREAD

**Issue by faruk77** [wenzhixin/bootstrap-table#1405]
![group](https://cloud.githubusercontent.com/assets/12938449/9811603/f5429468-5895-11e5-8c10-3c5b26c1abb6.PNG)

Hi please tell me how to add one group into another group(nested groups). Please tell how to achieve this..

1) How to hide the group headers as shown in above image. There are total 4 columns, group and instance are grouped. Please tell me how to do this in bootstrap table..

once check this link http://jsfiddle.net/jqwidgets/wzSxU/ similarly can we do with bootstrap table?

Thank you

**Comment by dabros** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#options/sub-table.html

@faruk77 - if you need more help with this then provide a bootrap fiddle using sub-table and that contains clear sign of effort on your part (comments in javascript panel for example) as you ask alot of questions but never really shown much effort on your part (and 'sub-table' is a super-obvious link in the examples list) and this really issnt difficult to implement, but is somewhat contextual to your actual data (so if you do need help, we do need your actual code)

I havent worked with sub-tables myself ever, but the classes and formatter options would help to achieve desired layout tweaks (css classes being applied to either table and using '!important' and rule heirachy to ensure proper overwrites, formatters if cell or row contents needing tweaking)

Also worth noting, depending on the actual content you want displayed, there is also the detailFormatter option, allowing you greater control over the detail view content (http://issues.wenzhixin.net.cn/bootstrap-table/#options/detail-view.html). This could include using a seperate json/js-array/js-object of data so that you add matching data from that seperate object into the detail view as needed.

**Comment by wenzhixin** [comment]
Close this because [there is no any response in 7 days](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#issues-and-labels).
