### ISSUE TITLE
Column's aligment issue

### ISSUE THREAD

**Issue by abazanvillanueva** [wenzhixin/bootstrap-table#1417]
![sin titulo](https://cloud.githubusercontent.com/assets/4936035/9859273/47c3c6ec-5aeb-11e5-93e2-ae7b5bbae5d5.jpg)

Any idea how to fix it, using 'resetView'? Or how to implement it?

**Comment by flippin-eck** [comment]
i have found calling .bootstrapTable('resetWidth') has fixed all my alignment issues.

**Comment by djhvscf** [comment]
Does the @flippin-eck solution work for you, @abazanvillanueva ?

**Comment by abazanvillanueva** [comment]
Not really. I put .bootstrapTable('resetWidth') after putting .bootstrapTable('load', arrayobject), but nothing happens.

**Comment by djhvscf** [comment]
Provide a fiddle in order to see your code, please @abazanvillanueva

**Comment by vdecristofaro** [comment]
Also have the same problem. A very bad effect on the text also.

![Sample](http://imageshack.com/a/img910/7853/yeDRjZ.png)

I successfully solved the problem either by using `resetWidth` or `resetView`

    setTimeout(function () {
        table.bootstrapTable('resetWidth');
    }, 400);

The best solution would be at least to have an event when the table has finished creation so we can subscribe the event and call `resetWidth` instead of trying setTimeout with an hardcoded number of milliseconds.
