### ISSUE TITLE
data-formatter search

### ISSUE THREAD

**Issue by shadow431** [wenzhixin/bootstrap-table#142]
After using "data-formatter" on a column to change the timezone of the Date/Time displayed, searching doesn't use new values, it uses original data.

Ex:
original: 2014-09-04 22:29:56
formated: 2014-09-04 03:29:56 pm

When searching "22" the row shows, but when searching "03", the visible hour, the table returns blank

**Comment by mgitis** [comment]
I have been looking to see where it was possible to search formatted data columns and I found this post. I see where it is possible to search a column where the data-field is set to a known field from the binding json data source, hence if there is a field called "field1" in the binding json data. then once that field is set when creating the table header it can be searched. Now suppose your binding json data was complex and all data would have to be formatted as there would be the need to have multiple custom fields; that is, the table will consist of data that is a combination of data within the binding json data forming logically a new field. For example, in the json binding object you have "firstname" and "lastname", however you want to concatenate both fields and make a new field called "name". From this example "name" does not exist in the binding json data and hence the property data-field cannot be set to "name". How do you go about setting this field so that it could be searched by the built-in search utility or the filter plugin / extension? Please note that in this case I require a custom "field" as I am currently using "operate" as data-field value and it appears that the field ("operate") cannot be searched. Also, note that the custom fields can have more complex combinations and formatting than outlined in this simple example.

JSON data: {"firstname":"john", "lastname:"doe"} 

Column Header:
<th data-field="operate" data-formatter="opNameFormatter" data-sortable="false">Name</th>

JavaScript:

function opNameFormatter(value, row, index) {
   return row.firstname + '  ' + row.lastname 
}
          
Also, note that I tried setting the data-filed to one of the know fields from the binding json object and I was able to do a search on the field. However, this will not work especially if the json object and the combinations become more complex.   Cannot use the same field name for the data-filed properties especially if within the json there is a object with multiple properties (e.g return row.personalinfo.gender and return row.personalinfo.maritalstatus i n tow separate data-formatter functions). Data-field will not recognize "gender" or "maritalstatus", but will "personalinfo" which cannot be used multiple times as data-field  appears to be unique  
                         
Thanks in advance
