### ISSUE TITLE
Table filter control when pagination on server submit response twice

### ISSUE THREAD

**Issue by javieralfaya** [wenzhixin/bootstrap-table#1501]
Table filter control when pagination on server submit response twice, i commented this.update Pagination(); into bootstrap-table-filter-control.js and problem is resolved:

    BootstrapTable.prototype.onColumnSearch = function (event) {
        copyValues(this);
        var text = $.trim($(event.currentTarget).val());
        var $field = $(event.currentTarget).parent().parent().parent().data('field')

        if ($.isEmptyObject(this.filterColumnsPartial)) {
            this.filterColumnsPartial = {};
        }
        if (text) {
            this.filterColumnsPartial[$field] = text;
        } else {
            delete this.filterColumnsPartial[$field];
        }

        this.options.pageNumber = 1;
        this.onSearch(event);
       
        //this.updatePagination();
        this.trigger('column-search', $field, text);
    };

**Comment by wenzhixin** [comment]
Can you provide a jsfiddle to show the problem and create a new pull request?

**Comment by djhvscf** [comment]
Same as #1605 , close this issue

**Comment by cyberbobjr** [comment]
I confirm the bug and the workaround proposed (comment the this.updatePagination();)
regards.

**Comment by tigris** [comment]
Is commenting out a line of the code really the solution? I'm seeing this same problem. What is the line of code doing then if we are all to just comment it out?

I'm using the `bootstrap-table-rails` rubygem, so commenting out a line of code in the vendored assets is not an easy task. So to "fix" the problem in this manner I would need to manually vendor this particular extension and keep it up to date myself with future fixes. Less than ideal.

Is the problem related to combining filter-control with server side pagination? If so, can't a better fix be to wrap that line of code in a simple if block rather than comment it out?
