### ISSUE TITLE
Is there a way to put the table inside a combobox as its "Options"?

### ISSUE THREAD

**Issue by abazanvillanueva** [wenzhixin/bootstrap-table#1505]
Is there a way to put the table inside a combobox as Options?

**Comment by dabros** [comment]
???

@abazanvillanueva - make a fiddle showing what you have and detailed explaination on what you want to achieve

https://github.com/wenzhixin/bootstrap-table#reporting-issues

**Comment by abazanvillanueva** [comment]
![rod](https://cloud.githubusercontent.com/assets/4936035/10329537/7e258316-6c88-11e5-8e28-61c43a8c6508.jpg)

**Comment by dabros** [comment]
@abazanvillanueva - so you want a more comprehensive combobox, in particular a table..?

Ive seen plenty of plugins that allow you to display custom content in option field for dropdowns (they often replace the <select> with a proper dropdown and such behind-the-scenes, and are often very flexible).

https://jqueryui.com/autocomplete/#custom-data is just one example, if you look around you could prob find and example of that using the combobox layout (see example list on right side of page) with custom content.

http://www.sitepoint.com/16-jquery-selectboxdrop-down-plugins/ - other examples, just quick google search should find more.

I fail to see why an actual table would be needed, though you could make it layed out similar to one for sure by using fixed widths (px or %) and i have used one in past that was easy to allow headers, which could match those widths if you really wanted.

Instead of focusing on the exact solution, explain the problem from the start out load - the actually business problem, not the technical one, and that should help you see what your actual business need is.

I really dont think this going to work with a combobox, mainly because why would you want it to if you couldnt reorder or filter - and that is not easy to integrate whilst there are so so many plugins for improving dropdowns already - you can easily display all the info you need and filter by starting to type in the textbox with the dropdown.

**Comment by abazanvillanueva** [comment]
Thanks for replay. The need I have to solve is that when a click in a text input, it has to display a table above with n columns  and when a  select an item, just display in the input one especific columns.
Thanks

**Comment by dabros** [comment]
@abazanvillanueva - that is a technical requirement your placing on your application, NOT a business need.

Please think and describe the actual need, namely about why that information is needed (each individual part) and why it has to be a table.

Then reread my post and look at other options for layout to decide whether table absolute needed, as what little you said indicates absolute no need for an actual table (table>tr>td) but perhaps just clear layout, so a custom html layout inside each option that includes just those key fields.

**Comment by wenzhixin** [comment]
Thanks the answer of @dabros, close the issue.
