### ISSUE TITLE
How to pass parameter  to server ?

### ISSUE THREAD

**Issue by hello-code** [wenzhixin/bootstrap-table#152]
Hi ! I have 2 questions,can you help me?

 $('#table-javascript').bootstrapTable({
                method: 'get',
                url: '/Home/GetData',
...
1. How to pass parameter  to server ?

 public ActionResult GetData(int id)
  {
            var   db=new EntityContext();
            var list=db.Department.Where(w => w.PId == id).ToList();
            return Json(list, JsonRequestBehavior.AllowGet);
}

2  Can method: 'POST' ?

**Comment by wenzhixin** [comment]
Hi @hello-code, have you solved your problem?
http://issues.wenzhixin.net.cn/bootstrap-table/152.html

**Comment by hello-code** [comment]
Issue:#200
$('#tableLogAcess').bootstrapTable('destroy').bootstrapTable({
url: vars.GetAllItens + '?DtBegin=2014/10/01' + '&DtEnd=2014/10/31' + '&Rows=10',
method: 'post'
});
Is this 'post'?
Sorry,I don't know what is the correct way.Can you speak clearly?
------------------------------------
Hi @hello-code, have you solved your problem?
http://issues.wenzhixin.net.cn/bootstrap-table/152.html
---------------------------------------
No.Thanks!

**Comment by vuducbinh** [comment]
Sorry, you answer wrong member. I don't ask that question.

Thanks.


*Binh Vu - Developer*

Blue*com*
The E-Commerce Experts
*Address*: 7/F Scetpa Building
19A Cong Hoa, Ward 12, Tan Binh District,
Ho Chi Minh City, Vietnam
*Mobile phone*: +84 902 647 961
*Web*: www.bluecomgroup.com

**Comment by havok2063** [comment]
In this example, the searching in the POST example does not work, compared to the GET version.  Tried searching on "test4" in both.  GET returns correct test4 search results.  POST returns everything (or does not work).

**Comment by prakashcse** [comment]
how to pass additional parameters to boostrapTable via javascript, i want to pass startdate and enddate.

**Comment by wenzhixin** [comment]
https://github.com/wenzhixin/bootstrap-table-examples/blob/master/152.html @prakashcse

**Comment by jaydeepgiri** [comment]
Hello,

I am using your bootstrap table for listing the data of 10 different categories. 
when table is first loaded it loads all the 10 category's data at a time. 
Now for the filtering purpose i have used a select drop-down above the table which lists all those 10 categories. 
When user wants to list the data of any particular category he selects any 1 category from that list, at that time i must display the data related to that category only. 

For this i have coded like this:

```
$('#main_id').on('change',function(){
		var main_id = $('#main_id').val();
		
//to load the table content according to the category ID
		$('#table-pagination').bootstrapTable({
		search:true,
		pagination:true,
		sidePagination:'server',
		url:'products-pagination.php',
		method:'get',
		queryParams:function(p){
			return { main_cat_id : main_id }
		}
		});
	});
```

above code fetches the data correctly but the problem is it does not allow **searching**, **Sorting** and **pagination**  What would be the issue.

Thank you..

**Comment by aiyuchen** [comment]
```
json_decode(file_get_contents('php://input')
```
