### ISSUE TITLE
how to CLEAR table?

### ISSUE THREAD

**Issue by joomlaA1** [wenzhixin/bootstrap-table#1524]
How to remove all data from table...? thanks

**Comment by dabros** [comment]
context please - namely business need for why, whether headers still needed or just rows, whether table reused for new dataset then or later??

http://bootstrap-table.wenzhixin.net.cn/documentation/#methods

The answer though is pretty obvious, the doco clearly says 'load' removes all old rows - just call load with an empty array or similar. Cant be sure that wouldnt remove headers or ect, but hence context question so we can see what fits your actual use case.

http://issues.wenzhixin.net.cn/bootstrap-table/methods/load.html

If you want help with code you gota give it a go then make fiddle with your progress so far if you then need help because it not working exactly as you need (gota explain context though too, see above): https://github.com/wenzhixin/bootstrap-table#reporting-issues

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#methods/removeAll.html

**Comment by dabros** [comment]
Or that one ; )

new method, added a month ago

**Comment by jimdunstan** [comment]
some of the documentation pages seem to have vanished.  Im trying to refresh a table in a modal, when it opens..   It just keeps showing the same data each time.

**Comment by eugeneborodkin2** [comment]
What is not clear to you? The user is asking how to empty a table (without refreshing from the server, just a client-side empty). Is this possible?

**Comment by wenzhixin** [comment]
`bootstrapTable('load', [])`
