### ISSUE TITLE
Formatter broken?

### ISSUE THREAD

**Issue by marank** [wenzhixin/bootstrap-table#1561]
https://jsfiddle.net/2smqcedg/1/

The formatted cell only displays the string value of data-formatter instead of calling the function. Am I doing something wrong or is it a bug?

**Comment by dabros** [comment]
I think this might be a bug, OR perhaps issue with jsfiddle when declared like that (all inline data)...

http://bootstrap-table.wenzhixin.net.cn/examples/#format runs from master and shows same basic syntax, just uses data url.

I tried breakpoints between line 139 - 149 as thats calculateObjectValue, and saw no obvious difference in param there, but I wasnt really for anything in particular, just something that didnt look right or match.

Updated fiddle with non min.js and some console.log: https://jsfiddle.net/dabros/2smqcedg/2/

**Comment by dabros** [comment]
Use of data array (via code start, not data-toggle) did no difference: https://jsfiddle.net/dabros/2smqcedg/3/

**Comment by marank** [comment]
Well, I found the issue!

All formatter functions need to be defined outside of the `$(function() {});` block - or directly when the page gets loaded. In the above examples, the formatters are wrapped in a `onLoad` block, which is too late: The table is already initialized.

Updated JSFiddle: https://jsfiddle.net/2smqcedg/7/ - Note that under Framework & Extensions, I've now set it to "No wrap - in <body>". And now it works just fine!

I think all that should be noted in the documentation. Could have saved me a few days of searching and trying.

**Comment by dabros** [comment]
@marank  - that is closures 101, not at all specific to bootstrap table.

The $(function(){ }); is a closure pattern, of course code isnt accessible outside that (though fiddle maybe doesnt work both ways due to how it runs, though you can tweak that in left side menu).

This has been referred to in other issues, search for 'closure' on all (open and closed) issues as im sure ive quoted that before, or look at the examples which do work (explicit js init maybe doesnt need formatter function in global if passed in same scope, but definitely needs in global scope if using data-toggle)

**Comment by dabros** [comment]
@marank - please remember to close this once your issue solved, or post again to state anything outstanding

re. doco, as i said its closure 101 so not likely to be referanced explicit in there, though your welcome to make a Pull Request yourself for the doco page regarding it - the doco is also on github and can be easily changed without requiring download and ect.

**Comment by marank** [comment]
Allright, thanks for your help!
