### ISSUE TITLE
show-columns and group-columns are incompatible

### ISSUE THREAD

**Issue by corina10** [wenzhixin/bootstrap-table#1578]
I think it would make more sense to have the items in the first row included in the show-columns menu.
This would allow hiding a column with all its subitems.

**Comment by dabros** [comment]
@corina10 - ive seen this twice now and still dont understand what it is exactly you want

Please provide more detail and an example (screenshot/s or jsfiddle) so we can understand, ensuring to include a clear current output vs desired output.

**Comment by corina10** [comment]
Hi, I created a fiddle: http://jsfiddle.net/corina10/651w38nr/
I would like to have 'Item Detail' included in the columns menu so I would be able to hide the subcolumns (price and name).
Try to hide the Item Price or the Item Name and the table should be messed up.

Thank you very much for your help.

**Comment by andersHj** [comment]
I have the same problems.
Most important for me is that the table does not get messed up when hiding a sub-column: 
It would also be really nice if it was possible to hide a col-group as well.

**Comment by chiaramcphee** [comment]
Hi there - I'm having the same problem. My table is getting messed up when hiding a sub-column. Has anyone found a way to fix this?

**Comment by dabros** [comment]
This got buried with newyear break, so thanks for posting again here to bump it up (wish github had bookmark feature of sorts, rather than auto-removing alerts on first view)

Basic issue is columns are hidden fine, but `colspan` issnt updated to match.

http://issues.wenzhixin.net.cn/bootstrap-table/assets/bootstrap-table/src/bootstrap-table.js

```javascript

// around line 60

    // http://jsfiddle.net/wenyi/47nz7ez9/3/
    var setFieldIndex = function (columns) {
        var i, j, k,
            totalCol = 0,
            flag = [];

        for (i = 0; i < columns[0].length; i++) {
            totalCol += columns[0][i].colspan || 1;
        }

        for (i = 0; i < columns.length; i++) {
            flag[i] = [];
            for (j = 0; j < totalCol; j++) {
                flag[i][j] = false;
            }
        }

        for (i = 0; i < columns.length; i++) {
            for (j = 0; j < columns[i].length; j++) {
                var r = columns[i][j],
                    rowspan = r.rowspan || 1,
                    colspan = r.colspan || 1,
                    index = $.inArray(false, flag[i]);

                if (colspan === 1) {
                    r.fieldIndex = index;
                    // when field is undefined, use index instead
                    if (typeof r.field === 'undefined') {
                        r.field = index;
                    }
                }

                for (k = 0; k < rowspan; k++) {
                    flag[i + k][index] = true;
                }
                for (k = 0; k < colspan; k++) {
                    flag[i][index + k] = true;
                }
            }
        }
    };

```

That line shows where colspan stored, so fixed and updated earlier fiddle so could be used as proof of concept for a fix.

`initTable` appears to contain the logic for setting this `colspan` index, but thats no good as its never called on column toggle, unlike `postHeader` and `postBody` (and therefore matching `init` functions)

```javascript

// around line 595

            $(this).find('th').each(function () {
                column.push($.extend({}, {
                    title: $(this).html(),
                    'class': $(this).attr('class'),
                    titleTooltip: $(this).attr('title'),
                    rowspan: $(this).attr('rowspan') ? +$(this).attr('rowspan') : undefined,
                    colspan: $(this).attr('colspan') ? +$(this).attr('colspan') : undefined
                }, $(this).data()));
            });
            columns.push(column);
```


`initHeader` has the logic printing the actual colspan value, but detection for hidden columns.

```javascript

// around line 672 

        $.each(this.options.columns, function (i, columns) {
            html.push('<tr>');

            if (i == 0 && !that.options.cardView && that.options.detailView) {
                html.push(sprintf('<th class="detail" rowspan="%s"><div class="fht-cell"></div></th>',
                    that.options.columns.length));
            }

            $.each(columns, function (j, column) {

// ...

// around line 728

                html.push('<th' + sprintf(' title="%s"', column.titleTooltip),
                    column.checkbox || column.radio ?
                        sprintf(' class="bs-checkbox %s"', column['class'] || '') :
                        class_,
                    sprintf(' style="%s"', halign + style),
                    sprintf(' rowspan="%s"', column.rowspan),
                    sprintf(' colspan="%s"', column.colspan),
                    sprintf(' data-field="%s"', column.field),
                    "tabindex='0'",
                    '>');

```


So we have 2 options to fix this, either recomputing the `colpan` on column toggle (prefered) or recompute inside `initHeader` (not recommended as only ever needed in rare use case, so why run each and every time?)


So the function to look at is `toggleColumn`:

```javascript

// around line 2077

    BootstrapTable.prototype.toggleColumn = function (index, checked, needUpdate) {
        if (index === -1) {
            return;
        }
       
       // DEBUG - use this to see what i refer to below
       // console.log('toggleColumn',[this.columns[index], this.columns, this.options.columns]);

        this.columns[index].visible = checked;
        this.initHeader();
        this.initSearch();
        this.initPagination();
        this.initBody();

        if (this.options.showColumns) {
            var $items = this.$toolbar.find('.keep-open input').prop('disabled', false);

            if (needUpdate) {
                $items.filter(sprintf('[value="%s"]', index)).prop('checked', checked);
            }

            if ($items.filter(':checked').length <= this.options.minimumCountColumns) {
                $items.filter(':checked').prop('disabled', true);
            }
        }
    };

```


The only remaining question is how to determine if is subcolumn and affect parent.

First thing i noticed is that `this.columns` is not same as `this.options.columns`, which is a 2d array to represent rows.

So `this.columns` is populated in `initTable`:

```javascript

// around line 609

        this.options.columns = $.extend(true, [], columns, this.options.columns);
        this.columns = [];

        setFieldIndex(this.options.columns);
        $.each(this.options.columns, function (i, columns) {
            $.each(columns, function (j, column) {
                column = $.extend({}, BootstrapTable.COLUMN_DEFAULTS, column);

                if (typeof column.fieldIndex !== 'undefined') {
                    that.columns[column.fieldIndex] = column;
                }

                that.options.columns[i][j] = column;
            });
        });

```

The key point appears to be `.fieldIndex`, set in `setFieldIndex` (copied in first code-block).

A little debugging (you can use live debug with 'source' panel in chrome at http://issues.wenzhixin.net.cn/bootstrap-table/index.html#options/group-columns.html and other examples) will show that `fieldIndex` is only set if it is sortable/searchable/ect column, and `this.columns` is really just trimmed list containing only those entries.

---

So thats where im up to, typed it out to help me think but still not certain best exact approach for the line/s computing which colgroup it belongs to (if any) and affecting .colspan on matching `this.options.columns` entry accordingly.

If anyone has idea, please share, this is basic javascript issue now we know all the factors.

**fiddle**  http://jsfiddle.net/dabros/92a57s7L/1/

Got a few other issues and real work, so will prob leave here for a bit to allow anyone else to have a crack at the final step

**Comment by chiaramcphee** [comment]
Hi @dabros - the Fiddle isn't working. Any updates on when this fix will be pushed? Unfortunately I'm not  a JS developer, but we need this in order to keep using Bootstrap Table. Please let us know any updated timeline. Thanks a ton for your help!

**Comment by dabros** [comment]
fixed fiddle link, here is updated fiddle:

http://jsfiddle.net/dabros/92a57s7L/2/

Still a little stuck on this last step, cant see an easy way short of iterating to build parent-child array we can use to identify group columns, then iterating again to recalculate colspan on some or all of these parents.

**Comment by dabros** [comment]
updated fiddle: http://jsfiddle.net/dabros/92a57s7L/5/

**Comment by dabros** [comment]
http://jsfiddle.net/dabros/92a57s7L/6/ - still cant think of best way to do this

**Comment by dabros** [comment]
So i rethought and decided to look at storing list of parents in each `this.columns`, so all parents can have colSpan reduced and hidden entirely if colSpan then equals "0".

This is stored in `setFieldIndex` (~line 60), with steps still needed ~line 2090 

This i believe is the smarter approach, but still does need to account for initial visibility.

Here is current fiddle, i will prob be looking in again later but got real work todo atm ;)

http://jsfiddle.net/dabros/92a57s7L/7/

**Comment by dabros** [comment]
http://jsfiddle.net/dabros/92a57s7L/8/

So this is where i leave at least for few days.

I have concat list of parents attatched to column object, some junk that for debugging but had issue with concat so for now just .ToString() calls that prove approach works.

Just gota use that or other value to referance parent so we can adjust colspan, and need to trigger immediate to account for initial `data-visible` calls so prob move logic out of `toggleColumn` (~line 2090) and into `initBody`, and/or trigger this recalc this in `initTable` too, but i feel `initBody` prob better in case any external action requires `data-visible` to be rechecked.

**Comment by dabros** [comment]
Okay, so this is solved, though not polished.

Here is fiddle at the point i solved it: http://jsfiddle.net/dabros/92a57s7L/9/

Functions (with ~line numbers) that might have changed are referenced in jspanel, and the **PR** i will make soon will ofcourse show exact diff.

**Comment by dabros** [comment]
@chiaramcphee - **PR** made, will likely take a short while before merged and new version released, but its just 2 small sections of code if overly time sensitive, just update whole version with next release in that case.

**Comment by djhvscf** [comment]
**PR** is being testing
