### ISSUE TITLE
mobileResponsive and DetailView : 

### ISSUE THREAD

**Issue by fas3r** [wenzhixin/bootstrap-table#1583]
Hello,

When using mobileResponsive plugin, the table shrink to CardView mode when the screen is too small. 

When the screen is in "CardView" mode, the column with the DetailView disappear / is not visible.

My problem is that the content of the "DetailView" is rendered dynamically and does not show only data from the table. 

Is there a way to use DetailView and MobileResponsive together ?  

Thanks.

**Comment by dabros** [comment]
@fas3r - we need something to work with, cant see any example collapsing to CardView (found http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/mobile.html but doesnt seem to toggle view, but with fiddle we could change sizing limits so that it would)

Please create a fiddle so we can help you with this (https://github.com/wenzhixin/bootstrap-table#reporting-issues). Even if you find working example, a fiddle means we can make changes in callbacks or whatever else to ensure any custom content can still be displayed.

Im thinking use onToggle and affect cardContent.

One approach might be wrapping one of the values in a class using formatter, so looks like hyperlink using css when in card view, and having that ALWAYS trigger details columns popup - or even load that into custom div below table maybe, if details row not possible while cardView open.

Also, maybe set 'smartDisplay' to false, doubtful though as MobileResponsive would be unlikely to directly use that setting (http://bootstrap-table.wenzhixin.net.cn/extensions/#table-mobile)

**Comment by fas3r** [comment]
Hello,

I reproduce the problem here : 

http://jsfiddle.net/e3nk137y/3403/

I generated the last column with formatter and add a link for each row. 

This link is opening and closing the detailview using expandrow as expected.

If you shrink the window until the table toggle to CardView, you will see that the DetailView ( First Column Diseapear ) and the link is not able to expand the row relative to DetailView as this one is not available ... 

If you have an idea, it's welcome. 

thanks by advance.

**Comment by dabros** [comment]
@fas3r - im using latest chrome, and shinking that frame or even whole window didnt switch to cardView for me, ever

I did see this error in console:

    Refused to execute script from 'https://raw.githubusercontent.com/wenzhixin/bootstrap-table/master/src/extensions/mobile/bootstrap-table-mobile.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

So i updated the fiddle and included that script inline, more than a little odd if worked for you in that fiddle, so please share browser details and whether you explicitly confirmed it in that fiddle.

http://jsfiddle.net/dabros/e3nk137y/3418/

This contains a working solution, which did take a bit more work than i expected, but i found easiest way is use that windows.operateEvents approach you had, but just account for if in cardView as detailsRow will NEVER appear if in cardView.

There maybe easier way to detect cardView than what i done, but it works well enough. OnCellClick looks promising too, i didnt finish testing but included code there you could use so that the entire row is the trigger (as only one cell in cardView, and can limit by fieldname or use default 'expand icon' if not in cardView)

The actual way you present your extra data, included if you want to actually add a row either nested or following (not recommended, just insert pretty div or such inside cell) - thats all very easy now you have referance to row and its contents.

Toggling extra content off is as easy as inline javascript 'onClick' in the html you print, or similar method. Toggling 'all' rows is similar, just use css selected to hide/destroy all. Content 'hiding' is recommended ofcourse unless sync isssues expected (ajax,ect). Simple check for existing content is included.

You will need to play with it to find what you think the best way is, but the core requirement is solved - you cant show detailsRow itself while in cardView, but you can mimic it or even better it, even use the same formatter if you want (you could also pass in extra param to same formatter if you wanted to affect it there)

It would be appreciated if you could share your final approach here when your done, so we can use it as reference for possible feature, so make it look good ;)

**Comment by fas3r** [comment]
Hello,

Regarding the error in the jsfiddle my apologize,  it was the first. The
error that you see is because I added the raw file from github .. so
jsfiddle see it as text and not as js file ..

In my case the content of the detailview is an Ajax call which simply
append a div from a different page.

I think I will do like this, when the table is in cardview,  I will keep
the approach with the "window. operate" and the button.  From my side I
noticed that the detail-view class is not present when in cardview.

So when triggering the Window.operate I will just check if detail-view can
be find, if not I will just insert a new row with insertrow and do my Ajax
again.

I'm just need to check if it's possible to listen insertrow like the other
events.

Matth.

**Comment by dabros** [comment]
@fas3r - please do share what you get working with an updated fiddle, you can mimic the ajax call fairly easily once you get it working on your local.

Use the callback 'all.bs.table' i left commented in my fiddle to see if logged through there (taken from http://issues.wenzhixin.net.cn/bootstrap-table/, which has bunch of other good code too).

I did edit fiddle after posting and updated comment, but only added a comment in click-cell.bs.table i think.

As i said above though, I would recommend just inserting into same row - i think it too easy to get unexpected behaivour if you start adding new rows, you can easily mimic the look with custom css (your ajax can also apply formatting and wrap the returned content, so remote url just needs to return minimal html, with $() or direct string replace if touchups needed (applying all formatting client side with just data array returned from ajax would reduce complexity even further).

**Comment by djhvscf** [comment]
Solution provided
