### ISSUE TITLE
Question: what is the best way to disable the toolbar whilst the table is loading?

### ISSUE THREAD

**Issue by u01jmg3** [wenzhixin/bootstrap-table#1601]
Just wanted to know if anyone has met this before and has a good way of disabling the toolbar anytime the table is loading or options have been changed.

Simple enough to hook into `onLoadSuccess()` or `onRefreshOptions()` to re-enable but wondered if anyone has tackled disabling the toolbar when the table data or options are changing (i.e. the toolbar may have changed in the DOM so disabling becomes harder).

**Comment by dabros** [comment]
@u01jmg3 - become purely cosmetic, is there any reason to do this?

Find a reproducible issue that can be caused by then, then perhaps we consider it as required.

As it stands now, refreshes arnt particularily long, have loading message anyway, and ive never heard of issues with people interacting with toolbar during this. 

Changing options and data is a wide label, maybe not always a loading message, but unless you find example where this causes issue then it seems unnecessary to me at least.

**Comment by u01jmg3** [comment]
My use case would be loading data in remotely and having the export plugin enabled. In the time it takes to load the data (so the table is empty), I can interact with the toolbar and download a blank file. This is why I want to disable the toolbar during loading.

I have successfully managed to achieve this but was curious of what others may have faced.
