### ISSUE TITLE
Re-define column width after resetView

### ISSUE THREAD

**Issue by erick-chali** [wenzhixin/bootstrap-table#1608]
I have defined the columns with a property of `width: 'npx'`, but when the action of column width is executed this property seems to be gone, is there any way to re-define the column property `width: 'npx'` after resetView?

**Comment by wenzhixin** [comment]
Provide a jsFiddle?

**Comment by erick-chali** [comment]
http://jsfiddle.net/erickchali93/8jL67Lcx/1/

here is my jsfiddle, but when the window is resized the width property is not working, so I want to know if I can redefine that,
Thank you

**Comment by wenzhixin** [comment]
![image](https://user-images.githubusercontent.com/2117018/38222890-41891fa8-371a-11e8-9541-0d092cfee83e.png)

We can see that the with attribute is applied to the td element, but because the table width is not wide enough, so here the with is the same as `max-width`.

![image](https://user-images.githubusercontent.com/2117018/38222962-af680cf0-371a-11e8-89ff-9469643f1b38.png)

So, I think we can use `class` column option and css to solve this problem: 
http://jsfiddle.net/wenyi/8jL67Lcx/11/
