### ISSUE TITLE
load method and "starred" (like mailbox)

### ISSUE THREAD

**Issue by joomlaA1** [wenzhixin/bootstrap-table#1617]
hi @wenzhixin

when i use load method(to display data to table),
the result can be like this(pure data, letters, numbers):
![normal](https://cloud.githubusercontent.com/assets/13029902/10840037/cdb394dc-7f15-11e5-839a-a0c05f6f34b2.png)

but what if i have this "star"(an icon) inside the table
and i have "is_starred"(boolean field) in database,

how can i have a "star" icon into the table using the load method(which returns only pure data)?
![smooth](https://cloud.githubusercontent.com/assets/13029902/10840038/cdb444c2-7f15-11e5-8703-e305590fd4ec.png)

How? Thanks

**Comment by joomlaA1** [comment]
@djhvscf could you help me?

**Comment by joomlaA1** [comment]
hello.
is it not possible,
load method and starred?

thanks

**Comment by joomlaA1** [comment]
hi @dabros could you help me again? please thanks

**Comment by dabros** [comment]
@joomlaA1 - use the formatter option

This will take that columns row input (td, not th) and allow you to add anything you want, including checking its value and printing specific html. 

Adding an event to toggle that value is simple ajax, nothing at all to do with bootstrap-table.

http://bootstrap-table.wenzhixin.net.cn/documentation/
http://issues.wenzhixin.net.cn/bootstrap-table/

there are plenty of good examples already out there, just search the examples pages and even github issues (remove 'is:open' filter)

here is a blank fiddle (no formatter option yet), i suggest forking and saving with jsfiddle account so you can re-fork it later for anything similar, if you havent done already

https://jsfiddle.net/dabros/t4pfrfpp/

But you really dont need any help with this, formatter is very straightforward and good examples out there.

**Comment by joomlaA1** [comment]
hey thanks @dabros you're great..

i like this part: I recommend that you send the server request to change the status, use the return of that request to confirm the new value (in case of data mis-sync). 

i think i picked up something from there.. thanks

**Comment by joomlaA1** [comment]
to @dabros: hi could you explain this more?

The only question is whether you need to affect local data if using client-side, just try changing pages, searching, use refresh button for table, ect. You will likely see at least some cases where the value is changed back. To fix either look at server side, calling refresh or some other way of affecting the data loaded into the table.

(You will likely see at least some cases where the value is changed back.)
it's happening now... on paginate.... how is this? thanks

**Comment by dabros** [comment]
@joomlaA1  ???

that image showed nothing

please make a fiddle with your work so far


You do NOT want to be using the default selection checkbox for the bootstrap-table - that is for selections and has its own handling and logic that is nothing like what we want.

Make your own column with a custom button (using formatter column option) that when clicks sends the ajax request to change the value of whatever. 

If your not able to host a copy of your db and have working urls (not localhost) for the data and that toggle function, then just do it up so it works (toggles value) on localhost and put in fiddle.

Get the basics working, use google if you cant do it because as i said above you need to know how to make an ajax function if you want to anything at all like this - there are too many tutorials out there for this for me to explain it better.
