### ISSUE TITLE
hide whole table including pagination and toolbar

### ISSUE THREAD

**Issue by joomlaA1** [wenzhixin/bootstrap-table#1667]
is there a method to do this? thanks

@wenzhixin @dabros @djhvscf

**Comment by dabros** [comment]
@joomlaA1 - seriously, pls read my other very patient posts where i explained you NEED to do jquery tutorials or the like.

Just hit F12 and figure out top level element, or wrap table in a tag with an id or classname you can target later, then use `$('.selector').hide();` and `$('selector').show();` or similar

this issnt even about bootstrap-table, just showing and hiding content in a page, just google that + jquery if you insist on shortcuts instead of 10-30min jquery tutorial that more than covers this and all other basics like closures, DOM traversal, ajax, events, ect.

**Comment by wenzhixin** [comment]
```html
<div class="selector">
    <table>...</table>
</div>
```
