### ISSUE TITLE
"search" by a search method?

### ISSUE THREAD

**Issue by joomlaA1** [wenzhixin/bootstrap-table#1687]
can we have....?

like $tbl.bootstrapTable('search', 'the text to search') that would trigger search in table

thanks

**Comment by joomlaA1** [comment]
@wenzhixin @dabros @djhvscf thanks

**Comment by dabros** [comment]
@joomlaA1 - `filterBy`

http://bootstrap-table.wenzhixin.net.cn/documentation/#methods

You could also just change the contents of the search box itself in whatever function you using

Extension like filter-control would also have similar methods, or rely on base methods like this.

If server-side pagination I would still recommend updating search-box rather than messing with queryParam or similar.

**Comment by joomlaA1** [comment]
thanks
@dabros you mentioned that "You could also just change the contents of the search box itself"
how is this? thanks

**Comment by djhvscf** [comment]
@joomlaA1 you can use this: $tbl.bootstrapTable('resetSearch', 'the text to search')

**Comment by joomlaA1** [comment]
thanks
is resetSearch new?
thanks
