### ISSUE TITLE
filterBy: superior or lower

### ISSUE THREAD

**Issue by hellhoundsx** [wenzhixin/bootstrap-table#1701]
Hi, is there an option the the FilterBy that can filter a column like:

"age : 10" > Filters column and shows only the rows with age of ten

"age : >10" > Filters column and shows only the rows with the age superior to 10

This could be done to dates too(actually what im trying to archieve in my project).

**Comment by djhvscf** [comment]
I think that is not supported. We can improve that method. Any pull request is welcome

**Comment by dabros** [comment]
@hellhoundsx - i havent worked much with it, but if you wanted to help implement this then prob look at `filter-control` and similar extensions first, rather than adding to base code.

http://bootstrap-table.wenzhixin.net.cn/extensions/

**PR** are always welcome :)

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md
