### ISSUE TITLE
Loading, please wait Issue

### ISSUE THREAD

**Issue by 4sujittiwari** [wenzhixin/bootstrap-table#1739]
I don't know what i am doing it wrong with the code and its definitely from javascript as my JSON response is well and good. Please help with this .
[code.txt](https://github.com/wenzhixin/bootstrap-table/files/44817/code.txt)
![console](https://cloud.githubusercontent.com/assets/11966793/11420205/a595b398-9452-11e5-849e-ade7e2fe4f2f.JPG)
![table](https://cloud.githubusercontent.com/assets/11966793/11420204/a5864f16-9452-11e5-80da-f456a3276827.JPG)

I have attached snapshot of table and the developer console output. I have also attached my code.

**Comment by djhvscf** [comment]
What about your JSON response? @4sujittiwari

**Comment by dabros** [comment]
@4sujittiwari - please confirm your json response as it might not match the format needed (extra level/index), which can be fixed by `responseHandler` if needed (see "side-pagination" and "responseHandler" at http://bootstrap-table.wenzhixin.net.cn/documentation/)

If you still cant fix it, then we need a fiddle to see it ourselves, https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by wenzhixin** [comment]
close this issue because there is no any response in 7 days: https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#issues-and-labels
