### ISSUE TITLE
DetailView column header not displaying

### ISSUE THREAD

**Issue by bhass2** [wenzhixin/bootstrap-table#1753]
Hi everyone!

First, Thank you for your awesome work!!
I am using bootstrapTable in a modal! 
When I set detailView to true in a modal, the detailView column header is not displayed. 
Maybe there is a bug since it works well when I use detailView out of a modal. 
Or maybe you have suggestion to help. 

Cheers

**Comment by djhvscf** [comment]
Please provide a fiddle, @bhass2

**Comment by bhass2** [comment]
![test](https://cloud.githubusercontent.com/assets/16050532/11446853/99c90772-953d-11e5-8aa1-d6d5733f682f.png)

I just tested it on fiddle, it works fine. So it comes from me. I have no idea where I am doing it wrong..
If you have a suggestion, it would be very appreciated !

**Comment by djhvscf** [comment]
@dabros do you have any idea why we are having this issue?

**Comment by bhass2** [comment]
@djhvscf @dabros I found what was the issue. It was in my Css file. Thank you again !!

**Comment by bambooom** [comment]
I found same problem in my css file since I set class `.detail` to be `display: none` for other reasons. 
The header for the `detailView` column also has class `.detail`. 
Is it better to change this defaul class name to be `detailView` ?

**Comment by dabros** [comment]
@bambooom - if css conflict, either scope your custom rule (ie `.higher-level-wrap .detail{ display:none; }`) or place use `.any-wrapper-for-bootrap-table  .detail{ display:block; }` or similar, just test different combos of selectors so that it overrides your other custom css but the inline style `display:none` still works (so no `!important` in your css styles)
