### ISSUE TITLE
Refresh Button Will not fire

### ISSUE THREAD

**Issue by LawrieDawson** [wenzhixin/bootstrap-table#1764]
Hi.  I am having trouble with the refresh button not firing when using jquery to call the url from a SQL server.   the pagination mode is server .   
chrome is not reporting any errors. 
pagination and column buttons all work.  

[bootstrap table refresh enquiry.docx](https://github.com/wenzhixin/bootstrap-table/files/49215/bootstrap.table.refresh.enquiry.docx)

**Comment by wenzhixin** [comment]
What's problem do you have? Can you provide a jsFiddle: https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md

**Comment by dabros** [comment]
@LawrieDawson - please dont ever include code in file download, just click the "Styleing with Markdown is supported" and look at how github lets you share code.

Also, dont use `data-toggle` and js init at same time, the `data-toggle` is redundant if you calling `$.bootstrapTable()` too, `data-toggle` is a call to automatically init the object, which is why http://bootstrap-table.wenzhixin.net.cn/getting-started/ clearly shows this as seperate option with not needed if using js init.

But we still need fiddle if that doesnt solve your problem

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by LawrieDawson** [comment]
fixed it.  this can be closed
