### ISSUE TITLE
Columns are not sortable by default

### ISSUE THREAD

**Issue by jbarrineau06** [wenzhixin/bootstrap-table#1794]
Hello,

According to the bootstrap-table documentation, all columns of a table are defaulted to be sortable, but that doesn't seem to be the case. Even if I set the sortable option to true in the table initialization options, it doesn't work. However, if I set data-sortable="true" on all columns, it works.  Hopefully it's not a misunderstanding on my part.

~~I can't link a jsfiddle here because we can't access it here at work (working on that), but I do have a [CodePen](http://codepen.io/jb06/pen/adOKre?editors=101) here.~~

Here is a [jsfiddle](http://jsfiddle.net/jbarrineau/fsaruk7b/3/) of the issue.

**Comment by dabros** [comment]
@wenzhixin - funnily enough i also noticed this when looking at unrelated issue just a few min ago

http://issues.wenzhixin.net.cn/bootstrap-table/index.html#options/boolean-options.html

That appears to confirm this behaivour, though no atm to look into it further sorry

**Comment by jbarrineau06** [comment]
@dabros @wenzhixin Seems the issue is fixed if you simply change the column sortable default option to true instead of false.

**Comment by dabros** [comment]
@jbarrineau06 - **PR** are always welcome :)

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by wenzhixin** [comment]
This issue is not a bug, the default `sortable` column option is `false`, http://bootstrap-table.wenzhixin.net.cn/documentation/#column-options. If you want to enable sortable feature need to set `sortable` to true, for example like this: http://jsfiddle.net/fsaruk7b/6/.

Of course, you can **Set the global sortable defaults for the table**: http://jsfiddle.net/fsaruk7b/7/
