### ISSUE TITLE
Custom scrollbar

### ISSUE THREAD

**Issue by AndrejGajdos** [wenzhixin/bootstrap-table#1818]
Hi, is it possible to replace vertical and horizontal scrollbar in bootstrap table? 

I found [this](http://stackoverflow.com/questions/26427977/custom-scrollbar-for-bootstrap-table) topic, but it works only for vertical scrollbar, not for horizontal scrollbar.

Working [example](http://plnkr.co/edit/IHnFAiVh0gfcmBdy05Mt?p=preview) without large columns

Not working [jsfiddle](https://jsfiddle.net/he1u2zo0/) with large columns.

**Comment by dabros** [comment]
@AndrejGajdos - as noted in https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#using-the-issue-tracker, prob best you post this on StackOverflow as this is a personal request rather than a core feature request or core bug fix

Be more people there who have worked with `$.slimScroll`

**Comment by AndrejGajdos** [comment]
Thanks for reply. slimScroll doesn't supports horizontal scrollbar, but [LionBars](https://github.com/Charuru/lionbars) does. More info on [SO](http://stackoverflow.com/questions/34363971/custom-horizontal-and-vertical-scrollbar-for-bootstrap-table)

**Comment by wenzhixin** [comment]
solved in [SO](http://stackoverflow.com/questions/34363971/custom-horizontal-and-vertical-scrollbar-for-bootstrap-table)
