### ISSUE TITLE
Formatting of editable cells

### ISSUE THREAD

**Issue by AndrejGajdos** [wenzhixin/bootstrap-table#1819]
If cells are editable and their content is stringified json, editable cells aren't formatted correctly (as a string).

[jsfiddle](https://jsfiddle.net/0oehnzk2/1/)

For example if content of cell is `"{x:5,y:6}"`, string is formatted as `[object Object]`

**Comment by dabros** [comment]
@wenzhixin @djhvscf - so my first thought was formatter of course

But i found extension using old/simple method of testing for formatter, rather that `CalculateObjectValue`

So i included `bootstrap-table-editable.js` inline and made change there rather than **PR** yet as im not sure this best approach

If anyone can proof it for me, then im happy to make **PR**, else please suggest how better to handle formatter. 

By toggling `data-editable` and `data-formatter` you can see its that `CalculateObjectValue` will still return as string, but unless it has whitespace or other char to stop it being json string, then `x-editable` plugin is what using that `data-value` and prints "[Object]".

This means a solution prob exists in `x-editable`, but this works too as it allows simple stringFormat " %s" value for `data-formatter`.

The changed line is not a fix of the core issue, but updates how the extension uses formatter, making workaround much easier. 

There is a referance to stringified json here: https://vitalets.github.io/x-editable/faq.html, and prob more out there, if anyone thinks it better to pass editable param or change how we call editable. 

But this works well enough.

https://jsfiddle.net/dabros/0oehnzk2/2/

I really just changed this line:

```
var result = _formatter ? _formatter(value, row, index) : value;
```
to
```
var result =  $.fn.bootstrapTable.utils.calculateObjectValue(column, _formatter, [value, row, index], value);
```

@AndrejGajdos  - as you can see, you just need a formatter to add white space to STOP that value appearing as an object.

Im not certain this is absolute best way, hence above request, but it works and is simple (i included inline stringFormat and testFormatter as example).

**Comment by wenzhixin** [comment]
Thanks @dabros
