### ISSUE TITLE
Detail View

### ISSUE THREAD

**Issue by Pat3ck029** [wenzhixin/bootstrap-table#1829]
Hi, i'm trying to use the detail view method and i'm getting this result whenever i expand the detail view.

mealType: 2
_mealType_id: undefined
_mealType_class: undefined
_mealType_rowspan: undefined
_mealType_title: undefined
_mealType_data: [object Object]
serviceType: 2
_serviceType_id: undefined
_serviceType_class: undefined
_serviceType_rowspan: undefined
_serviceType_title: undefined
_serviceType_data: [object Object]
foodSource: 2
_foodSource_id: undefined
_foodSource_class: undefined
_foodSource_rowspan: undefined
_foodSource_title: undefined
_foodSource_data: [object Object]
startTime: 2
_startTime_id: undefined
_startTime_class: undefined
_startTime_rowspan: undefined
_startTime_title: undefined
_startTime_data: [object Object]
endTime: 2
_endTime_id: undefined
_endTime_class: undefined
_endTime_rowspan: undefined
_endTime_title: undefined
_endTime_data: [object Object]
pickupTime: 2
_pickupTime_id: undefined
_pickupTime_class: undefined
_pickupTime_rowspan: undefined
_pickupTime_title: undefined
_pickupTime_data: [object Object]

i just copied the detail formatter from one of your examples.

function detailFormatter(index, row) {
        var html = [];
        $.each(row, function (key, value) {
            html.push('<p><b>' + key + ':</b> ' + value + '</p>');
        });
        return html.join('');
   } 

Thank you so much.

**Comment by dabros** [comment]
@Pat3ck029 - please format your posts (click that 'Styling with Markdown is supported' button in the github editor)

Also, we absolutely need a fiddle for issues like this:

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

Please use the templates there as examples or to fork from, and get as close to your use case as possible, even if you have to move a subset of your data into a javascript array and load from that instead of via url.

**Comment by wenzhixin** [comment]
close because [there is no any response in 7 days](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#issues-and-labels)
