### ISSUE TITLE
How to prevent the editable pop-up box shut down

### ISSUE THREAD

**Issue by zyz** [wenzhixin/bootstrap-table#1850]
editable-save.bs.table event, if input is empty, 
How to prevent the editable pop-up box shut down?

**Comment by dabros** [comment]
@zyz - there are options for controlling x-editable you can pass through, notably a full x-ediable config set if setting via js (column editable index instead of via data-editable="true" for each column)

However, it sounds like you talking about anomalous behaiviour, though it will still be part of x-editable itself please share a fiddle demonstrating this so we can confirm it (https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports)

https://github.com/vitalets/x-editable
http://vitalets.github.io/x-editable/docs.html#editable

http://bootstrap-table.wenzhixin.net.cn/extensions/

**Comment by wenzhixin** [comment]
Please provide a jsFiddle to show what you mean.

**Comment by dabros** [comment]
@zyz - still waiting

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
