### ISSUE TITLE
Do not collapse a detail view after table initialization or refresh (Feature request)

### ISSUE THREAD

**Issue by monchoz** [wenzhixin/bootstrap-table#1899]
Please include a feature kind of like a param in `refresh` method that prevents closing or collapsing rows that are expanded. 

I use this workaround https://github.com/wenzhixin/bootstrap-table/issues/1603 and it's perfect in some cases like when you need to update a specific row and the action is triggered by a button inside the detail view (for instance).

Regards!

**Comment by dabros** [comment]
similar to #1498, and seems an interesting feature to me as poor performance in some circumstances if full refresh for single row update and ect.

**Comment by wenzhixin** [comment]
I think they are not the same problem.

**Comment by wenzhixin** [comment]
ref #1593

**Comment by monchoz** [comment]
Thanks! that is a good approach that also works. Personally there are some issues I still dislike, in a context, I use detail rows with tab contents in a very CSS styled way on every row and whenever a row gets updated it does not remain in the same same tab, the whole detail content is re-constructed, I can live with that but one thing I don't is the page scrolling to top every time `initBody` gets called, do you know how can I prevent that?

My thoughts about that were on line 1573 but got no luck

`if (!fixedScroll) {
   this.scrollTo(0);
}`

Thanks!

**Comment by dabros** [comment]
@monchoz - a passing thought on scroll issue is that maybe its the browser scrolling to top because there is no content below.

Try using fixed height for table and or its container, height options exist but just as easy to use min-height on your main content containner (assuming nav,container,footer type approach).

`initBody` recreates the contents, so for x milliseconds there is no content there and the whole page gets shorter.

But thats assuming you mean "page" when you say "page", instead of when internal scrollbar in tbody appears.

If you did mean internal scrollbar, then for exact same reason it would scroll up but you could do something like storing current scroll position during `onPreBody` then restoring in `onPostBody`, or equatable approach using other callbacks.

**Comment by monchoz** [comment]
@dabros Thanks! I tried using a fixed height and got the same behaviour. I think caching the current scroll position could be an approach but not sure if still will move from position for a glyph, it's kind of annoying, have to try.

**Comment by manukieli** [comment]
If a table have detailView = true and some row are expanded.
If I update the data of this row, the detailView is collapsed.
How can I keep the detailView open???

**Comment by UtechtDustin** [comment]
@manukieli 
As you maybe see this issue is marked as "feature", its currently not possible.

**Comment by wenzhixin** [comment]
https://bootstrap-table.com/docs/api/table-options/#detailview
> You can set the `uniqueId` option to maintain the detail view state when refreshing the table.

Example: https://examples.bootstrap-table.com/#options/detail-view-unique-id.html
