### ISSUE TITLE
search result over column with data-field="fields.plan_code" not working

### ISSUE THREAD

**Issue by molavy** [wenzhixin/bootstrap-table#1906]
that seems search over field with field data like fields.plan_code not working
i try debug this problem and found in initsearch column selected just first part(fields)
$.grep(this.options.data, function (item, i){console.log(i);console.log(item);})
return this

VM821:1 Object {pk: 17, fields: Object}
fields: {
creation_date: "1394/10/22"
mdl_markaz: "markaz 1"
mdl_plan_process: "1"
onvan: "ghfghf"
plan_code: "94-10-1-000017"
proc_status: "sarparast"}
**proto**: Object
pk: 17__proto__: Object

**Comment by wenzhixin** [comment]
Please provide a jsfiddle: https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports

**Comment by molavy** [comment]
please search "blog" and "حسین" in this jsfiddle
that work for blog but not for حسین
http://jsfiddle.net/e3nk137y/4365/

**Comment by dabros** [comment]
@wenzhixin - confirmed that support for searching certain character sets fails when in the 'name' column, possibly due to its definition in `fields` column index.

Same characters in 'description' field appear to search fine.

http://jsfiddle.net/dabros/2woz3jqa/

I might look into it more again today, but am busy atm.

**Comment by dabros** [comment]
I was for a moment thinking that as a workaround @molavy could use `formatter` and use `return row.index;`, that 'should' work to make it searchable, as it will use content of the cell direct, specifying `sortName` should allow sorting if that is broken by this. 

But no, even with `data-sort-name` and `data-field`, that generated column refused to search. It made me think that 'blog' was a fluke too, and it was.

Its exactly as was noted at very top, grep or similar only returns first part.

Updated my fiddle and set to base again: http://jsfiddle.net/dabros/2woz3jqa/

---



I might look into it more again today, but am busy atm.

**Comment by molavy** [comment]
seems this issue require more attention, how can i fix this problem

**Comment by dabros** [comment]
@molavy - no time to look into it further myself atm, but i left notes above and setup my fiddle to be fairly robust test case.

The issue is the grep line, look into seeing how that works and whether it can be replaced/improved. I didnt really get much into that bit yet, and not too familiar with grep myself anyway.

**Comment by wenzhixin** [comment]
The latest version has fixed this problem.
http://jsfiddle.net/e3nk137y/4365/
