### ISSUE TITLE
Event after tablesort is finished

### ISSUE THREAD

**Issue by user0815123** [wenzhixin/bootstrap-table#1912]
Hi guys,
im having trubble with a tooltip on a tablecell... to create the tooltip i use this js:

$(document).ready(function() {
    refreshTooltip();
    
   $('html').on('hidden.bs.dropdown', function () {
        refreshTooltip();
    } );
    $('.btn btn-default').on('click', function () {
        refreshTooltip();
    });
    /* THIS IS NOT WORKING
    $('.table').on('sort.bs.table', function () {
        refreshTooltip();
    }); */
} );

function refreshTooltip(){
    $("[data-toggle='tooltip']").tooltip({html: true});
}

but as u can see i have to catch every event that changes/refreshes the table to recreate the tooltip.. i assume that is a dirty way to code :D.. 
Now i need to catch the sorted event because thats i hope the last reason for my tooltip to disapear.. Is there such an event showing the table has been sorted like the event for closing a dropdown-menu "hidden.bs.dropdown"?
Or is there a better way to refresh the view of the tooltop (the value of the tablecell does not change!!! just the tooltip disapears!)

I hope u guys can help me.. Thx!

**Comment by djhvscf** [comment]
Please provide a fiddle but in the meantime you can try to use the "all.bs.table" event. See the documentation: http://bootstrap-table.wenzhixin.net.cn/documentation/#events

**Comment by dabros** [comment]
@user0815123 - as djhvscf says, create a fiddle https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

I would also recommend using `onPostBody` aka `post-body.bs.table`.

If those tooltips contained inside the table, as there are many actions (sort, search, explicit refresh, update, ect) that will require the table rows to be regenerated.

So `post-body.bs.table` might have something like `$("#table [data-toggle='tooltip']").tooltip({html: true});`. Just use F12 to check the generated html for most appropriate location, remember table itself now inside of `.fixed-table-body` wrap.

As a side note, you might instead use a formatter or similar to call something like `$('<a>').html(value).tooltip({html:true})` (wrapping in an anchor and calling tooltip against just that, rather than entire view), that should actually reapply each time that value is printed, and just to that element so less redundant `$.tooltip` iterations over already established elements.

And if needing similar/same treatment for table headers or such, then same exact rules apply with `post-header.bs.table` or whatever other element you want to target (footer should be covered by `post-body.bs.table` though).

**Comment by wenzhixin** [comment]
#864 Table with tooltip and popover: http://jsfiddle.net/djhvscf/8vgk5626/14/

ref #1765

**Comment by gtalarico** [comment]
Thank you wenzhixin. Solved for me.
