### ISSUE TITLE
server-side update

### ISSUE THREAD

**Issue by the1994** [wenzhixin/bootstrap-table#1939]
Hello,
I  want to make new row and save data into json file. 
I saw #1851 and #1272.
and get to know [x-editable](http://vitalets.github.io/x-editable/docs.html).
Here is my page: http://pallada.dothome.co.kr

But i have no idea what `url: /post` or `url: post.php`(server-sdie script?) means.
I searched many people's issues. 
And I think that is .php files or just directory's name(?).
I don't know how to write server-side script code. 

Is there a simple example code or 
Should I start to learn PHP & mysql?

Thanks.

**Comment by dabros** [comment]
@the1994 - you need to find tutorials for php+mysql (or whatever your Database is)

What your looking for with editing capability is part of CRUD, google it. 

Have endpoints (urls, either php file or codeigniter type route or similar)  where you perform each operation (create,read,update,delete). Your best off looking at basics using simple tutorial and generic test html form/table before worrying at all about bootstrap-table, then integrate it using your new understanding of the basics.

But i have come across this here, which may help you get started, though you seriously do need to google any steps you dont understand rather than post here - learn the proper way by understanding basics first.

Format of data required #1931 (has link to CRUD example too)
How do I use custom JSON data to Server Side Pagination? #1862

I havent used https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/editable myself, but seems you might just put the ajax request to make the actual update in the callbacks, or it is sent automatically, since opening http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/editable.html and hitting F12 to monitor network requests shows nothing sent on editable save by default.

**Comment by the1994** [comment]
How kind of you!! Thanks.

**Comment by dabros** [comment]
@the1994 - see #1968 that i linked here, just noticed you can prob still use `x-editable` ajax options, which is prob what you were quoting as not understanding earlier.

Same approach, get it working outside this, then decide if callback or passing through as `x-editable` object works best for you. Same endpoint i guess, but undoubtably many working examples of `x-editable` which you might find easier to use.
