### ISSUE TITLE
Sort method

### ISSUE THREAD

**Issue by tmatinla** [wenzhixin/bootstrap-table#1948]
I would like to sort the table with a JS method, but there seems to be no "sort" method available. Is there any way to achieve this currently? (Use case here is that the table header is hidden and sorting would be done with an external toolbar/buttons.)

**Comment by dabros** [comment]
@tmatinla - a custom ui for sorting is very irregular, never heard of anyone needing that

Why dont you make a fiddle (templates at https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports) and put in your custom toolbar, showing us the type of UI you want to control it with and giving us a playground to look at this more.

Also be sure to explain why custom sorting UI is neccessary, from:

1. A end user perspective (what sorting are users expected to require, no mention of ui or implementation, just business need), as well as...
2. A developement perspective (if particular functionality has been imagined that needs such UI)

**Comment by tmatinla** [comment]
Thanks! But I'm sorry, this custom sort thing that was implemented was not the thing I had in mind (it might be usable as well, though). What I was thinking is ability to say, for example, $table.sort('field-id', 'asc'); or similar in my code, i.e. call sort from my code instead of applying sort via clicking table header (since header is hidden in my case but I have buttons for sorting the table).

**Comment by dabros** [comment]
@tmatinla - my question still stands from above, please provide a fiddle (forking one of the examples on the page i linked to) and dummy ui mimicing how you plan to use this, and some reasoning why standard approach (via table header) not suitable (including "why is it hidden?")

Thanks

**Comment by wenzhixin** [comment]
how you plan to use this feature?

**Comment by wenzhixin** [comment]
please provide a fiddle.

**Comment by tmatinla** [comment]
http://jsfiddle.net/LrhL0w9q/

(I'm actually also using https://github.com/adamwulf/Columnizer-jQuery-Plugin to put the table in columns and that's why I don't want the table headers to be shown.)

DataTables has similar method: https://datatables.net/reference/api/order%28%29

**Comment by aretteen** [comment]
One example I am trying to implement is to use with Bootstrap Tour to show a non-technical user the functionality of a sort. It'd be nice to have a sortColumn method much like there is a resetSearch method and others. I'm sure it can be done in other ways, but a method included in the library would make it much easier.

**Comment by lowegreg** [comment]
This feature would really help me.  I need to resort the rows prior to an append.  This seems to be the only way to make sure that the new row is created at the top of the table consistently.  

I can provide a fiddle if you still need one.

Cheers,
Greg

**Comment by jrsconfitto** [comment]
Hi! I think I may have run into a case that provides some reasoning for a programmatic sort method for a column.

An application I'm developing is designed to provide URLs that change when sort changes with `history.pushState`. This is done in order to allow the user to bookmark the URL and pick up where they left off. (I know the bootstrap-cookie extension provides similar functionality, but I like that the user can see the sort and order properties in the URL and be able to use the bookmark across devices.)

When `popstate` events occur, I'd like to be able to sort the table, with the given order, according to the URL given after the `popstate`.

I'm willing to accept feedback on my design (maybe there's an inherent flaw, or better way to do this?) and whether or not this is sufficient justification for the ability to sort a particular column through a method on the table.

It looks like I might be able to use the `refresh` method instead of using a programmatic sort? I haven't tested that yet, but plan to.

_Thanks for a great component!_

**Comment by djhvscf** [comment]
You can use customSort table option
