### ISSUE TITLE
Sort with thousand seperators and decimal numbers?

### ISSUE THREAD

**Issue by theBear** [wenzhixin/bootstrap-table#1990]
There are worldwide different ways for the decimal numbers and thousand seperators. Is there a way to use this with bootstrap table?

For example: **100000000** should be displayed as **100.000.000** in the table column, but should be still sortable by **100000000**

Similar Question for decimal separators: **12345.6789** should be displayed as **12345,6789** in the table column, but should be still sortable as **12345.6789**

Any idea how to realize that? Thx.

**Comment by dabros** [comment]
@theBear - create a fiddle (https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports) that has examples of these.

Apply simple formatter/s to achieve your desired format/s, then if your expected result does not equal actual result, try using custom sorter on that column.

http://bootstrap-table.wenzhixin.net.cn/documentation/#column-options
http://issues.wenzhixin.net.cn/bootstrap-table/index.html#options/format.html
http://issues.wenzhixin.net.cn/bootstrap-table/index.html#options/custom-sort.html

When you start actually using it, youll see pretty quickly that not so big an issue as it always sorts just that ONE column, with the SAME formatting.

So long as `100.000.000 > 099.999.999` and/or `100.000.000 > 99.999.999`, then your fine. 

`100.000.000` does NOT have to `> 99999999`, because that same column has same formatting, so assumingly both will have same seperator syntax. 

And you can always apply sorter to the column that strips seperators or whatever else you need to make it conform in rare cases.

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!

**Comment by jakobdo** [comment]
I'm having the same issue.
Please see this jsfiddle: http://jsfiddle.net/kk9pLtuc/
My numbers is formatted using the "backend" and using "selected" language from the browser. (da or uk)

**Comment by mhosks** [comment]
It's happening for me too. The jsfiddle above mimics my issue.

**Comment by wenzhixin** [comment]
I think [custom-sort](http://issues.wenzhixin.net.cn/bootstrap-table/index.html#options/custom-sort.html) can solve the problem.

**Comment by crockstylie** [comment]
Hello, 
I'm having an issue when sorting a column.
I think it belongs here.
The 10s are sorted between the 2s and the 1s (example : 2,1 - 2 - 10,4 - 1,9 - 1,8).
First I thought it was because of coma separated numbers (because we are french)
That issue lead me to that thread.
I thought I'll find an answer, but there is almost that issue on your examples.
You can see it here : https://examples.bootstrap-table.com/index.html
You sort by Item Name and go to page 3 to see that items are sorted as following : 

- Item 80
- Item 8
- Item 799
- Item 798...

which is alphabetically accurate, but not numerically.
