### ISSUE TITLE
editable extension conflicts with export extension

### ISSUE THREAD

**Issue by MOOREZHANG64** [wenzhixin/bootstrap-table#2043]
When i trying to implement export extension with editable fields, data-fields which implement data-editable won't display normally after selecting 'Export all / Export Select', something likes the followed image, name fields display with a link.
![screen shot 2016-02-29 at 5 14 14 pm](https://cloud.githubusercontent.com/assets/10070015/13390264/4ea39c20-df08-11e5-91d2-95f13d6ae22d.png)

Issue can be found on this jsfiddle link:
http://jsfiddle.net/mengzhang/zh11qbcm/

So, as i concerned, data-editable bounds to data-fileds, before normal data. 

Thanks!

**Comment by dabros** [comment]
@therobbiedavis - not a bad workaround, performance wise doesnt even seem too big a hit compared

The issue doesnt seem to relate around the `columns`, and fix itself if they are explicitly reset.

For example, this works just as well:

```javascript

var mycolumns = [{
      field: 'state',
      checkbox: 'true',
    }, {
      field: 'name',
      title: 'Name',
      editable: {
        type: 'text',
      }
    }, {
      field: 'stargazers_count',
      title: 'Stars',
    }, {
      field: 'stargazers_count',
      title: 'Stars',
    }, {
      field: 'forks_count',
      title: 'Forks',
    }, {
      field: 'description',
      title: 'Description',
    }];

  $('#toolbar').find('select').change(function() {
    $table.bootstrapTable('refreshOptions', {
      exportDataType: $(this).val(),
      columns: mycolumns
    });
  });

```

`refresh` and `resetView` methods seemed to have no effect, since i guess they just focus on loading data and affecting containers respectively, they dont force the columns themselves to reset.

But this is still a workaround, so i encourage anyone to look into this more, notably chasing what actually happens when `exportType` options is changed and how that is NOT triggering required editable code (which it should have been since they both do most of this in extensions of `initBody`, but timing and similar issues could maybe contribute to this).

**Comment by wenzhixin** [comment]
This bug has been fixed in the latest version.
