### ISSUE TITLE
Access to current table elements in onPostHeader function

### ISSUE THREAD

**Issue by duduklein** [wenzhixin/bootstrap-table#2079]
Hi, 

I have multiple tables (bootstrap tables) in my page and I'm using select2 for my selects in the `td`s. I have looked at #1254 which says that the select2 initialisation must be set in the onPostHeader event. So far, so good. One implementation is here; http://stackoverflow.com/a/31975429

The problem is that in this case, I can not get only the select2 for the current table. I would like to be able to do something like this: `$(this).find('.finditem').select2({...})`, so I can make ure to only select the current table's elements.

Is it possible to do it right now?

Thanks

**Comment by dabros** [comment]
@duduklein - i fail to see how `$('#table').find` or (depending on timing) `$('#myWrapperAroundTable').find` wouldnt work.

Your question isnt even related to `boostrapTable`, its just using selectors - so hit F12 and inspect generated html to see what pathing you need to pick up on just those items.

**Comment by duduklein** [comment]
@dabros - It's not a matter of selectors. Let me ask you the question differently.

Suppose I have multiple tables that I can access like this `$("table")` all the tables have en input element where I want to place an "one" handler. If I use `$("table").find(''.my-input")` in every onPostHeader handler, I will not add one handler to each element but "n" ("n" being the number of tables I have).

How can I achieve this withing bootstrap-table?

**Comment by dabros** [comment]
@duduklein - sorry for confusion, I thought you had seperate event handlers.

Did a little playing and yes, `$(this)` should work.

Just try this in your code to test, taken from the example I liked above.


```javascript
        $('table').on('all.bs.table', function (e, name, args) {
            console.log(name, args);
            console.log('this',[name,this,$(this)]);
        });
```

As with all such things, do be careful of scoping and keep all variables you use inside purely relative (like `$(this)`) or scoped similar, usual stuff, but it works fine so if issues just check your scoping.

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!

**Comment by ronaldbarendse** [comment]
The issue @duduklein is facing still persists if you're using the `onPostHeader` method on the BootstrapTable itself (instead of the jQuery instance and the `post-header.bs.table` event).

Eg. when setting `jQuery.fn.bootstrapTable.defaults.onPostHeader` to run some logic for all tables, the function is invoked with `this` set to the options and therefore a reference to the table instance is not available (because of `this.options[BootstrapTable.EVENTS[name]].apply(this.options, args);` in `BootstrapTable.prototype.trigger`).

A possible solution would be to add an argument with the jQuery table instance or changing the binding to the BootstrapTable instance instead of the options object.
