### ISSUE TITLE
data-filter-control="select" with Pagination issue

### ISSUE THREAD

**Issue by edsoja** [wenzhixin/bootstrap-table#2091]
There seems to be an issue using data-filter-control="select" with pagination.  The select only shows values from the initial page.  Additional values are added after selecting additional pages.

1. Select dropdown only show values on page 1
2. click on page 2
3. Select now shows values from page 1 and page 2
4. click on page 3
5. Select now show values from page 1, 2, and 3

fiddle: https://jsfiddle.net/edsoja/cyuqeghz/1/

I believe the issue may be in bootstrap-table-filter-control.js, line 143
`for (var i = bootstrapTable.pageFrom - 1; i < bootstrapTable.pageTo; i++) {`

**Comment by edsoja** [comment]
Should line 143 be something more like this?
`for (var i = 0; i < bootstrapTable.options.totalRows; i++) {`

**Comment by Bertjuh** [comment]
I just started using this plugin and this was the first thing i've ran into. I use the code from CDN so it would be awesome if this is fixed. Subscribing to this issue.

**Comment by djhvscf** [comment]
This only works fine when the sidePagination is set to `client` because if it is set to `server` we won't be able to know all the data in the server... If the sidePagination is set to `server` we will add items to the select control as we change the page number. if this is not ok for you, you can use `filterData` column options in order to load all the items that you want.

**Comment by Bertjuh** [comment]
Awesome! thanks for your quick answer. The pagination in our case should be set to server because of the huge amount of rows and data objects that are loaded on each pageload. Which was causing a slight performance penalty.

**Comment by edsoja** [comment]
Thanks for the info and fixes.
