### ISSUE TITLE
Baseline of custom toolbar  diff with existing one.

### ISSUE THREAD

**Issue by vingorius** [wenzhixin/bootstrap-table#2160]
When i add custom toolbar with button, it diff it's baseline with existing one.

i check it firefox, chrome, ie. same problem are there.

For your information i attach two screen file, one is existing example, the other is mine.

thanks in advance.

**Existing Example**
![screenshot-2016-04-05 17-21-02](https://cloud.githubusercontent.com/assets/5274928/14275882/c687b410-fb55-11e5-8420-70d8b0285c1b.png)
left "OK" button and right "Refresh" button baseline are different.

**Custom Toolbar, toolbarAlign=right**
![screenshot-2016-04-05 17-28-27](https://cloud.githubusercontent.com/assets/5274928/14275839/5d459152-fb55-11e5-9de9-a7800eceb715.png)
"Refresh" button and "Plus" button baseline are different

**Comment by dabros** [comment]
ref: #2156 

@vingorius do look at my last post there, wrappers and some overriding css is all you need here, if you want help discovering underlying issue though we do need a fiddle (https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports)

**Comment by vingorius** [comment]
Thanks @dabros , I fork custom toolbar fiddle, and just add "data-toolbar-align=right". There's about 1px gap between two group. please refer http://jsfiddle.net/vingorius/7bxujpc8/2/

**Comment by dabros** [comment]
@vingorius - use F12 and 'inspect' (or comparable tool in other browsers) to check what css is actually applied.

Underlying cause is that the 'pull-right' is applied at different level, and as such the `.btn-group{display: inline-block;}` rule causes slightly different layout when float is not applied. 

Many possible solutions, prob easiest is something like `#toolbar{ float:right;margin-left:2px;margin-right:5px}`, though that might seem redundant float it does mimic the main toolbar. Similar affect by adding `pull-right` to `#toolbar` too, but youll prob want to overwrite margin too.

Another solution, below `#toolbar` use `<div class="btn-group pull-right">`, mimicing the other btn-group. Its a little odd you added `btn-group` class to `#toolbar` itself in the first place, just semantically speaking as its intented as the wrapper to all your addons, so I would recommend this more than adding `pull-right` to `#toolbar` or direct float.

**Comment by vingorius** [comment]
@dabros - i think it's a bug, because i just add "data-toolbar-align" option on example jsfiddle.
After many tweaking css, i found a solution.
```css
#toolbar {
  float:right !important;
}
```
Refer this jsfiddle http://jsfiddle.net/vingorius/7bxujpc8/3/

**Comment by dabros** [comment]
@vingorius - read my last post again, i said that and explained why its not a bug

The issue came from YOU applying a `.btn-group` class to the `#toolbar` wrap without checking whether it had same other properties as the existing `.btn-group` you were trying to mimic/complement

**Comment by vingorius** [comment]
OK @dabros I understand you.

By the way, for your information,  I **didn't** add `.btn-group` , the example has it.

Please check @wenzhixin 's jsfiddle:  http://jsfiddle.net/wenyi/e3nk137y/34/

Thanks very much for your kind help.
