### ISSUE TITLE
example of php file to get server side

### ISSUE THREAD

**Issue by joefreire** [wenzhixin/bootstrap-table#2165]
hi, i try to get json enconde with php but dont work well

do have any class in php to enconde json as bootstrap-table need?

thanks

**Comment by dabros** [comment]
@joefreire - then google `json_encode mysql php` or similar

There are plenty of examples of the required format, literally all examples as you can hit F12 and see the data passing back and forth.

Read the doco, especially `url` in http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options

See the examples: http://issues.wenzhixin.net.cn/bootstrap-table/

There is no 'class in php to encode json as bootstrap-table need' because bootstrap-table just need what you see in the doco, and thousands upon thousands of tutorials out there about returning database details for every possible DB and scripting language combo you can think of.

**Comment by airtonjr** [comment]
@joefreire I am using this solution to get data with the PHP. 

I will try to explain:

1. Try to use in the table config the URL:

>  <table id="table"              
>            data-url="./HERE YOU SELECT FILE.php">     
>     </table>

2. In the PHP file with your select result just use: echo json_enconde($result_query);

And done.

Tente usar apenas json_enconde ($resultado_query) e vc conseguirá aplicar em todas as colunas os resultados obtidos. Estou usando isto sem problemas. 

Abraço.

**Comment by dabros** [comment]
@airtonjr - read my post, use google, find out how to query your DB or dataset, thousands of tutorials out there

**Comment by airtonjr** [comment]
@dabros Why should I need to use google if I am already have my code working? You should read my post.

**Comment by dabros** [comment]
@airtonjr - sorry, i have about 6+ issues i was posting to, mistook you for original poster.

Deleted that post, please do same to your last to reduce clutter

thanks

**Comment by joefreire** [comment]
@airtonjr work here, thks
