### ISSUE TITLE
Issue under Browserify

### ISSUE THREAD

**Issue by ray306** [wenzhixin/bootstrap-table#2167]
Hi, I tried bootstrap-table via Browserify.
The _main.js_ contains:

```
var bootstrapTable = require('../node_modules/bootstrap-table');
$('table').bootstrapTable();
```

Then I convert the _main.js_ to a _bundle.js_ by Browserify.
But when I run the webapp in browser, it occurs:

```
bundle.js:12462 Uncaught TypeError: $(...).bootstrapTable is not a function
```

**Comment by djhvscf** [comment]
I'm not familiar with Browserify... Let see if @dabros or @wenzhixin can help here

**Comment by dabros** [comment]
@ray306 @djhvscf - no experience with browserify, but its obviously an ordering issue.

Perhaps running inside `$(document).onReady(function(){}` or anonymous jquery function will work

Its nothing specific to bootstrap table, just js method being called before script is loaded

Look around at other browserify issues and try calling on document ready or similar, and if still no luck post to SO - but there is definately related issues since its just a timing issue if thats the only error.

**Comment by pabloandi** [comment]
I have the same error with Browserify. Besides, tried to use the following:

`window.$ = window.jQuery = require('jquery');`
`var table = require('bootstrap-table');`
`$(document).ready(function(){`
`    var config = {`
`        columns: [{`
`            field: 'id',`
`            title: 'Item ID'`
`        }],`
`        data: [{`
`            id: 1,`
`           }, {`
`            id: 2       `
`        }]`
`    };`
 `   table($('#table'),config);`
`});`

Throws the following error:
`grunt.file is undefined`

**Comment by pabloandi** [comment]
@ray306 @dabros Solved! just put in the require statement the path of the production bootstrap-table js library.
`var bootstrapTable = require('bootstrap-table/dist/bootstrap-table.js')`
