### ISSUE TITLE
Cannot read property 'locales' of undefined

### ISSUE THREAD

**Issue by darionyaphet** [wenzhixin/bootstrap-table#2219]
CDN 加载文件之后报错 ： `Uncaught TypeError: Cannot read property 'locales' of undefined`

**Comment by wenzhixin** [comment]
你怎么用？

**Comment by darionyaphet** [comment]
<head> 标签里面加载了官网给的例子 然后打开 chrome 开发工具 看见这个错误了

**Comment by wenzhixin** [comment]
提供下 jsfiddle 吧，如 #1765 ，不然不知道什么问题

**Comment by dengyongfu** [comment]
我也遇到同样的问题，刚开始用bootstarp，最后我发现是引用js文件放置的顺序问题
eg:
<script type="text/javascript" src="<%=basePath %>resources/js/bootstrap/table/bootstrap-table.min.js"></script>
	<script type="text/javascript" src="<%=basePath %>resources/js/bootstrap/table/bootstrap-table-zh-CN.js"></script>

**Comment by blurstream** [comment]
I am sorry but I can't understand if this issue is resolved, I checked "Getting started" homepage to get rid of this issue, following inclusions specified there, but I'm still getting
`Uncaught TypeError: Cannot read property 'locales' of undefined
    at bootstrap-table-it-IT.min.js:7
    at bootstrap-table-it-IT.min.js:7`
when I use the following code:

<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.1/bootstrap-table.min.css">

<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.1/bootstrap-table.min.js"></script>

<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.1/locale/bootstrap-table-it-IT.min.js"></script>
... I just changed the locale of the project keeping inclusions unaltered
