### ISSUE TITLE
need a new event

### ISSUE THREAD

**Issue by ientrytech** [wenzhixin/bootstrap-table#2236]
How would I go about adding an event that was called after a row is drawn? I need to be able to run a function after each row has been completed, including the formatter function.

**Comment by djhvscf** [comment]
See these lines of code: 
https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L1752 (We push the `tr` into an array which contains rows)
https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L1763 (We include the html code into the `body` tag of our table)

So because of that we cannot fire an event after a row is drawn because the rows are rendered just once
