### ISSUE TITLE
updateByUniqueId

### ISSUE THREAD

**Issue by denjs** [wenzhixin/bootstrap-table#2267]
Hi Guys,
I'm trying to make my table to be a bit faster than it is...
279 rows, 9 columns, 5 columns have formatters two of them are quite complicated.
Each time when I use updateByUniqueId method is seems like it triggers to redraw the whole table.
So I've got a noticeable delay before row gets updated... putting console.log into formatters tells me that each formatter runs for each row. Is there any way to update just one row when use updateByUniqueId while having custom formatter? Thanks.

**Comment by dabros** [comment]
possibly related: #1498

**Comment by denjs** [comment]
I've tried that (same changes like if (params.reinit === false) { return; }) but it doesn't work for rowbyid update :(

**Comment by denjs** [comment]
Hi,
Any chance this can be fixed? :)

**Comment by dabros** [comment]
@djhvscf @wenzhixin - any thoughts?

**Comment by wenzhixin** [comment]
Have you try the develop branch version?

**Comment by denjs** [comment]
Me? Lol, I'm not that smart :D
What I'm after is to update a row in the table using updateByUniqueId method. It does what I need perfectly, the only downside is that it does trigger my custom formatter for each row which makes my table EXTREMELY slow... to redraw only 268 records it takes almost 15 seconds :( I have to custom formatters so the I run updateByUniqueId it does 268x2 calls to formatters.
If you guys consider that for future improvement that would be Awesome!
Thanks.

**Comment by dabros** [comment]
@denjs - thats kinda a common issue of any big data, which is why pagination and similar is recommended in those cases.

I do get the point of feature request, and regardless of you finding a workaround I know this is being looked at, but for your purposes perhaps look at either using css and/or other approaches to apply similar styling

15 seconds seems extreme, so prob some room for optimisations there, some ideas:

1. Remove uneeded formatters, using simple css to replace if possible
2. Improve performance of formatters, for example using more simple conditional checks and returning certain css class or html snippet that is then detected by css OR other (such as `onPostBody` code) to apply further effects.

The biggest step of all is trying to use pagination, especially if that table is likely to grow.

As a point of rule i ALWAYS use pagination unless a dire need not to, as data can almost always be expected to grow over time, so performance testing is only relevant if scoped and consistent with future predictions.

**Comment by denjs** [comment]
Thanks for advice, much appreciated. I'll try to go with pagination... maybe it just looks bad, but in fact maybe alright. As for the formatters... I add some classes and html wrappers... nothing major, but maybe they have too many "if" conditions...

**Comment by dabros** [comment]
@denjs - remember to use `this` keyword in formatters and cellStyle, rowStyle ect and see other param.

Those 'if' conditions can be worked in many ways, simpler is better

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it, thanks!

**Comment by dimidd** [comment]
I have the same problem.
http://stackoverflow.com/questions/42885273/appending-a-row-to-a-bootstrap-table-alters-previous-rows

**Comment by djhvscf** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it, thanks!
