### ISSUE TITLE
Can bootstrap-table provide tree-table mode , thanks !

### ISSUE THREAD

**Issue by mataoxf** [wenzhixin/bootstrap-table#2285]
> ### Can bootstrap-table provide tree-table mode , thanks !

I need a table to show with tree-table mode , I know bootstrap-table has the sub-table mode,but I wan't the mode like the bottom picture . 

- all the row has the same column count with in one table.

- I can select a column to expand.

- the expand column can be indentation by hierarchy.

![treetable-example](https://cloud.githubusercontent.com/assets/880980/15384484/83820edc-1dcd-11e6-938d-2abf288f9091.jpg)

**Comment by djhvscf** [comment]
You can use these extensions: 

- https://github.com/wenzhixin/bootstrap-table/tree/develop/src/extensions/group-by

- https://github.com/wenzhixin/bootstrap-table/tree/develop/src/extensions/group-by-v2

**Comment by dabros** [comment]
@mataoxf - also keep in mind that `detail-view` can be whatever you want, included a fully featured subtable

The following example uses dummy data, but very easy to see core code and you can add classes and such to subtables to achieve any desired visual tweaks, included having that exact layout you show in image

http://issues.wenzhixin.net.cn/bootstrap-table/index.html#options/sub-table.html

If you search for "sub table" and similar I know there are other issues here or on SO that can help with more example code if needed, but its really just you putting your sub-table init code inside detail view function/option

**Comment by dabros** [comment]
@djhvscf - im not too familiar with those, any examples?

Column grouping is shown breifly (http://issues.wenzhixin.net.cn/bootstrap-table/index.html#options/group-columns.html) but ive never seen row grouping like that, or anything more than that one example at all

**Comment by wenzhixin** [comment]
@mataoxf have you solve your problem?

**Comment by wenzhixin** [comment]
Close this issue.

**Comment by thinkerou** [comment]
I have read the documentation: https://bootstrap-table.com/docs/vuejs/browser/
I know how use it using `Browser` mode, and it only is `table` not `tree-table`.
But, I want to use `treegrid` using `Browser` mode, how should I do?

**Comment by wenzhixin** [comment]
@thinkerou Vue + treegrid example: https://live.bootstrap-table.com/code/wenzhixin/402

**Comment by thinkerou** [comment]
@wenzhixin thanks!

**Comment by kothashyam** [comment]
As per example i need to use JSON for tree grid. but in my case i have to loop through ArrayList to make each row. How can i get tree structure in my case?? Please hell

**Comment by wenzhixin** [comment]
@kothashyam only supports array data in the current version.

**Comment by kothashyam** [comment]
> @kothashyam only supports array data in the current version.

@wenzhixin - Thanks for your reply. You mean Java Array or JavaScript Array? can you give me an example code?

**Comment by wenzhixin** [comment]
https://github.com/wenzhixin/bootstrap-table-examples/blob/develop/json/treegrid.json
