### ISSUE TITLE
Request for Sample Code for Ajax +Json + ServerSide pagination.

### ISSUE THREAD

**Issue by kghulami** [wenzhixin/bootstrap-table#2289]
Can anyone please put a Sample (Simple) tutorial on how can I use Ajax+Json+ServerSidePagination in my project.

I have checked different issues, and their answers, documentation, and also the codes behind examples in this site, BUT could not understand how i can use this in my own project  (.NET MVC project). 

If you can put these here:

1. Code which i need to write in controller
2. Ajax in View 

I searched a lot to find the answer in issues already raised but i am totally lost now. :|

Thanks for your help.

**Comment by wenzhixin** [comment]
1. google `NET+restful`
2. http://issues.wenzhixin.net.cn/bootstrap-table/#options/server-side-pagination.html

**Comment by kghulami** [comment]
Thanks wenzhixin;
I have already checked point 2, but what can I use from point 1?

I know i should create a new "Action" in my controller file and pass the data queried from my database throught JSON to my view file where i have the Ajax code in order to receive these data and put them into my table, but need a sample code in order to understand how should I do this.

**Comment by wenzhixin** [comment]
I am familiar with .NET, so I don't know how to help you, I think you can search the answer from SO.

**Comment by dabros** [comment]
@kghulami - no one can give you your entire project, follow some tutorial on .NET and restful, then when you got the data flow working with manual ajax, tie it into bootstrap table.

Plently of great examples out there for all steps required, here is just the bootstrap side, you gota know how to work with .NET yourself first

**Comment by kghulami** [comment]
@dabros ;
Tnx for the response.
i have came up with a piece of code but faced an small issue.
Now i can pass the json data into my view but can not show it in TABLE.
As you said i have put my code in jsfiddle in below address.  Can you plz have a look into it? how should i solve this?


https://jsfiddle.net/kazemghulami/qhLbrwh1/

**Comment by dabros** [comment]
@kghulami 

Your fiddle is broken

Have a look at https://developers.google.com/web/tools/chrome-devtools/

What you need to do is called debugging, plenty of guides and tools out there.

In this case just enable F12 and console, then run fiddle and see errors returned.

The 2 I saw are using html inside the javascript panel, easily detected when you watch console errors with F12, as well as your ajax request is actually broken. The error msg can be misleading in those cases, but why you using relative url on jsfiddle?

Unless your url is litterally `https://jsfiddle.net/kazemghulami/qhLbrwh1/Book/LoadData` then it will NOT WORK.

You have also not included jquery or bootstrap table resources..?

Use that link I gave you, gives a guide and example fiddles, see how they are created. Always start simple, so use that server side data, doesnt matter bout your .NET so long as the format matches the network requests you see for that WORKING example (hit F12 and watch Network panel on initial data request and user actions).

For JSFiddle include jquery using the button in top right of javascript panel, or via external resource, doesnt matter so long as included.

Start simple

**Comment by kghulami** [comment]
@dabros;
I did as you adviced, 
I checked my the Json that my Controller returns, it is in below format:

{"total":60,
"data":[{"Id":1,"BookTitle":"Book1","Author":"Author1","Price":"100","Publisher":"Publisher1","Type":"Type1","Language":"Language1"},{"Id":2,"BookTitle":"Book2","Author":"Author2","Price":"101","Publisher":"Publisher2","Type":"Type2","Language":"Language2"},{"Id":3,"BookTitle":"Book3","Author":"Author3","Price":"102","Publisher":"Publisher3","Type":"Type3","Language":"Language3"},{"Id":4,"BookTitle":"Book4","Author":"Author4","Price":"103","Publisher":"Publisher4","Type":"Type4","Language":"Language4"}]
}

There maybe something wrong with my JSON? 

**HTML CODE:**
`@model IEnumerable<BFreshTBL.Models.Book>

@{
    ViewBag.Title = "Index";
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>

<script >
    $(document).ready(function () {
       

        $.ajax({
            url: '/Book/LoadData',
            type: 'POST',
            dataType: 'json',
            success: function (data) {
                debugger;
                $('#table').bootstrapTable({
                    data: data
                    
                });
                $('#table').bootstrapTable('load', data);
                
           }
        });
    });
</script>

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<div class="wrapper">
    <div class="fresh-table toolbar-color-azure ">
        <div class="toolbar">
            <button id="alertBtn" class="btn btn-default">Alert</button>
        </div>
        
        <table id="table" class="bootstrapTable"  data-side-pagination="server" data-url="/Book/LoadData" > 
            <thead>
                <tr>
                    <th data-field="Id">ID</th>
                    <th data-field="BookTitle">Title</th>
                    <th data-field="Author">Author</th>
                    <th data-field="Price">Price</th>
                    <th data-field="Publisher">Publisher</th>
                    <th data-field="Type">Type</th>
                    <th data-field="Language">Language</th>
                </tr>
            </thead>
        </table>
    </div>
</div>


`

**ACTION, .NET CODE:**
`	[HttpPost]

        public ActionResult LoadData(int? Id = 2)
        {
            var v = (from b in db.Books where b.Id == Id select b).ToList();
            int total = v.Count();
            return Json(new { total = total, data = v } ,JsonRequestBehavior.AllowGet);
        }`

**Comment by dabros** [comment]
@kghulami - 

Sharing flat code is no real use to anyone, all I can say is the following:

1. read my post, use F12 and tell me if your code produces errors in console, I have no idea what `debugger;` line does

2. STOP COPY PASTING EVERYTHING, read first

`data-side-pagination="server"`

If your using server side pagination, you need to tie that in properly. What your actually coding is that via an external (to bootstrapTable) ajax request you get a datapacket, then your passing the WHOLE thing DIRECT into the table...

Thats not server side, you cant just copy paste from around the place without reading the getting started and what each option does, see the doco

http://bootstrap-table.wenzhixin.net.cn/getting-started/
http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options (find side-pagination)


3. Stop copy pasting everything... 

Actually read your code line by line and if you are AT ALL unsure about what a line does, find out, its not hard at all

```
$('#table').bootstrapTable({
   data: data                    
});
$('#table').bootstrapTable('load', data);    
```

Your loading it twice, the first is the constructor where you (optionally) pass in data or any other options as a object array with named keys (such as `data`, `columns`, ect). As you can see in "getting started", you can use data attributes (`data-x`) OR pass in like that, or a combo of both, just understand what each are and what they mean

The `$('#table').bootstrapTable('load', data);` line is useless, you already passed data in, and there is not a single official example alive that has both those lines like that, so ALWAYS look at WORKING examples and take inspiration, dont mix and match copy and paste without understanding lines


3. Some focus points

The 'with server side' example in the `side-pagination` doco (see above) should show clearly how, if you want to do pagination before is data is sent (hence quicker response from server and less data back and forth) then use the param. 

These param are sent to the server by default, F12 and 'network panel' can help you see that, then just use them to add `limit`, `order` ect on your db query (plently of examples and issues for in general and to bootstrapTable, nothing fancy or special to bootstrapTable at all)

If you dont mind pagination being performed on client side (so all data sent, javascript does pagination, alright with smaller data sources, less ideal if you expect data source to grow over time), then change to `client` for the option, or leave blank as it will then default to it (see doco, always states default values)

You also dont really seem to need that seperate ajax at all, bootstrapTable doesnt that for you if you supply a `url`, which you have. Its great that you first setup a direct ajax and test data source, but as I said, you gotta look up what you dont know, because now your table is trying to load data 3 times and has server pagination but server side (data source and data return) is NOT setup for server-side 


---

Dont take this too harshly, im being honest and frank because this will save you ALOT of hassle and pain in the long run.

When you just start trying, it is hard, but the better you get at researching and having a process, the better you are at not just coding but also many other tasks in life. You will be surprised just how confident you can get once you get good at approaching new issues and applying a smart mindset towards researching.

Absolutely every programmer I know spends time every single day looking up keywords, code and doco. Every Single Day.

What changes is that you get better at getting to the point, getting what you need quickly and seeing the common patterns, meaning that most of the time you just confirming an idea and not being afraid to take just a few min to expand your knowledge just a little more 

Take your time to do things properly, dont worry about perfection, but keep on point with wanting to learn - itll make a massive difference :+1: :)

**Comment by kghulami** [comment]
@dabros;
Thnx a lot for responding my questions.
It did help me a lot. I did as you mentioned and read all links.
I Improved a lot with it now. With client side paginations all works good. but when i change the pagination to server, data loads into my table but the pagination toolbar does not appear.
I used firebug in my firefox to check the posted parameters and received JSON from my server, all seem to be normal, but could not find a way to get it working.

I put my server side code here but for Javascript and HTML will make a JSfiddle.

**Controller's Code:**  (pageSize,pageNumber and sortOrder are passed with no problem.)
`public ActionResult LoadData( int pageSize, int pageNumber, string sortOrder)
        {
           int pgSize = pageSize;
           int skip = (pageNumber ) * pageSize;
           int totalRecords = db.Books.Count();
            var data = db.Books.ToList();
            if (sortOrder == "asc")
            {
                data = data.OrderBy(x => x.Id).Skip(skip).Take(pageSize).ToList();
            }
            else {
                data = data.OrderByDescending(x => x.Id).Skip(skip).Take(pageSize).ToList();
            }
            return Json(new { total = totalRecords, data = data },JsonRequestBehavior.AllowGet);           
        }`

![capture](https://cloud.githubusercontent.com/assets/19181690/15628309/0923a798-2513-11e6-886d-d818ac95f3cb.PNG)

**Here is my Jsfiddle:**
https://jsfiddle.net/kazemghulami/bhynLn8y/1/
(I know my fiddle is not working correctly but in order to see the output i put screenshot of my app bellow.)

**Comment by dabros** [comment]
@kghulami - your format doesnt match, check doco examples of this in description for option `sidePagination` and if needed use `responseHandler` to debug and/or tweak your data to proper format

Also keep eye for errors and ect in console

**Comment by kghulami** [comment]
@dabros ;
`responseHandler ` was my answer.
solved it.

**Comment by dabros** [comment]
@kghulami - if solved pls explain just a little and ideally share some working code, then close when done

Thanks

**Comment by snomula-idc** [comment]
@kghulami : I have client side one check this:  https://stackoverflow.com/questions/51350056/bootstrap-table-server-side-pagination-and-search-functionality
