### ISSUE TITLE
Input values don't persist after using search or sort

### ISSUE THREAD

**Issue by hcancelik** [wenzhixin/bootstrap-table#2325]
Hi,

Thanks for the great repo.

When you have an input in the table and change its value, isn't it suppose to persist the value after doing a sort or search? I created this fiddle https://jsfiddle.net/hcancelik/na9ovj2v/17/ and if you check any of the checkboxes and then search, the selection get's discarded. Same as with if you type something inside the last input and then make a search, the value inside the input box get lost. Is this a bug?

**Comment by dabros** [comment]
@wenzhixin @djhvscf

**Comment by wenzhixin** [comment]
@hcancelik Input values don't persist is because after transfer table from html to `data`, the data is the origin rows. When you search or sort, our plugin use the origin rows data.

But you can update the input cell manually: https://jsfiddle.net/wenyi/na9ovj2v/19/.

Although you can do like this, but it is not recommended, it is better to use `data` and `formatter` and then call `updateRow` method to update your row data.

```
<th data-field="input" data-formatter="inputFormatter" data-events="inputEvents">
```

```
bootstrapTable({
    data: data
});

inputEvents: {
    'change: input': function () {
        // call updateRow
    }
}
```

**Comment by hcancelik** [comment]
@wenzhixin thank you for the reply.

**Comment by wenzhixin** [comment]
let's close the issue.
