### ISSUE TITLE
data-toggle:table data not showing

### ISSUE THREAD

**Issue by zoaeu12** [wenzhixin/bootstrap-table#2437]
hi.
my table data get MSSQL used ajax and C#
 - no data-toggle="table"
![no toggle](https://cloud.githubusercontent.com/assets/14974087/16610616/52d34bee-4397-11e6-829e-212e77748942.png)

 - use data-toggle="table"
![use toggle](https://cloud.githubusercontent.com/assets/14974087/16610617/52d394aa-4397-11e6-8efb-c540bf333070.png)

create bootstrapTable like this
$('#table').bootstrapTable({ data: JsonData});

**Comment by dabros** [comment]
@zoaeu12 - as explained in documentation and in many other issues, use `data-toggle` **OR** `$(table).bootstrapTable(..)` to initialize your table.

http://bootstrap-table.wenzhixin.net.cn/getting-started/

`data-toggle` is just a shortcut, a very common shortcut for many jquery plugins, that just triggers the case as soon as possible. On a side note, this can cause timing or scoping issues for code, so I always use js init rather than `data-toggle`

**Comment by zoaeu12** [comment]
oh.. i understand perfectly!
thank you for reply.
