### ISSUE TITLE
Export Button is not shown even after using data-show-export="true"

### ISSUE THREAD

**Issue by geniusdevill** [wenzhixin/bootstrap-table#2451]
I am using exactly this method as shown in example but Export Button is not being shown. Can you please check whats wrong with it?

http://issues.wenzhixin.net.cn/bootstrap-table/#issues/188.html

Even I have tried an existing Fiddle but it don't shows any export button.

http://jsfiddle.net/j0be3khu/1/

Thanks!

**Comment by dabros** [comment]
@geniusdevill - always look at console and debug (F12)

Your link is broken, see how other urls work and mimic that, https://rawgit.com/wenzhixin/bootstrap-table/master/dist/extensions/export/bootstrap-table-export.js seems more like what you need, not "extensions/export/bootstrap-table-export.js" which then becomes http://jsfiddle.net/j0be3khu/1/extensions/export/bootstrap-table-export.js since you failed to put whole path in

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/export.html
You need to import the export resource: https://github.com/wenzhixin/bootstrap-table-examples/blob/master/extensions/export.html#L13

**Comment by wenzhixin** [comment]
http://jsfiddle.net/j0be3khu/15/
