### ISSUE TITLE
Filter control does not work on editable columns

### ISSUE THREAD

**Issue by bounlu** [wenzhixin/bootstrap-table#2470]
When both **filter control** and **editable** are used on the same column, filtering does not work.

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by bounlu** [comment]
Here is the fiddle but filter control and editable do not work on the fiddle although the same code does on my website:

https://jsfiddle.net/arkanion/fkaLzawe/

**Comment by dabros** [comment]
@bounlu 

Your fiddle is broken because you didnt check your links or check console for errors (F12). Please provide a working Fiddle and we can help you more, dummy data from js array is fine (just needs to replicate core issue). 

Examples and guide provided below:
- https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
- #1765

Doesnt even need to save actual values, though do look at your editable declaration as all examples ive seen use editable setup as seen in example and an ajax call inside `onEditableSave` to send to actual save script (many issues that would show that).

Editable plugin:
https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/editable
http://bootstrap-table.wenzhixin.net.cn/extensions/
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/editable.html

**Comment by bounlu** [comment]
I finally figured out the problem. If "data-filter-strict-search" is set to "true", filter control does not work on editable fields, if set to "false", it works.
