### ISSUE TITLE
BUG当refresh url返回rows为null时，table载入的数据为最后一次查询到的数据

### ISSUE THREAD

**Issue by sugerlemon** [wenzhixin/bootstrap-table#2546]
第一次载入json是：
‘["total":"10","sum":10,"rows":[xxxxxxxxx]]’
table 显示正常的10条数据，然后 点击button，refresh 后，返回的json是：
‘["total":"0","sum":0,"rows":null]’

但是此时，表格显示的数据依旧是上一次的json数据：
‘["total":"10","sum":10,"rows":[xxxxxxxxx]]’

请检查。

p.s 试过 destroy，貌似还是无法刷出rows为 null时的正确回馈

**Comment by sugerlemon** [comment]
上述应该是个BUG，经过多次尝试后，使用以下代码解决：
`$table.bootstrapTable('removeAll').bootstrapTable('refresh');`

**Comment by dabros** [comment]
@wenzhixin

**Comment by wesleywong** [comment]
same problem here. the search will use the old data even after destroy. I believe is render problem, because sometimes will happen and sometimes not. I notice when old data happen then fitHeader unable to find this.$header and will return 0 height for margin-top.

$table.bootstrapTable('removeAll').bootstrapTable('refresh'); cannot solve this issue.

**Comment by wenzhixin** [comment]
@sugerlemon @wesleywong, you can use `responseHandler` to solve your problem:
```
responseHandler: function (res) {
  res.rows = res.rows || [];
  return res;
}
```
