### ISSUE TITLE
Auto refreshing page

### ISSUE THREAD

**Issue by yaylitzis** [wenzhixin/bootstrap-table#2553]
I use bootstrap-table with JSON file. I develop my webapplication with TOMCAT and when I go to the page where I show the bootstrap table, the page is auto reloading continuously.

Is there any possibility that this is happening because of the bootstrap-table?

**Comment by dabros** [comment]
Please provide a Fiddle and we can help you more, dummy data from js array is fine (just needs to replicate core issue). For data-url use them from examples provided, if you need more custom server side then see http://stackoverflow.com/questions/7194408/how-can-i-use-the-jsfiddle-echo-feature-with-jquery

Examples and guide provided below:
- https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
- #1765 

If you can replicate the issue then we can help, if it is part of boostrapTable then its likely you have it being initiated in some loop or similiar, also make sure you use `data-toggle` OR js init `$('#table').boostrapTable()`, never both, see the numerous examples for how to set your table up.

If you cant replicate the issue, then its something else and we really cant help sorry. Though attempting to replicate might actually bring your attention to where the actual problem lies (as you establish the sections of code that work as expected), so definitely worth trying either way.
