### ISSUE TITLE
reorder-rows what methods?

### ISSUE THREAD

**Issue by pehser** [wenzhixin/bootstrap-table#2561]
Tell me what method to check that the row has changed when using reorder-rows

**Comment by dabros** [comment]
@pehser 

How about I try to rephrase your question so we have at least some idea what you actually want, please work with me and help finish it then post with correct details


"Hi

I'm using the `reorder-rows` extension ([doco](https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/reorder-rows), [example](http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/reorder-rows.html))

I have a working codebase with reorder-rows and client-side pagination, was hoping you could help me find which method to use to ???

A. Check that the row has changed after i perform a call to reorder-rows??? (need more detail)
B. Apply a css style to the rows I move when I call reorder-rows?
C. Keep track of a list of all changed rows after I perform any calls to `reorder-rows` so that i can use it for??? (need more detail)

Thanks for your help"

@pehser - now please fill that out, and realise that it is both more polite but also something we can actually help you with, rather than being puzzled what it is you have or you want.

Always ensure your question described current state of your project (in regards to functionality you enquiring about and summarise any related information), and critically it HAS TO describe current output vs desired output
