### ISSUE TITLE
How can i send multiple pk to server while i use table editable

### ISSUE THREAD

**Issue by codefrosts** [wenzhixin/bootstrap-table#2564]
According topic
my table is a combine key pk. so I must send two pk to the server side.
I tried to use params function of x-editable but it didn't work for me.
It only used last value of table.

**Comment by dabros** [comment]
@ZenixFrost 

As clearly stated in the doco and in many issues (such as #2298) the editable plugin just helps expose x-editable functionality

This multiple pk issue is entirely an x-editable plugin issue, see links in the issue #2298 to find more info and links to official x-editable doco and examples. Get it working WITHOUT bootstrapTable and it will work WITH it, nothing to do with bootstrap table itself it all so check out those x-editable resources and support (of which there is a considerable amount, far more than this plugin)

**Comment by ZenixFrost** [comment]
I clicked your link above, but it isn't clearly for me.
Can you show me some sample.

https://jsfiddle.net/tmt829uz/2/

Accoirding link
I have course_id , subject_id and subject_name field.
when i click some field to edit then I must send course_id and subject_id to server side.
because I'll know row that i have to edit if i only send subject_id. I won't know.
my table has two pk is subject_id and course_id.
I use idField I have only one pk is subject_id which I want one more pk send to the server side.

sry for my bad english.  (English isn't my native language. :(  )
I hope you'll get it.

**Comment by dabros** [comment]
@ZenixFrost 

As stated in that linked topic and the many links i collated there, customisations and any editable config is actually the domain of the x-editable plugin itself. Bootstrap editable plugin simply provides a way to pass those EXACT SAME SETTINGS you would use to solve this in any x-editable scenerio

https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/editable

http://vitalets.github.io/x-editable/docs.html#editable

Look for x-editable solutions (ignore bootstrap table for now) to solve your core issue. When you have some basic x-editable code working with multiple pk and such (or whatever other approach answers your core need, never get too fixed on any one approach) then you just pass that into bootstrap table

We cannot help you anymore on this, but there are a great many x-editable resources out there and support community around that very widely used plugin

**Comment by dabros** [comment]
@ZenixFrost 

Also, as noted in issues here and elsewhere, editable plugin itself does NOT save changes to your DB, it ONLY saves to table data

The actual save call to your datasource needs to be placed in `onEditableSave` callback, which has access to row data, and you can easily pass that entire row via ajax to your datasource.
