### ISSUE TITLE
同时设置pageNumber和searchText初始值会冲突

### ISSUE THREAD

**Issue by aron10** [wenzhixin/bootstrap-table#2580]
同时设置pageNumber和searchText初始值会有冲突，造成pageNumber值无效
$table.bootstrapTable({
            url: "XXXX",
            toolbar:'.toolbar',
            showColumns: true,
            striped: true,
            pagination: true,
            pageList: [20,30,50],
            pageSize:20,
            pageNumber:2,
            sortOrder:'desc',
            search:true,
            searchText:"ja",
            sidePagination:'server'
        });

**Comment by dabros** [comment]
@wenzhixin

**Comment by jonatanklosko** [comment]
I've just stumbled upon the same issue probably. When I use server pagination and I set both `searchText` and `pageNumber`, the 1st page is always rendered (`pageNumber` is reset to `1`).
I can provide the chain of things leading to this:
- inside the `init` function `initSearchText` is called ([here](https://github.com/wenzhixin/bootstrap-table/blob/60a8c3bcd50ab4821d805c5478024082e3147e0a/src/bootstrap-table.js#L572))
- inside the `initSearchText` function `onSearch` is called ([here](https://github.com/wenzhixin/bootstrap-table/blob/60a8c3bcd50ab4821d805c5478024082e3147e0a/src/bootstrap-table.js#L2024))
- inside the `onSearch` function there's an `if` that could `return` but it evaluates to false ([here](https://github.com/wenzhixin/bootstrap-table/blob/60a8c3bcd50ab4821d805c5478024082e3147e0a/src/bootstrap-table.js#L1217))
- below this `if` we finally set the `pageNumber` to `1` ([here](https://github.com/wenzhixin/bootstrap-table/blob/60a8c3bcd50ab4821d805c5478024082e3147e0a/src/bootstrap-table.js#L1223))

The problem seems to be in the fact that despite of the presence of `this.options.searchText`, the `this.searchText` is `undefined`, and thus the if fails.
I cannot say what solution fits the whole code, but I can say that adding this
```js
this.searchText = this.options.searchText;
```
under [this line](https://github.com/wenzhixin/bootstrap-table/blob/60a8c3bcd50ab4821d805c5478024082e3147e0a/src/bootstrap-table.js#L2021) works (the if evaluates to `true` at the first time).

**Comment by jfly** [comment]
Ping. Any update here? This is causing us some trouble. Is there anything wrong with @jonatanklosko's suggested [workaround](https://github.com/wenzhixin/bootstrap-table/issues/2580#issuecomment-244552699)?

**Comment by wenzhixin** [comment]
Fixed in the latest version.
