### ISSUE TITLE
How to save columns after reorder

### ISSUE THREAD

**Issue by skumarfaruk** [wenzhixin/bootstrap-table#2605]
Hi,
Please tell me How to save columns after reorder is it possible?

**Comment by Falseee** [comment]
Listen on the [onReorderColumn](https://bootstrap-table.com/docs/extensions/reorder-columns/#onreordercolumnreorder-columnbstable) Event, send the order to your server, save it in the database and render the table next time in the new order.

I close this issue because its older than 2 years, if you still need help pls reopen the issue.

**Comment by shopexdream** [comment]
ok
