### ISSUE TITLE
Fetch table cell value using data-field value in Js

### ISSUE THREAD

**Issue by HegdeSach** [wenzhixin/bootstrap-table#2611]
I am trying to access table cell data to update some other cell value. So how can I fetch the cell value given I know only data-field value of the cell.

[jsfiddle](http://jsfiddle.net/Sachin_h/po1218x6/) - Click on Update error button in the fiddle to update error column using input_a and input_b column

**Comment by Falseee** [comment]
How or when do you want to fetch the cell value ?
Almost any event e.g. [onClickRow](https://bootstrap-table.com/docs/api/events/#onclickrow) returns the full row, so you can fetch the value of the column you want.
I will close the Issue because its almost 3 Years old, if you still need/want help pls reopen the issue.
