### ISSUE TITLE
Disappearing Row values on pagination and toggle view or toggle pagination

### ISSUE THREAD

**Issue by macsupport** [wenzhixin/bootstrap-table#2641]
This occurs in Safari, Chrome and Firefox. I have row values calculated by jQuery based on the value of an input. They show up initially but when I toggle the table view, toggle pagination or paginate to the next page or previous page, the values disappear and have to be re-entered. 

[jsfiddle](https://jsfiddle.net/macsupport/o6hh0111/) - a link to a simple reduced test case

Not the best option for my table!

**Comment by Falseee** [comment]
This error occurs because you only edit the dom elements.
If you toggle pagination or the table view the table will load the initinal loaded data and rerender it.
To persist changes you have to use an update function e.g. [updateRow](https://bootstrap-table.com/docs/api/methods/#updaterow).

I close this Issue because its older than 2 Years, if you need more help with that pls reopen the issue.
