### ISSUE TITLE
Bootstrap filter control doesn't working correctly for cells with hyperlinks?

### ISSUE THREAD

**Issue by 5331k** [wenzhixin/bootstrap-table#2655]
Please view the [example](http://jsfiddle.net/5h595r6g/71/). I have a cell created like this. 

```
<td> 
 <a href="https://www.google.com" target="_blank">
  3 (10.0 %)
 </a>
</td>

```

Now, in above cell actual data value is 3 (10.0 %) but when I type "google" in filter box it shows the cell with value 3 (10.0 %) which means it is taking whole hyperlink tag as cell value.

How i can achieve the correct filtering behavior for cells with hyperlinks ? May be I am following wrong approach for inserting hyperlink in table cell ? Any help or hint will be much appreciated.

**Comment by TCS-Taylor** [comment]
In addition, along these same lines, sorting doesn't work properly for columns with hyperlinks either, possibly for the same reason that is creating this issue.

**Comment by Falseee** [comment]
Should we add a column options `searchOnlyText` and `sortOnlyText` which only compare the text without html tags ?
Example: https://jsfiddle.net/8xrtudsa/

What do you think @wenzhixin @djhvscf ?

@TCS-Taylor 
Use [customSort](https://bootstrap-table.com/docs/api/table-options/#customsort) or [sorter](https://bootstrap-table.com/docs/api/column-options/#sorter) or [sortName](https://bootstrap-table.com/docs/api/column-options/#sortname).

**Comment by wenzhixin** [comment]
In the example provided, the problem is that the value of the cell is indeed:
```
<a href="https://www.google.com" target="_blank">
  3 (10.0 %)
</a>
```

I think we can use [`formatter`](https://bootstrap-table.com/docs/api/column-options/#formatter) and [`searchFormatter`](https://bootstrap-table.com/docs/api/column-options/#searchformatter) column options to solve the problem:
* Updated example: http://jsfiddle.net/wenyi/vm8tjbd1/3/.
* Solved example: http://jsfiddle.net/wenyi/vm8tjbd1/5/.

**Comment by UtechtDustin** [comment]
Please use the solution from wenzhixin, if you still need help please reopen the issue.

**Comment by dvhassel** [comment]
This solution seems to work for filter controls of the type input, but not for Select filter controls. See the forked JSFiddle: http://jsfiddle.net/Dietervh/1anq8wfj/1/

**Comment by UtechtDustin** [comment]
@wenzhixin @djhvscf 
https://github.com/wenzhixin/bootstrap-table/issues/2655#issuecomment-480015657 ?

**Comment by drhossa** [comment]
I have a similar issue like dvhassel! In my case I have to be able to filter on cell contents which may have HTML-Tags included. The rows have to be filterable by select.
`<strong>foo</strong> bar`
`<i>foo</i> bar`
`<a href="#">foo</a> bar`
By default the whole string will be taken by the select. A filtering leads to no results

Is it possible to filter on data-attribute values instead of the innerHTML of a cell?
