### ISSUE TITLE
Wrong pagination when deleting all elements in last page

### ISSUE THREAD

**Issue by paco-optimyzet** [wenzhixin/bootstrap-table#2711]
Steps to reproduce:
- Go to the last page of a paginated list.
- Remove all elements on page.
- When last element is removed you'll see "No records found". The table remains on the empty page but there are previous pages with records.

Expected:
- Detect the case (0 records recovered, on last page, more than one page), repaginate to the new last page and refresh.

**Comment by SafKris** [comment]
I have the same problem.

I have a bootstrap table with pagination and button "DELETE". When I delete the latest row on the latest page,  I have a message "No matching records found", no pagination and I can't see the rest of existing pages. What am I doing wrong?

In your example I see the same problem:
http://issues.wenzhixin.net.cn/bootstrap-table/index.html

**Comment by vykulakov** [comment]
I have the same problem. But in my case I use the cookie plugin and when I remove the last record on the last page, my table breaks down completely. It does not work even after I restart the web page because the number of non-existent page is saved in a cookie. To repair the table, I must clear the cookies!

In my projects I found the following workaround for the problem:

    $table.bootstrapTable({
    	url: url,
    	columns: [{
    		checkbox: true
    	}, {
    		field: 'id',
    		title: 'id',
    		sortable: true
    	}, {
    		field: 'name',
    		title: 'Name',
    		sortable: true
    	}],
    	search: true,
    	showRefresh: true,
    	pagination: true,
    	sidePagination: 'server',
    	pageSize: 10,
    	pageList: [5, 10, 20, 50],
    	stateSave: true,
    	stateSaveIdTable: 'table',
    	onPostBody: function() {
    		var options = $table.bootstrapTable('getOptions');
    		if(options.data.length === 0 && options.totalRows > 0 && options.totalPages > 0) {
    			that.$mainTable.bootstrapTable('selectPage', options.totalPages);
    		}
    	},
    });

When the server came to an empty data, I once again load the data for the last existing page. In the worst case we obtain duplicate requests.

**Comment by wenzhixin** [comment]
There is a workaround I am using to solve this problem:
```js
$table.on('load-success.bs.table', function (e, data) {
    if (data.total && !data.rows.length) {
        $table.bootstrapTable('prevPage').bootstrapTable('refresh');
    }
});
```
