### ISSUE TITLE
Submit form with all data if using pagination?

### ISSUE THREAD

**Issue by clin407** [wenzhixin/bootstrap-table#2730]
I have a form currently which works properly and I wanted to include this plugin to display a list of records (100+) with a column that has a checkbox. When submitting it without a plugin, itworks fine, I can see all the data being submitted properly but if I use pagination, and it shows 10 records at a time, I am only able to see the 10 records being displayed in the POST data. How do I have it submit all data? I'm not using ajax to submit my form.

**Comment by inversepolymath** [comment]
I am running into this same problem. I can supply an example if needed.

**Comment by aasmoth** [comment]
HI @inversepolymath,
Is it possible to get an example, please ? I'm running currently the same problem. 
Thanks

**Comment by jimgit** [comment]
Since a user can "SEARCH" or "SORT" - it's best to use ajax updates via check events so that the server is updated,  then regardless of the sort order or filter or page number,  the data is consistent between the users selection and the json results of the server side data.

For example,  if i check a checkbox then type something in search box,  where is the checked box persisted?  Ajax takes care of this by sending the change(s) to the server.   Now if you have a limited amount of data and use client side pagination,  you can use your technique.

**Comment by Falseee** [comment]
Use `getData` to get all rows then use [jquery filter](http://api.jquery.com/filter/) to filter only the checked rows.
Example: http://jsfiddle.net/54h8r2yq/
