### ISSUE TITLE
Issue with groupby when multi grids on same page

### ISSUE THREAD

**Issue by povolev15** [wenzhixin/bootstrap-table#2750]
Hi Guys,

I have an issue that I have 3 bootstrap table on same page and I use groupby extension.
2 grids are empty(0 rows) without data and one grid is loaded with data .
When I choose to remove from one column on the loaded one dropdown the grouping dissapear

Can someone help me please its super urgent
Attached JSfiddle: [http://jsfiddle.net/heqyLmrx/](http://jsfiddle.net/heqyLmrx/)
![image](https://cloud.githubusercontent.com/assets/16233475/19968289/53b7b6aa-a1aa-11e6-8258-9a6b2ada9a9c.png)

after I choose
![image](https://cloud.githubusercontent.com/assets/16233475/19968308/68a2bc36-a1aa-11e6-8e3f-59fd655b1879.png)

![image](https://cloud.githubusercontent.com/assets/16233475/19968317/702f1602-a1aa-11e6-9063-e71431662aaf.png)

The grouping dissapear

Best Regards,
Lev Povolotsky

**Comment by jlpilkin** [comment]
In the group-by plugin, the variable 'tableGroups' is set to be a global variable, when in fact it should be part of the bootstrap table object itself.

If you move 'tableGroups' inside the object (in my case, I moved it into the 'options' object of the Bootstrap table, though this can be moved anywhere), the issue is fixed.

**Comment by Falseee** [comment]
The groupby extension will be removed (#4281).
