### ISSUE TITLE
An issue was encounterred when calling "updateRow" method after search text

### ISSUE THREAD

**Issue by yftkwyp** [wenzhixin/bootstrap-table#2810]
Dear developer,
There is the example code following below:

&lt;table id="table"&gt;&lt;/table&gt;

`$('#table').bootstrapTable({
        search: true,
        columns: [{
            field: 'id',
            title: 'Item ID'
        }, {
            field: 'name',
            title: 'Item Name'
        }, {
            field: 'price',
            title: 'Item Price'
        },{
            field: 'operate',
            title: 'Action',
            events: {
                'click .edit': function (e, value, row, index) {
                    row["name"] = "updated item " + index;
                    $("#table").bootstrapTable("updateRow", { index: index, row: row });
                }
            },
            formatter: function () {
                return [
                    '<a class="edit" href="javascript:void(0);"> Edit</a> '
                ].join('');
            }
        }],
        data: [{
            id: 1,
            name: 'Item 1',
            price: '$1'
        }, {
            id: 2,
            name: 'Item 2',
            price: '$2'
        }]
    });`
-------------------------------------------------------<br />
After I type "2" in search box and then click "Edit" link to update this row, I got two same rows and the data was updated.

Can you help to solve this problem?

**Comment by B-Alvarez** [comment]
This happens when you search and edit (select) two objects are concatenated (being selected). Ex: getselections = [{row: 1}, {row: 2}] and so both rows that are selected are updated.


Try changing in bootstrap-table.js or min.js the value of "maintainSelected:" true or false.

I report this problem:

https://github.com/wenzhixin/bootstrap-table/issues/2544
https://github.com/wenzhixin/bootstrap-table/issues/2485

**Comment by yftkwyp** [comment]
Thanks!

**Comment by Falseee** [comment]
https://bootstrap-table.com/docs/api/table-options/#maintainselected
