### ISSUE TITLE
Cookie feature (re-order, resize)

### ISSUE THREAD

**Issue by djhvscf** [wenzhixin/bootstrap-table#2889]
Add feature to Cookie extension in order to save the re-order and resize configuration

**Comment by gggfreak2003** [comment]
It would be perfect if the saving of the column reordering could be implemented!

**Comment by UtechtDustin** [comment]
Can be implemented now, because of #4680.

**Comment by djhvscf** [comment]
Thanks @UtechtDustin this is now in my queue

**Comment by pavlalexandr** [comment]
Hi @djhvscf , Have you tried to implement the feature? I already have some edits about columns resizing. But as because resizing comes from 3d control it will require some additional 'data' attributes for the table and every column. Also, as I understand, it will require modification for code for programmatically columns definition for that data-attributes, right.  Is there anything else what I am missing about it?
