### ISSUE TITLE
Buttons Approve Reject AJAX POST action with notes

### ISSUE THREAD

**Issue by weedkiller** [wenzhixin/bootstrap-table#2961]
Hi, I was going through the samples, but there was no sample with

Buttons in cols, like Approve /Rject and putting notes and sending to AJAX POST Action
Updating the status of the row on success

**Comment by Falseee** [comment]
I guess the issue is no more up to date, but here is the way to go:
   - Use the Formatter to add the Buttons ([Example](https://examples.bootstrap-table.com/#column-options/format.html))
   - Listen to the Buttons (see example above)
   - Sending your ajax
   - Use the [updateRow](https://examples.bootstrap-table.com/index.html#methods/updateRow.html) function to update your row

@wenzhixin I think this issue can be closed.

**Comment by weedkiller** [comment]
In the sample page, it would be nice to have tab to show code behind on server and view, controller, model
