### ISSUE TITLE
A bug from Table search function

### ISSUE THREAD

**Issue by chobitsnerv** [wenzhixin/bootstrap-table#3009]
Hi guys,
I apply this library for my web db management tools and it works very cool.
But recently i have found a small bug.
When the table item contain a '.‘ as a column name, the research function will run into an error.
I try to locate the reason of this bug and get the following info:

from  bootstrap-table.js:1264
.......
                    if (typeof key === 'string') {
                        value = item;
                        **var props = key.split('.');**
                        for (var prop_index = 0; prop_index < props.length; prop_index++) {
                            value = value[props[prop_index]];
                        }
.........
I wonder whether there is a way to solve this bug smoothly.
Looking forward to the interesting replies.

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by chobitsnerv** [comment]
Sorry for missing sample.
Here it is:
http://jsfiddle.net/6bz80h6y/

The search function can be used any more since the first column name contains a '.' symbol.

**Comment by martinburch** [comment]
I think the dot split is intended to allow nested properties to be addressed with dot notation in strings, specifically HTML5 data attributes.

Here's an example: http://jsfiddle.net/6bz80h6y/1/
```
data-field="na.me"
[{ "na" : { "me": "bootstrap-table"} }]
```
JavaScript writers wouldn't normally use dots in property names. It's totally ok, but it means that the property would have to be accessed using bracket notation `['na.me']`.

Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Property_Accessors

@chobitsnerv You can specify your table configuration using JavaScript instead of HTML if you need to use bracket notation

Example: http://jsfiddle.net/6bz80h6y/4/

    $('#table').bootstrapTable({
        data: data,
        columns: [
        {field: ['na.me'], title: 'Name'},
        {field: 'stargazers_count', title: 'Stars'},
        {field: 'forks_count', title: 'Forks'},
        {field: 'description', title: 'Description'},
        ]
    });

Does this work for you? And @wenzhixin is this OK?

**Comment by chobitsnerv** [comment]
Oh, I see. Thank you very much for sharing the information.
I have already confirmed this method and it's no problem at all.
@wenzhixin Could you share this as a sample for using dynamic data source?
After all , thanks a lot for all you guys!
Best wishes~

**Comment by wenzhixin** [comment]
#1765
