### ISSUE TITLE
data-filter-control="input" 无效

### ISSUE THREAD

**Issue by chenfd99** [wenzhixin/bootstrap-table#3021]
data-filter-control="input" 无效 显示不出来  只有data-filter-control=" select"  才能显示

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by gitkingchen** [comment]
this extension has many versions , change version i think it will show

**Comment by GiriB** [comment]
'input' type filter-control [doesn't seem to work](http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/filter-control.html).

**Comment by GiriB** [comment]
Ok, the reason is [bootstrap-table-examples](https://github.com/wenzhixin/bootstrap-table-examples) is not using  the latest code for `bootstrap-table-filter-control.js`. The `input` field is not rendered in case of a [missing placeholder attribute](https://github.com/wenzhixin/bootstrap-table/blob/215a8006dcf0601b9c42ffbbc5319aa6e7da10a8/src/extensions/filter-control/bootstrap-table-filter-control.js#L433-L435).  This had been taken care of [in the latest code](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/filter-control/bootstrap-table-filter-control.js#L260).
