### ISSUE TITLE
No way to set footer values when server-side pagination is used

### ISSUE THREAD

**Issue by mrbubblesort** [wenzhixin/bootstrap-table#3046]
I would like to set the values in the footer with an object in the ajax response when data-url & data-side-pagination="server" is set.  (Specifically, I'm loading data from an elasticsearch instance, and want to show my aggregations in the footer.)  Is there a way to do that?  For example, if this is the response:

`
{
    "total": 200,
    "rows": [ ['col1':50, 'col2':50] .... ],
    "aggs": [ 'col1' : 100, 'col2' : 200 ]
}
`

How can I set the "aggs" field in the footer?  Or is there a better way to do it?

If there isn't a way, I've made a small change that might work:
https://github.com/wenzhixin/bootstrap-table/compare/develop...mrbubblesort:develop

**Comment by mrbubblesort** [comment]
Made pull request
https://github.com/wenzhixin/bootstrap-table/pull/3048

**Comment by mnswiftone** [comment]
I found a solution to adding total values to the footer row of my server-sided pagination true table using existing 1.14 with no modifications needed.  The way it works is all data values returned are available in the load-success event - and if you use the footerFormatter - you can assign id'd containers (I used spans) to put the values from the dataset in the load-success event.  I have used this with my results over 16000 rows as a lot of pages, with the total row showing all column totals (returned from stored proc assigned in API returned dataset) - and not the current page only totals.

I believe this could be a solution for both #3048 and #3046

Steps:

1.  Add a footerformatter to the column(s) you wish to have a total value. i.e.
```
columns: [
 ...(other columns)...,
{
     title: 'Order<br />Amount', 
     field: 'Order_Amount', 
     sortable: true, 
     align: 'center', 
     footerFormatter: 'totalFormatter'
}]
```
2. Add footerFormatter's for each column - each having a unique html container id for your footer column (I added class text-nowrap to ensure the $ was in front of the amount, otherwise it showed as 'Total $' and amount on the next line) :
```
function totalFormatter(data, row) {
     return 'Total: <span id="totalspan" class="text-nowrap"></span>';
}
```

3. Add the value for that column as part of your API return data set (one for each column you want to show a total for) i.e. My example shows one  column, I did this for many columns, but all same concept just unique ids in footerFormatter. Here I added a totalamount and totalcount to show total $ of orders, and how many orders placed from stored proc and assigned those to return values in the API, returned in the dataset like:
```
{
     rows: ...   ,
     total: 600,
     totalamount: 5432.10,
     totalcount: 203
}
```
4. Add the column totals to the footer by adding a load-success.bs.table event 
(I put the `<br />` in to put the count (...) below the $ amount):
```
$("#table").on('load-success.bs.table', function (e, data) {
     $("#totalspan").html(
     '$ ' + data.totalamount.toString().replace(/\d(?=(\d{3})+\.)/g, '$&,') 
     + '<br />(' + data.totalcount + ')');
     ...
});
```

The result will be the footer row showing the total value for this column as:
   Total: 
$5432.10
  (203)

It's really pretty simple - all you have to do is have the values in your dataset as @mrbubblesort suggested.  I decided it was simpler to assigned column values individually to the result set, instead of as an array of columns (course, if you wanted to do that, I think you could just do something like aggs.col1 in the load-success event. (guessing, I'm not that great at array notation)).

The problem was that the dataset values are not directly available anywhere during the table creation - but they are after the table is 'successfully loaded' in the load-success event, directly as the data argument with all values accessible in it. (Thanks @wenzhixin - great design!)
