### ISSUE TITLE
Sort formatted columns

### ISSUE THREAD

**Issue by nysmoon** [wenzhixin/bootstrap-table#3065]
I apologize if this is mentioned somewhere, but I couldn't find the answer to my question.

Is it possible to sort a table by column that has been formatted? 

I tried to implement custom sort, but my "a" and "b" are undefined for some reasons. 

Here is the code: https://jsfiddle.net/nysmoon/hb1faqad/8/

**Comment by martinburch** [comment]
Thanks for providing a fiddle! The data is undefined because the `field`s named `date` and `time` don't exist. The data is showing up OK because the formatter functions know to use `eta`.

If you switch the field names for the columns titled `Date` and `Time` to `eta`, the default sorter will be able to handle this.

https://jsfiddle.net/hb1faqad/10/

Does that work for you?

**Comment by djhvscf** [comment]
@nysmoon the example provided by @martinburch solved your problem? If not please reopen this issue. Thanks

**Comment by nysmoon** [comment]
Sorry for the delay. It happened to be a busy weekend.

Yes, this is actually genius! I didn't even think that filtering just by `eta` will filter both columns correctly, instead of filtering by date and then by time separately :D

Thanks a lot. This is awesome!
