### ISSUE TITLE
x-editable: Performance issue with big tables

### ISSUE THREAD

**Issue by bilua-xiaolei** [wenzhixin/bootstrap-table#3142]
With big tables and all cells with x-editable, there is a really big performance issue specially when refreshing.

I recommend to create the x-editable input on cell click and not on table refresh

**Comment by wenzhixin** [comment]
I recommend you can use `server` sidePagination instead.
BTW, any PR is welcome.

**Comment by dskilken** [comment]
Unfortunately I just pulled bootstrap-table out of my site because of performance issues.   Using bootstrap table adds 12 seconds to the page load time.  My table is only 27 columns and 200 rows.  It does not involve server-side generated content.  It is static, well-formed HTML on the page at load time.  You cannot use column classes to hide columns, but instead have to use bootstrap-table's facility to hide and reveal columns.  If you don't use bootstrap-table's facility, then you run the risk of blowing errors.   In jQuery, if you use a selector that does not exist, the operation is ignored.  In bootstrap-table if you use an index that does not exist, the code blows an error.  Any changes to the table require a table refresh that takes over 4-5 seconds to complete.   So hiding and revealing table columns or rows is way too slow using boot-strap table.     I recommend the development team start profiling the code to figure out where the performance issues are.   I believe one of the major slow functions is the table initialization.    You should not have this kind of impact on page load time.  I recommend you test to see if an index exists before trying to do an operation to avoid javascript errors.  I found another plugin that would let me lock the header and first column, and then used other plugins to add print and search capabilities.  This took my 14 second load time with bootstrap-table down to 1.5 seconds.
