### ISSUE TITLE
Pre check "state" checkbox

### ISSUE THREAD

**Issue by Ghalleb** [wenzhixin/bootstrap-table#3208]
Hi everyone

Is there a way to check state checkbox via html property?
I saw it's possible via json by having a field named state, but I can't find the same way in html.

By taking a look at the code I can see
`sprintf(' checked="%s"', value === true || (value && value.checked) ? 'checked' : undefined)`
But I can just set a string "true" as a value.

I used those options on the table:
`<table data-toggle="table"
               data-filter-control="true"
               data-click-to-select="true"
               data-maintain-selected="true"
               data-select-item-name="subscribed"
               data-id-field="id-field" >`

Any help would be appreciated

**Comment by doomfrawen** [comment]
Hi, 

I faced a similar issue so I decided to add my own check-boxes instead of using the one included. 

I have some code like this inside my blade:
`@foreach($foo as $bar => $foobar)
<td><input type="checkbox" value=1 name="update_checkbox{{$row['id']}}"/></td>
@endforeach`

And then I do the validation in my controller.

Hope it helps.

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by wenzhixin** [comment]
Example: #3242
