### ISSUE TITLE
How do I validate editable table fields changed?

### ISSUE THREAD

**Issue by startovernow** [wenzhixin/bootstrap-table#3219]
Hello,

In my editable table, I would like to display something like "This field is required" if user clear the field and click on submit button, right now it just display "Empty", but giving error.

How should I do it? I tried to set column option as following but did not work:
data-editable-validate="validateFunction"
...
function validateFunction(value)
{
....
}

![image](https://user-images.githubusercontent.com/18681747/27303315-09d50f24-5500-11e7-9cb9-140190d57c00.png)

Thanks much!

**Comment by Prometodo** [comment]
Also having this issue. Tried messing around with x-editable source code and the table plugin with no results till now.

**Comment by surongaukeys** [comment]
Column options

editable:{
    validate:function(value){
          //  do something, this value is  value of input
    }
}


Function for client-side validation. If returns string - means validation not passed and string showed as error. Since 1.5.1 you can modify submitted value by returning object from validate: {newValue: '...'} or {newValue: '...', msg: '...'}

validate: function(value) {
    if($.trim(value) == '') {
        return 'This field is required';
    }
}

link:http://vitalets.github.io/x-editable/docs.html#editable

**Comment by startovernow** [comment]
@surongaukeys , thanks much for your input!

**Comment by programatix** [comment]
Does this mean that it can only be set when the table is initialized with javascript? Is there a way to mix the initialization with data attributes + javascript?
