### ISSUE TITLE
Very slow loading docs server

### ISSUE THREAD

**Issue by rizhenkov** [wenzhixin/bootstrap-table#3227]
Maybe need to move docs to github pages or other high-load free docs server?

**Comment by martinburch** [comment]
Since the docs are already in the repositories and either are HTML pages (in the case of bootstrap-table-examples) or can be built (bootstrap-table), I think this might just need to be enabled at the repo level.

https://github.com/wenzhixin/bootstrap-table/tree/master/docs
which is currently located at: http://bootstrap-table.wenzhixin.net.cn/
could appear at: http://wenzhixin.github.io/bootstrap-table/
See: https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch (Github Pages [supports Jekyll](https://help.github.com/articles/about-github-pages-and-jekyll/))

https://github.com/wenzhixin/bootstrap-table-examples
which is currently located at: http://issues.wenzhixin.net.cn/bootstrap-table/
could appear at: http://wenzhixin.github.io/bootstrap-table-examples/
See: https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#enabling-github-pages-to-publish-your-site-from-master-or-gh-pages

If this works out OK, the wenzhixin.net.cn pages could serve HTTP 301 Moved Permanently to redirect to the new locations.

**Comment by nirix** [comment]
I know many people would be very appreciative of having the docs moved to GitHub Pages.

The last time I tried to use the docs it took over 7 minutes to load the page, even then it didn't load correctly.

I've ended up just checking out the repository and running the docs locally, which is somewhat annoying to have to do.

**Comment by djhvscf** [comment]
@wenzhixin

**Comment by wenzhixin** [comment]
OK, I will add this to support.

**Comment by wenzhixin** [comment]
Moved to github pages and used cdn instead.
