### ISSUE TITLE
updateCell - params argument not compatible with previous versions

### ISSUE THREAD

**Issue by coffy** [wenzhixin/bootstrap-table#3336]
Argument 'params' in upadateCell() method changed between versions and it's not in release notes and it doesn't follow semantic versioning. 

In 1.8 parameters were 'rowIndex, fieldName, fieldVal'. 
In current 1.11 it's 'index, field, value'
Can we add backward compatible patch? 
Related to #2010 (updateCell - Documentation Incorrect)

**Comment by wenzhixin** [comment]
> In 1.8 parameters were 'rowIndex, fieldName, fieldVal'.

It is because this method is added ref #865 by @anhnt, and you can see other methods is use `index, field, value` parameters, we need to keep them the same so I update it to the correct parameters  name in latest version.
http://bootstrap-table.wenzhixin.net.cn/documentation/#methods

If you upgrade to the latest version you just only replace `rowIndex` to `index`, etc.

Thanks!
