### ISSUE TITLE
Check/Uncheck All in all pages with server-side paging

### ISSUE THREAD

**Issue by nngochue** [wenzhixin/bootstrap-table#3445]
Hi,

I need to check/uncheck all rows in all pages. I followed the #1167 issue but it's not success with server-side paging.

**Comment by wenzhixin** [comment]
[Server side pagination check/uncheck all rows](http://jsfiddle.net/wenyi/4r6g4cfu/844/)

**Comment by nngochue** [comment]
Thanks wenzhixin!

**Comment by zoharbarak** [comment]
@wenzhixin 
I tried using it in my Vue2 project and failed to do it because I can't use data-response-handler as it takes a function name and not a function pointer and inside the component <template> html part the name that is this.methodName() (for example) isn't the method name after building everything with webpack.

Also using refreshOptions doesn't work in this case.
Is it possible for you to add an option to set that method (data-response-handler) in a way I can give it a fucntion pointer?

**Comment by shobhitUI-PAN** [comment]
@wenzhixin can anyone help  "Check/Uncheck All in all pages with clientside pagination"
