### ISSUE TITLE
Cell Style row with lowest value

### ISSUE THREAD

**Issue by Rayvien** [wenzhixin/bootstrap-table#3447]
There doesn't seem to be a way to style a cell based on the value of cells in other rows. I would like to set the background color of the cell with the lowest value in a column but the data isn't available from the cellStyle function.

Is there a way to do this?

**Comment by jimgit** [comment]
Not sure if this will work since I can't get the data-cell-style function to fire or work but this might help.  Using on data load to find the min of the forks column, then using the cell style to format the cell.

[JSFiddle bootstrap-table find minimum and format cell](http://jsfiddle.net/jimkennelly/47g8jxbs/15/)

If you get it working - please reply with an improved fiddle since I would like to know what I am doing wrong.

**Comment by wenzhixin** [comment]
@Rayvien  @jimgit  http://jsfiddle.net/wenyi/47g8jxbs/21/
