### ISSUE TITLE
Documentation incomplete

### ISSUE THREAD

**Issue by SerethiX** [wenzhixin/bootstrap-table#3552]
Documentation incomplete

The Documentation is incomplete or it is a bug: stumbled upon this, when setting up synchronous loading of a Json string.
I wrote my Json data to the "data-data" HTML-Attribute and it loaded the data right aways, without further action after calling .bootstrapTable() on the Table.

```HTML
<table id="tableId"
       data-pagination="true"
       data-search="true"
       data-data="{{ tableData | json_encode | escape('html_attr') }}">
    <thead>...
```

```JS
$(document).ready(function() {
    $('#tableId').bootstrapTable();
});
```

In the documentation no data-data Field is documented, only the data field inside the options object. 

```MD
data | - | Array | [] | The data to be loaded.
-- | -- | -- | -- | --
```

It could be:
```MD
data | data-data | Array | [] | The data to be loaded.
-- | -- | -- | -- | --
```

Or is this a bug and not intentional and I should stop using it, before it breaks my code in any further release?

Greetings,
SerethiX

**Comment by jimgit** [comment]
I wouldn't use the data-data tag for complex data due to the html parsing of the browser may get confused trying to render the dom - see the [data property as shown in this jsfiddle](http://jsfiddle.net/jimkennelly/tyfhub54/)

![image](https://user-images.githubusercontent.com/1921941/35160180-07791f72-fd02-11e7-92c2-bd7454efcd57.png)

**Comment by SerethiX** [comment]
What do you mean by "May get confused"?

I thought as long everything is properly escaped for the context, there is not much that can go wrong?

The data is dynamic so we need some sort of variable. It should not get loaded asynchronously, since there is not a lot of changes on the data and a new request takes longer.

Inline JavaScript is not an option. So normally I would attach the data to load somewhere to an data-* attribute anyways and read it via jQuery from there manually. I'm just curious if this autoloading mechanism is intended use.

**Comment by jimgit** [comment]
Can you provide a jsfiddle ?

**Comment by SerethiX** [comment]
Sorry for the delay, was very busy: https://jsfiddle.net/1pbou991/

**Comment by jimgit** [comment]
Thank you for the JSFiddle.  I can now understand what your question is.

I think your problem is not the data-data tag.  [See this JSFiddle using your data-data tag](http://jsfiddle.net/jimkennelly/ccupyxdh/)  Suggest you add the remaining features you need step by step and see when the jsfiddle breaks.

**Comment by SerethiX** [comment]
I added all the features I needed already in my Project, it doesn't break.

My Question was: Is this feature going to be removed in any future release of BS Table or am I fine using this. Because it is not in the docs.

**Comment by Falseee** [comment]
The bootstrap-table fetch automaticly all data-* attributes and use them to set the value to the internal options object. Because of this automation your code should round "forever".

What do you think @wenzhixin @djhvscf, should we update the documentation or just close this issue and leave that "functionality" hidden?

**Comment by wenzhixin** [comment]
I didn't try to use it like this, so I didn't write `data-data` in the documentation.

Updated the documentation.
