### ISSUE TITLE
Multiple columns with 'data-events' does only for work the first column since 1.9.0

### ISSUE THREAD

**Issue by damsgaard** [wenzhixin/bootstrap-table#3564]
Multiple columns with 'data-events' does only work for the first column since 1.9.0

As shown here it is possible to receive events when a link is clicked in a cell with details on the cell.

[http://jsfiddle.net/wenyi/e3nk137y/39/](http://jsfiddle.net/wenyi/e3nk137y/39/)

Having more than column with 'data-events' configured does only work for the first column since 1.9.0:

```
<th data-field="columnA" data-formatter="columnAFormatter" data-events="columnAEvents">Action</th>
<th data-field="columnB" data-formatter="columnBFormatter" data-events="columnBEvents">Action</th>
```

With the above two columns only events for columnA is received.

Reversing the order of the columns making columnB the first then columnA stops working and columnB starts working.

Having the same name for the 'data-event' name does not work either.

**Comment by jimgit** [comment]
I have never used that setting - [but can reproduce the issue here](http://jsfiddle.net/jimkennelly/oh6zzsfa/)

I separated the formatters and action events to see  if that would help ,but didn't.

Noticed that the second "heart" doesn't get an event listener.

![image](https://user-images.githubusercontent.com/1921941/35386505-e3eeb014-0191-11e8-9251-c60c3c6b1a39.png)

**Comment by Falseee** [comment]
Looks the issue is resolved (thumb up reaction), if not pls reopen the issue.
