### ISSUE TITLE
Bootstrab 1.11.1 table doesn't display any sample data with bootstrap v 3.3.7

### ISSUE THREAD

**Issue by Siedlerchr** [wenzhixin/bootstrap-table#3570]
Sorry to bother you again, but I can't even get a minimal example working. It neither works in FF 56 nor Internet Explorer.
I have absolutely no clue and tried around all morning to get this working.  I have no idea why this fails.

https://jsfiddle.net/zo1cthax/1/

```

  <table data-toggle="table"   data-show-columns="true">
                <thead>
                <tr>
                    <th data-field="date">Date</th>
                    <th data-field="path">Path</th>
                    <th data-field="scenarioname">Name</th>
                </tr>
                </thead>

</table>

```

```js

  var mydata = [{
        "scenarioname": "xxx",
        "path": "xxxx-01-07-15-30-05",
        "date": "2018-01-07 15:30:05"
      }, {
        "scenarioname": "yyyyy",
        "Path": "yyyyyy-01-11-11-00-45",
        "date": "2018-01-11 11:00:45"
      }];

      window.onload = function() {
        $('#table').bootstrapTable({
          data: mydata
        });

      }

```

**Comment by lowegreg** [comment]
The problem is in your code.  Make sure you add an id to your table.

`<table data-toggle="table" id="table" data-show-columns="true">
    <thead>
        <tr>
            <th data-field="date">Date</th>
            <th data-field="path">Path</th>
            <th data-field="scenarioname">Name</th>
        </tr>
    </thead>
</table>`

**Comment by jimgit** [comment]
Thank you for providing a jsfiddle - [see this JSFIDDLE  - ](https://jsfiddle.net/jimkennelly/5aajhssn/)

Note the couple items.
Need a an id in the <table id="myTable"... to find the dom element from your code
I am not a jsfiddle expert but you may want to start with a working example from the documentation site since it looks like you may be pulling in multiple js.  Start with a new fiddle (or use an example from documentation) and then add in external resources.  I don't think you need the <html><head...
I like to use the ready event so I just pasted in my usual method.
Spelling error "Path" is not the same as "path" on your second line of data.

**Comment by Siedlerchr** [comment]
I now found the main difference, despite the missing id:
I had to remove the `data-toggle="table"` attribute from the table defintion. Now it works fine for my cases.
Thanks  a lot for your quick help and this awesome library 👍
