### ISSUE TITLE
Checked checkboxes disappear when sorting

### ISSUE THREAD

**Issue by sdespont** [wenzhixin/bootstrap-table#3600]
Version 1.11.1

I am facing a simple problem involving the options : "checkbox" and "sorting". 

When click for sorting, the **checked** checkboxes disappear.

In the following fiddler, click on the "target" column to sort it: 
http://jsfiddle.net/sdespont/16gywqts/14/

## **Example 1**
![image](https://user-images.githubusercontent.com/646632/36194006-57e17e1c-1168-11e8-9ad2-fd6335e82394.png)
![image](https://user-images.githubusercontent.com/646632/36194026-7354d8e2-1168-11e8-906b-dd7bb4a385fd.png)

## **Example 2**
![image](https://user-images.githubusercontent.com/646632/36194061-99177116-1168-11e8-9d38-44706be61581.png)

![image](https://user-images.githubusercontent.com/646632/36194075-a4b0d59e-1168-11e8-81c3-fd186688640e.png)

**Comment by jimgit** [comment]
If you need to "select" a row - [use the data-checkbox property as shown in this JSFIDDLE](http://jsfiddle.net/wenyi/e3nk137y/30/)

If the data is part of your json or table data - use the data-formatter to create the checkbox

Please include a JSFIDDLE so we can help solve your problem.

**Comment by sdespont** [comment]
@jimgit JSFiddle was included in the first message : http://jsfiddle.net/sdespont/16gywqts/14/

**Comment by jimgit** [comment]
Sorry - missed your fiddle in original post.  [How about this JSFIDDLE?](http://jsfiddle.net/jimkennelly/fwwmt4uz/)

**Comment by sdespont** [comment]
@jimgit I have just checked your example and it is working without separate data. But sometimes, create a JSON array of your data it is not what you want : some cells contains code under conditions (field displaying, styling part of text, ...), several input fields, and so on. In my point of view, it is more obvious to create table lines and cells with a loop on an array in the view instead of create a "not so easy" json array in a controller. 

So, according to my JSFiddle, are you agree that it is a bug?

**Comment by jimgit** [comment]
I would disagree - I find separating the data from the presentation works best for ME.  I have found this tool valuable for the types of applications I do.  My experience is that data should be kept clean and formatting should be handled separately.  This is just my opinion.  I am not a contributor but try to help answer questions when I can since I've benefited from this wonderful tool that the author and the extension authors have so nicely provided.  In the "old" days (pre-ajax) - many of us paid big bucks for server side tools like Infragistics (and other grid providers) with expensive yearly costs.   I will let the authors weigh in and determine what a bug is or is not but HTML resident data seems like a complication from my small view of the world.

**Comment by katiemccann** [comment]
I'm having this same issue (checkboxes disappear after sorting) and the JSFiddle that @jimgit posted has the same issue (http://jsfiddle.net/jimkennelly/fwwmt4uz/). 
<img width="1240" alt="screen shot 2018-03-04 at 10 09 04 am" src="https://user-images.githubusercontent.com/2029820/36948726-1e15a80e-1f94-11e8-9814-0270234865a5.png">

**Comment by katiemccann** [comment]
@sdespont I figured this out in my own project, thought I'd share here. Basically you can't have *any* data in the <td> for the checkbox column (even a space). In your JSFiddle, you have <td>1</td> etc in the checkbox column - remove that and the sorting works properly, see http://jsfiddle.net/katiemccann/zag8kzLs/1/

**Comment by Falseee** [comment]
Both Jsfiddle ([first](http://jsfiddle.net/jimkennelly/fwwmt4uz/), [second](http://jsfiddle.net/sdespont/16gywqts/14/)) works in the newest version.
If the error still exists, pls reopen this issue or open a new issue.
