### ISSUE TITLE
Let updateCell only update one HTML cell

### ISSUE THREAD

**Issue by benny-innofaith** [wenzhixin/bootstrap-table#3612]
Let `updateCell` only update one HTML cell

Reproducible steps:
- Update a cell by calling `updateCell`.

Expected behavior
- Only that cell is re-created.

Actual behavior
- Entire table is re-created or nothing is redrawn (if you pass `reinit`).

`reinit` was a fine. It would be better if `updateCell` updates that one specific cell.

[Table with input elements](https://jsfiddle.net/80wtkz0y/4/) - This shows how my table looks like. Edit any cell except for the top left one. Every second `updateCell` is called for the top left cell and any changes in the other cells are lost.

My use case is as follows: I have a few input elements in a cell. And asynchronous updates come from a server to update specific cells. Those updates re-draw the entire table, causing any input elements to be thrown away and re-created. Any focus, cursor and unsaved text is lost.

**Comment by pchaganti** [comment]
👍

**Comment by Falseee** [comment]
Currently there i no option to only update a cell without table rerender, because we always rerender the whole table.
Should be also the correct behavior, beause if you search for some word, you find 4 rows and edit a row you would still see this rows although the row dont match the search param.

If we would implement that feature it would a larger feature i guess, also we should give any method (insertInto, updateCell, updateCellById, ...) that option.

What do you think @wenzhixin @djhvscf ?

**Comment by wenzhixin** [comment]
Yes @UtechtDustin, implement this issue it would a larger feature.
Many methods will rerender the whole table.
In the future version, consider improving this feature.
