### ISSUE TITLE
Card-view click events issue

### ISSUE THREAD

**Issue by Miguel-Rey** [wenzhixin/bootstrap-table#3780]
I need to handle some 'click' events in my table. There is no problem in standar view, but when I toggle it to Card View it doesnt work. It seems that two things happens:

a) If there is any content which handles a click event, Card View prevents that from triggering. The only work with this is with the custom event "click-cell"
b) When you toggle to Card View, all the content gets wrapped in the first cell, so It doesn't matter where you click. The event triggered is always 'click-cell' of the first td.

Here is a fiddle. As you can see, there is no way to click on the "description".

http://jsfiddle.net/gakjn61m/

**Comment by jimgit** [comment]
Try using the row variable:

See this[ JSFIDDLE](http://jsfiddle.net/jimkennelly/57yu4zqx/)


![image](https://user-images.githubusercontent.com/1921941/50910415-5b39b500-13f3-11e9-913f-24a3d477b5c9.png)

**Comment by bob526** [comment]
Thank you for your quick reply.

Yes, for people who only want the data in row variable that will work.
But, in my real use case, I need the correct field variable because I will do different jobs according to the clicked field.

I updated the jsFiddle to reduce the ambiguity.
[updated jsFiddle](http://jsfiddle.net/jm02oaLk/13/)

**Comment by wenzhixin** [comment]
Merged.
