### ISSUE TITLE
If clickToSelect set true, ignoreClickToSelectOn not working anymore

### ISSUE THREAD

**Issue by camambeou** [wenzhixin/bootstrap-table#3822]
Here is Fiddle: 
http://jsfiddle.net/e3nk137y/28570/
if button (or a) is clicked, row is checked.
If I'm not wrong, row is not checked in this case.

**Comment by camambeou** [comment]
OMG, sorry for that, its my mistake!
Thanks for your time!

**Comment by Bensemer** [comment]
> I can't see that you're implementing ignoreClickToSelectOn on that code.

ignoreClickToSelectOn is activated by default for A and BUTTON tags. He does not have to implement it in his code. The problem is the new behaviour of $.inArray... For jquery 3.x the default function has to be

`ignoreClickToSelectOn: function (element) {
return $.inArray(element.tagName, ['A', 'BUTTON']) === -1;
}`

**Comment by camambeou** [comment]
If I turn default to this code 
`
ignoreClickToSelectOn: function (element) { return $.inArray(element.tagName, ['A', 'BUTTON']) === -1; }
`
the option clickToSelect not working anymore

**Comment by camambeou** [comment]
Does anyone have solution for this issue???

**Comment by camambeou** [comment]
Never mind.
I have solution for that. Something is misunderstood on the documentation.
