### ISSUE TITLE
How can i get data-field name in data-formatter function?

### ISSUE THREAD

**Issue by halimuygun** [wenzhixin/bootstrap-table#3825]
Hello, my code:
``` html
<table id="dataTable1" ...... >
    <thead>
        <th data-field="Price" data-align="center" data-formatter="formatCell" data-width="50">Price</th>
    </thead>
</table>
```
``` javascript
function formatCell(value, row, index) {
    return '<input type="number" id="' + XXXX + '">';
}
```

for XXXX:
I can use "row.Price" but i want cell's data-field name attribute. is this possible?

example: 

``` javascript
function formatCell(value, row, index) {
    return '<input type="number" id="' + column.FieldName + '">';
}
```
and returns:

``` html
<input type="number" id="Price">
```

**Comment by dabros** [comment]
@halimuygun - been a whloe since really worked much in this, but a cursory search showed a good dozen hits related to use of additional parameters

This one shows you can use `this` in that context to access the column object: #1986

This one mentioned same solution and is literally the same basic title and on first page of any issue list, so please do remember to search too as that helps everyone link topics and improve SEO: #3774

Same basic solution, used in footer formatter: #1856

Also, loosely related as this user wants access to all `data-*` attributes too, so uses `$(this).data()`, shared here as curious use of `this` keyword, and loosely related: #2247

**Comment by halimuygun** [comment]
Thank you @dabros :) 

I get the field name via:  ```this.field```

Thanks..
