### ISSUE TITLE
Remove doesn't work on dinamically added rows with append()

### ISSUE THREAD

**Issue by tperiz** [wenzhixin/bootstrap-table#3834]
Steps to reproduce:
1. Create a table with some hardcoded data on it (just for test purposes. The behavior is still present even when the table has no rows)
2. Append a row to the table using the `append` method.
3. Try to delete your newly-appended row using the `remove` method.

Expected behavior:
The row is removed.
Actual behavior:
Nothing happens.

Note that `remove` does work when trying to remove rows that were already present in the table.

Test case:
https://jsbin.com/hopudujuzu/edit?html,js,output

**Comment by jimgit** [comment]
Try using the removeByUniqueID

![image](https://user-images.githubusercontent.com/1921941/41106290-5f296da8-6a35-11e8-9301-4f15ad22bc61.png)


Make sure the id is the id you added - see this


function append() {
var id = 100;
$('table').bootstrapTable('append', {id: id, another: "Hello again from " + id});
}

function remove(id) {
  $('table').bootstrapTable('removeByUniqueId', id);


[See this link
](https://jsbin.com/cininog/1/edit?html,js,output)

**Comment by tperiz** [comment]
Ok that worked thanks, but why doesn't it work with remove?

**Comment by jimgit** [comment]
[Take a look at this example from the documentation:](http://issues.wenzhixin.net.cn/bootstrap-table/#methods/remove.html)

**Comment by andre-ss6** [comment]
What do you mean? The bin he provided seems pretty identical to the example from the documentation.

**Comment by jimgit** [comment]
[Look at this JSFiddle](http://jsfiddle.net/jimkennelly/a2p40csz/)

![image](https://user-images.githubusercontent.com/1921941/41151939-df15d356-6ad7-11e8-9738-ccc56e36750d.png)

**Comment by andre-ss6** [comment]
Ok, so it all boils down to this:

```javascript
$('table').bootstrapTable('append', {
    id: "" + id, // this was changed from id: id
    another: "Hello again from " + id
  });
```
It seems that the properties of the object provided to the append function must be of type string, otherwise other functions that use them won't work properly.

**Comment by jimgit** [comment]
Look at this example [JSFIDDLE - changed from string to non-string](http://jsfiddle.net/a2p40csz/2/)

**Comment by jimgit** [comment]
I volunteer to help the with problems since I have used to the BootstrapTable and really appreciate its functionality - and spend a few minutes here and there helping.  I suggested a quick fix to get the problem moved along - other people are free to suggest proper solutions.  Simple JSFiddle examples without jquery complications and other user widgets/code confusing the issues are best.  In my world,  there may be a perfect solution but working is better than broke.  It was nice that an example was included but I am more used to jsfiddle for testing since the bootstrap examples are in jsfiddle.  So I have to take the time to setup an example to show the functionality.  Did not mean to mislead you or cause confusion - just trying to help.  Your tone implies you purchased a warrantied product and expect proper customer service.  This is open source not Amazon.

**Comment by andre-ss6** [comment]
>Your tone implies you purchased a warrantied product and expect proper customer service. This is open source not Amazon.

I did not mean any of that since I was not the one reporting the issue. My complaint was only an observation, not an attack, and both its meaning and its target were very specific - the target being you, of course, not "bootstrap-table Company": I said that it seemed that you knew what the problem was from the beginning, however instead of pointing out what the problem was, you just linked to various js fiddle examples. _You even spent your time taking a screenshot and painting over the code_. You could have typed "the problem is with `id: id`" fifty times in that same time.

In any way, his reported issue is clearly not a bug and now I'm leaving this discussion.

**Comment by UtechtDustin** [comment]
Works in the latest version: http://jsfiddle.net/qurtg9Ln/3/
