### ISSUE TITLE
 dynamic sum selected row data and display

### ISSUE THREAD

**Issue by RenshuozZ** [wenzhixin/bootstrap-table#3970]
is any better solution for this request  
expect your help  
![image](https://user-images.githubusercontent.com/11639841/45252465-51426f80-b389-11e8-81c7-116e59755e00.png)

jsfiddle: https://jsfiddle.net/renshuo/c1beyz3s/13/

**Comment by RenshuozZ** [comment]
@wenzhixin

**Comment by jimgit** [comment]
[Take a look at this page](https://stackoverflow.com/questions/45190917/bootstrap-table-footer-functions-not-working-data-footer-formatter/45193022#45193022)

**Comment by UtechtDustin** [comment]
I close the issue because your last response was from sep 2018, if you still need help and the following idea dont help please reopen the issue.

Use the table option [maintainSelected](https://bootstrap-table.com/docs/api/table-options/#maintainselected), a [footerFormatter](https://bootstrap-table.com/docs/api/column-options/#footerformatter) and the [refresh](https://bootstrap-table.com/docs/api/methods/#refresh) method.
