### ISSUE TITLE
How to show data in two lines

### ISSUE THREAD

**Issue by Lightpassby** [wenzhixin/bootstrap-table#4006]
Now we can show one data{"data1":data1,"data2":data2,"data3":data3} in one line,
but I want "data2":data2 shows in the second line.

现在每条数据在一行显示，我想要每条数据分两行显示，要怎么做啊？

I want to change from

`    <table>
            <tr>
                <th data-field="1">data1</th>
                <th  data-field="2">data2</th>
                <th data-field="3">data3</th>
            </tr>
    </table>

to

    <table>
            <tr>
                <th data-field="1">data1</th>
                <th data-field="3">data3</th>
            </tr>
            <tr>
                <th data-field="2" colspan="2">data2</th>
            </tr>
    </table>`

How can I make it

**Comment by jimgit** [comment]
You could use the data-formatter to lookup the next record.

I would use the load data success to get the data records,  then lookup the "NEXT" value in the data-formatter function - note this could be different than the data table since the user may be sorting or filtering data.

![image](https://user-images.githubusercontent.com/1921941/47093574-1dabfe00-d1ef-11e8-9f60-af76383625a7.png)

**Comment by wenzhixin** [comment]
只能通过responseHandler重新预处理你的返回值，配合mergeCells方法
