### ISSUE TITLE
The Table Filter doesn't work

### ISSUE THREAD

**Issue by yhe-aa** [wenzhixin/bootstrap-table#402]
I followed the link:
http://wenzhixin.net.cn/p/bootstrap-table/docs/extensions.html
to use plugin bootstrap-table-filter.js
add data-show-filter="true" in label "table"
but it looks like below: 
![image](https://cloud.githubusercontent.com/assets/7802103/5641522/69b80dca-9675-11e4-9eda-12659ffdab7f.png)

html code:
![image](https://cloud.githubusercontent.com/assets/7802103/5641551/f67a0934-9675-11e4-8f0b-53c9171796e8.png)

any idea?

**Comment by shin-nien** [comment]
The plugin's homepage shows you how to initialise the set of filters (https://github.com/lukaskral/bootstrap-table-filter).

What isn't explained clearly is that the examples do this automatically for you if you import:
http://wenzhixin.net.cn/p/bootstrap-table/docs/assets/table-filter/ext/bs-table.js

I couldn't get filter working properly without importing 3 files in total as noted by https://github.com/wenzhixin/bootstrap-table/issues/180#issuecomment-66613287

**Comment by yhe-aa** [comment]
Hi shin-nien:

after import http://wenzhixin.net.cn/p/bootstrap-table/docs/assets/table-filter/ext/bs-table.js it worked.
But another problem occurs, the filter only worked for "Item ID", for "Item Name" and "Item Price", it always removed everything, include which I want remain. Do you know why?

**Comment by shin-nien** [comment]
Sounds like that has nothing to do with filtering. You only see those fields because they have been marked with the data-field column option.

I suspect that even without the table-filter plugin you will still not see your data so you should go back and look at the documentation and follow some of the examples.

http://bootstrap-table.wenzhixin.net.cn/documentation/#column-options

**Comment by yhe-aa** [comment]
Hi shin-nien:

it's worked after I add http://wenzhixin.net.cn/p/bootstrap-table/docs/assets/table-filter/bootstrap-table-filter.js to html.
but if I copy-paste the code to my disk, and replace it, it doesn't work, so weird!

**Comment by shin-nien** [comment]
Yeah like I said, I had to import 3 files to get everything working. As noticed already in https://github.com/wenzhixin/bootstrap-table/issues/180#issuecomment-66613287 it seems there are two bootstrap-filter files called the same thing, do different things but aren't bundled together.

**Comment by yhe-aa** [comment]
yes, another question, I see the code in the js, and it can indicate the filter type for each column, I saw it has 'range', 'ajaxSelect', 'select', how can I specify each column's filter type?

**Comment by shin-nien** [comment]
I don't think you can. It's doing a best guess based on the value types of your data.

If you need more control then I think you have to not include bs-table.js and follow the plugin setup to explicitly setup your filters.

**Comment by yhe-aa** [comment]
yes, I think I need to write js to do this, the example in github: https://github.com/lukaskral/bootstrap-table-filter  shows how to write the js. But if we can config the filter type in html code, it'll be easier.

**Comment by yhe-aa** [comment]
Hi another question, if I use data-search="true" and filter plugin, the search function will not work, why?

**Comment by fenixphp** [comment]
So what is the essence of this plugin?

- Going from illogical files.
- He has no apparent connection to the table.
- Initialized separately.
- Sending data is an external method.

**Comment by wenzhixin** [comment]
Hello @lukaskral, do you have any idea?

**Comment by fenixphp** [comment]
Integrate it as is done with the search.

**Comment by mj399** [comment]
Hey shin-nien /yhe-aa
I'm having the same problem? filter doesn't show up. 
Can you please reply what you have done to make it work?

Thanks in advance

**Comment by maxgrass** [comment]
@yhe-aa first you shoud set COLUMN attribute FILTERABLE to TRUE.

There is more to that, the old version with the snapshot at 
http://wenzhixin.net.cn/p/bootstrap-table/docs/assets/table-filter
does filtering (=works) but not integrated well (doesn't recognize 'filterable'-fields):
http://jsfiddle.net/maxgrass/d9e9y5k1/

the version with current version of lukaskral/bootstrap-table-filter
recognizes the filter attribute `<th data-field="stargazers_count" data-filterable="true">Stars</th>` but doesn't work.
http://jsfiddle.net/maxgrass/d9e9y5k1/9/

I could debug into bs-table.js:
```
    BootstrapTableFilter.prototype.getFilter = function(field) {
        if (typeof this.filters[field] === 'undefined') {
            throw 'Invalid filter ' + field;
        }
        return this.filters[field];
    };
```
and
https://github.com/lukaskral/bootstrap-table-filter/blob/master/src/ext/bs-table.js#L63

The most disturbing part is this line 63 is never reached even when no exception is thrown.

```
var rowFilter = function(item, i) {
        var filterType;
        var ret = true;
        $.each(item, function(field, value) {
            filterType = false;
            try {
                filterType = bootstrapTableFilter.getFilterType(field);
                filter = bootstrapTableFilter.getFilter(field);
/// THIS LINE NEVER REACHED
                if (typeof filter.values !== 'undefined') {
                    value = filter.values.indexOf(value);
                }
                if (filterType && typeof filterData[field] !== 'undefined') {
                    ret = ret && bootstrapTableFilter.checkFilterTypeValue(filterType, filterData[field], value);
                }
            }
            catch (e) {}
        });
        return ret;
    };
```

WHY doesn't it work:
because if a single COLUMN is not mark as FILTERABLE, then an exception will be thrown, STILL trying to filter by that column, and if exeption is thrown the ROW will be selected, as the default flag (ret) is true.

Issues #407 #473 are parallel to this one and come from not well formalized, integrated and documented extension.

**Comment by wenzhixin** [comment]
Ref to https://github.com/lukaskral/bootstrap-table-filter/issues/2, please go to the plugin repo to discuss the problem.
