### ISSUE TITLE
Search and Filter can not use together?

### ISSUE THREAD

**Issue by yhe-aa** [wenzhixin/bootstrap-table#407]
When I use data-search="true" and filter bar, the search function can not work, why?
here is the code:
![image](https://cloud.githubusercontent.com/assets/7802103/5660955/e59920c8-9760-11e4-9c1d-43963b861047.png)

**Comment by Apelsinka223** [comment]
Hi, i found how to fix it. In file /bootstrap-table/extensions/filter/bootstrap-table-filter.min.js is this code (decompressed):
![default](https://cloud.githubusercontent.com/assets/6092419/6258529/5256b272-b7da-11e4-893c-143c54d64ad5.PNG)
I changed it on this (renamed function initSearch to initSearch1 and added it into a.fn.bootstrapTable.methods.push):
![1](https://cloud.githubusercontent.com/assets/6092419/6258558/97e69d34-b7da-11e4-8d67-c13b1ad0abcc.PNG)
And now both filter and search are working! I think that problem was in redefinition function initSearch, thas why it didn't work.

**Comment by maxgrass** [comment]
write a small example at jsbin.com

**Comment by wenzhixin** [comment]
Same issue with #402, close this one.
