### ISSUE TITLE
it can not support ie11

### ISSUE THREAD

**Issue by BeyondLinda** [wenzhixin/bootstrap-table#4098]
includes、symble、 =>
can not support by ie

**Comment by tflins** [comment]
I also encountered this problem.

**Comment by wenzhixin** [comment]
**PS:** Because we use babel-cli to compile the ES6 source code, we don’t support `import babel-polyfill` to solve the problem on IE, So we need to use `core.js` to solve this problem now, we will use webpack to compile in the future.

Docs: https://bootstrap-table.wenzhixin.net.cn/docs/getting-started/introduction/#starter-template
Example: http://bootstrap-table-examples.wenzhixin.net.cn/

**Comment by plockaby** [comment]
Hello, I'm not sure why this is just a docs/build bug. This is a problem in actual usage of bootstrap-table that prevents us from upgrading to version 13.

**Comment by wenzhixin** [comment]
@plockaby Fixed this bug in develop branch.
