### ISSUE TITLE
Refresh formatter after value change

### ISSUE THREAD

**Issue by Dunge** [wenzhixin/bootstrap-table#4224]
Look at this fiddle:

https://jsfiddle.net/4azr6u1q/1/

I'm using a column formatter to display a progress bar using two values of the table.
The second value (capacity max) can be edited with editable. It indeed change the row value and do an ajax call to update the value on the server. I just want once this is finished to refresh the progress bar with the new value.

I tried 
`$('#table').bootstrapTable('resetView');`
and
`$('#table').bootstrapTable('refresh');`

But it does not work because it's not the goal of these functions

**Comment by Falseee** [comment]
The issue is that the saved value is not changed in the internal bootstrap table data (checked with [getData](https://bootstrap-table.com/docs/api/methods/#getdata)).
As workarount until this issue is fixed you could load the new data with ajax and load this with the [load](https://bootstrap-table.com/docs/api/methods/#load) funciton.

**Comment by Falseee** [comment]
Until this issue is fixed you could use a method which triggers the rendering of the table.

Example with `toggleView`: https://jsfiddle.net/fz715xvy/

**Comment by Dunge** [comment]
Thanks for the workaround!

**Comment by Falseee** [comment]
@Dunge No Problem, but leave the issue open, the error has not been resolved.

**Comment by wenzhixin** [comment]
Merged in the develop branch.
