### ISSUE TITLE
使用导出插件导出完成后console会提示一个报错信息

### ISSUE THREAD

**Issue by hellojackup** [wenzhixin/bootstrap-table#4335]
官方示例代码报错：
![image](https://user-images.githubusercontent.com/34531617/56939697-66e4ef00-6b3c-11e9-96a4-c92fe796ef35.png)

**Comment by UtechtDustin** [comment]
This issue is already known, and also fixed in our develop branch (https://github.com/wenzhixin/bootstrap-table/commit/3148edc98eb5fdf149a2ba79c7b1c4210e334080#diff-d7a23377d26f6a2c005ee0b16f07ac18R198).
You can ignore the error, this error will cause no issues (exception from the message in the console).
