### ISSUE TITLE
MS-Excel Export: Excel shows warning 

### ISSUE THREAD

**Issue by sebastiandeppisch** [wenzhixin/bootstrap-table#4347]
https://examples.bootstrap-table.com/index.html?bootstrap3#extensions/export.html
When I open the MS-Excel Export in Excel (Office Professional Plus 2010), i get this warning: 
![image](https://user-images.githubusercontent.com/3171655/57535997-90bfc200-7343-11e9-9df6-bfecfa730a10.png)
In English it should be this text: 
> The file you are trying to open, 'tableExport.xls', is in a different format than specified by the file extension. Verify that the file is not corrupted and is from a trusted source before opening the file. Do you want to open the file now?

(If I click yes, i can open the file, but it still looks like a bug)

**Comment by UtechtDustin** [comment]
First of all this would be the wrong repository to report it, because we use a [export Plugin](https://github.com/hhurz/tableExport.jquery.plugin).

You can still report it to the plugin repository, but i think they will not fix it.
The Problem is that the table will be exported as Html i guess and that is the reason why excel will show the error message.
I think to report it in the correct (Excel)Format, will cost to much resources.
Just mine exceperience with that "error message".
---
Hier bist du am falschen Ort, wir nutzen nur ein Plugin zum exportieren  der Daten.
Daher wäre deren Repository der richtige Ort den "Fehler" zu melden.

Die Fehlermeldung wird angezeigt da das Plugin (soweit ich weiß) die Tabelle als Html einfach nur speichert, excel kann das zwar auswerten aber meckert trotzdem rum.
Ich kenne den Fehler von der Arbeit, ich glaube auch das exportieren im richtigen Format würde zu viel Leistung rauben.

Du kannst gerne nachfragen (in deren Repository) aber ich glaube nicht das sie es umsetzen werden.
