### ISSUE TITLE
Documentation on using filter extensions

### ISSUE THREAD

**Issue by PotatoTroll** [wenzhixin/bootstrap-table#4432]
What is the official stance on using `Filter Control` and `Select2 Filter`. Are they mutually exclusive, and only one should be used at a time, or is the `Select2 Filter` extension dependent on `Filter Control`? What about Cookie extension in this case, does it support only `Filter Control`?

I'm asking because I have issues when using `Select2 Filter`: if  including both extensions libraries `Filter Control` and `Select2 Filter` - Cookie extension goes crazy, but if I'm using only `Select2 Filter` I get other issues - Cookie extension crashes - expects function from `Filter Control`, also some filters don't work as expected.

**Comment by UtechtDustin** [comment]
I never used the select2 filter so i also dont know the different.
But i know that the cookie extensions need some refactoring, because its sometimes buggy and dont work for all extensions.

Could you provide us an example of your issue ? (using our [editor](https://live.bootstrap-table.com/))

@wenzhixin  @djhvscf
where are the difference, could we merge this two extensions without using the select2 plugin ?

**Comment by djhvscf** [comment]
We should consider remove select2filter extension since it is almost the same as filter control
