### ISSUE TITLE
Colspan bug, plz fix it 

### ISSUE THREAD

**Issue by ugamer123** [wenzhixin/bootstrap-table#4562]
hello!

when you add colspan to the table, such an error appears
https://monosnap.com/file/w1ZFVQ1SG8Ht9A3nmJ0hshu5XYJpBk

plz fix it

**Comment by UtechtDustin** [comment]
Please provide an example of the issue (using our [editor](https://live.bootstrap-table.com/), our [example](https://examples.bootstrap-table.com/index.html#column-options/rowspan-colspan.html) looks good.

**Comment by rame0** [comment]
Just ran into an issue which look like the same.
I had grouped columns header
row 1: 5, 2, 2 cols
row 2: 9 cols

There I had misspelled last colspan. It was 3 instead of 2.
So, after update to 1.15.4 table is crushed.

After some investigation I found that function updateFieldGroup (columns) from utils does not handle columns count. In previous version it somehow ignored it.

I've tried some scenarious and found that:

1. If first row cols count (with colspan) = second row cols - everithing is ok.
2. If first row cols count (with colspan) > second row cols - lib is crushing with TypeError: `index.js:88 Uncaught TypeError: Cannot read property 'visible' of undefined`. 
3. If first row cols count (with colspan) < second row cols - not crush, but table columns count is equal to first header row columns count (with colspan).


So, I suppose there should be some kind of validation inside initHeader() before calling Utils.updateFieldGroup()that will check that all header rows are the same size.

**Comment by KaiKaiWaWa** [comment]
您好，我有同样的问题。
![image](https://user-images.githubusercontent.com/19490296/67476816-5ea0e300-f68b-11e9-9ece-8b8ff916009a.png)

example：
```
 <table
      data-id-field="id"
      data-show-refresh="false"
      data-click-to-select="true"
      class="table table-bordered table-hover"
      data-show-columns="false"
      data-show-fullscreen="false"
      data-toggle="table"
      data-sort-name="id"
      data-search="false"
    >
      <thead>
        <tr>
          <th data-visible="false" data-align="left" data-field="pluginId">
            ID
          </th>
          <th
            data-width="200px"
            data-align="center"
            data-halign="center"
            data-field="b"
          >
            名称
          </th>
          <th data-align="left" data-halign="center" data-field="params">
            参数
          </th>
          <th
            data-width="200px"
            data-align="center"
            data-halign="center"
            data-field="operate"
          >
            操作
          </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td></td>
          <td colspan="3" style="text-align:center;">
            <font style="color:red">当前脱敏策略下未配置任何插件!</font>
          </td>
        </tr>
      </tbody>
    </table>
```

**Comment by UtechtDustin** [comment]
Example: https://live.bootstrap-table.com/code/Jshf/1042 (Thanks to @Jshf)

**Comment by Jshf** [comment]
Is there any way to fix this problem ？I saw the above method, but that doesn't apply to me.I did some experiments myself and didn't succeed.

**Comment by UtechtDustin** [comment]
Fixed in the next version.

Examples:
Before: https://live.bootstrap-table.com/code/Jshf/1042
Next version: https://live.bootstrap-table.com/code/UtechtDustin/3831
