### ISSUE TITLE
Bug with setting new parameter value in refresh with query since v1.15.4

### ISSUE THREAD

**Issue by mi2git** [wenzhixin/bootstrap-table#4596]
Since version 1.15.4 we cannot set a new value for an already exsiting parameter in the function refresh in conjunction with "query".

See the following example:
https://live.bootstrap-table.com/code/mi2git/609

When having a look at the network tab in your browser, you'll see that the value for the parameter foo1 remains the initial value ('init0') when clicking on refresh which calls `$table.bootstrapTable('refresh', {silent: true, query: {foo1: 'bar'+i}});`

This works fine in earlier version like v1.15.3.

Can you please check?

**Comment by wenzhixin** [comment]
@mi2git From 1.15.4, because we need to be more flexible and suitable for other plugins, so added the `query`(`refresh` method) in `queryParams`.
PR: #4508
I am sorry this change trouble you, in your case you need to update the `queryParams` option to solve your problem: https://live.bootstrap-table.com/code/wenzhixin/628
