### ISSUE TITLE
Load Bootstrap Table's core code without dependencies

### ISSUE THREAD

**Issue by pattishih** [wenzhixin/bootstrap-table#4641]
Hi, I want to start off by saying that you and the other contributors to this project have created a wonderful extension for tables. 

However, Bootstrap Table is dependent on both JQuery, popper.js, and Bootstrap.js, which means there is a huge time delay before Bootstrap Table can do anything on the page. Using [Google's Mobile-friendly test](https://search.google.com/test/mobile-friendly), half of the time, the test does not wait long enough for Bootstrap Table. This is after I have converted most of my resources to use CDNs. I'm also unable to achieve a good score using [Google's PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/) because I cannot asynchronously load those resources when I need Bootstrap Table to serve the page's main contents. 

I propose that the core code for Bootstrap Table should be rewritten with pure Javascript so that it doesn't have any dependencies, plus it is much faster anyway. Specifically, Bootstrap table should be able to insert a table (including in card-view) with its related elements (buttons, inputs, etc) without the need of JQuery, popper.js, and Bootstrap.js. The other components that enable dropdowns, search, buttons, etc to work interactively can be deferred until after the main contents of the page have been rendered.

I am willing to help convert, but since this is your core code, I do not want to impose if you would rather handle it yourself.

Related issue: https://github.com/wenzhixin/bootstrap-table/issues/4364

**Comment by UtechtDustin** [comment]
Its also our goal to rewrite the code, so we dont need jquery or bootstrap.
But its hard todo, because the project is already very large and complex. That means it can take a long time until the bootstrap-table needs no dependency.

Currently i do the first step and create a minimal css for the bootstrap table (#4403), which means you need no css Framework (bootstrap, bulma, etc.).

Feel free to help us with that huge todo, you can help us with #4403 or you can rewrite smaller parts of the bootstrap-table to vanilla javascript!

**Comment by pattishih** [comment]
Hi thank you for the invitation! I will take a deeper look into the code when I find some time later next week.

That being said, I actually don't feel it is necessary to convert the whole code to 0 dependencies. It's called "Bootstrap" Table after all! ;) It's never a bad thing to be independent though.
