### ISSUE TITLE
The mobile extension does not work on the demo site

### ISSUE THREAD

**Issue by gurumark** [wenzhixin/bootstrap-table#5052]
Hello,
The mobile extension does not change to the card view on the demo site using Chrome 80:
https://examples.bootstrap-table.com/index.html?bootstrap3#extensions/mobile.html

thanks

**Comment by UtechtDustin** [comment]
Please update your Browser, its working fine with the newest chrome version (83.0.4103.61).

**Comment by gurumark** [comment]
It does the same thing on chrome 83.x. See the screenshot. It is at ubuntu 18.04.
![Screenshot (8)](https://user-images.githubusercontent.com/1859151/83273909-0d198300-a19b-11ea-9d56-186943562c60.png)

**Comment by UtechtDustin** [comment]
It will not work on the device emulator of the Browser, just resize the browser to the minimum.
I also tested it on my phone, works fine :-)

**Comment by gurumark** [comment]
![WhatsApp Image 2020-05-29 at 14 10 35](https://user-images.githubusercontent.com/1859151/83291685-bc178800-a1b6-11ea-8b03-feeeb6b59a02.jpeg)
![WhatsApp Image 2020-05-29 at 14 13 07](https://user-images.githubusercontent.com/1859151/83291686-bcb01e80-a1b6-11ea-9d89-b445dd380e9a.jpeg)
**************
One is Android Chrome and the other Android Brave.
It does not work in both of them.

**Comment by UtechtDustin** [comment]
@wenzhixin @djhvscf Its working for me (ios firefox/chrome) could you please check that ?

**Comment by gurumark** [comment]
![WhatsApp Image 2020-05-29 at 14 40 22](https://user-images.githubusercontent.com/1859151/83293909-6e048380-a1ba-11ea-86d3-c38e49eaadf8.jpeg)
It does not work on Android Firefox either. I already sent the screenshot for Chrome.

**Comment by UtechtDustin** [comment]
Does it not work on general or only on the demo site ?

**Comment by wenzhixin** [comment]
That's because we didn't add a mobile phone viewport to our demo website: https://github.com/wenzhixin/bootstrap-table-examples/blob/develop/index.html#L8.

You can use https://live.bootstrap-table.com/example/extensions/mobile.html.

Chrome: ![image](https://user-images.githubusercontent.com/2117018/83317153-5a5e2900-a25d-11ea-8e8c-78b9460774b1.png)

Android: ![image](https://user-images.githubusercontent.com/2117018/83317167-6ba73580-a25d-11ea-8ac6-3529ac8d6207.png)
