### ISSUE TITLE
Custom button in data-buttons-toolbar not displayed

### ISSUE THREAD

**Issue by marceloverdijk** [wenzhixin/bootstrap-table#5066]
When defining a custom button in a `buttons-toolbar` like:

```
<div id="buttons-toolbar" style="background-color: yellow;">
  <button class="btn btn-secondary" type="button" name="custom" aria-label="Pagination Switch" title="Hide/Show pagination">
    <i class="fa fa-rocket"></i>      
  </button>
</div>

<table
  id="table"
  data-buttons-toolbar="#buttons-toolbar"
  ..
```

the custom buttons disappears as can be seen in this online example:
https://live.bootstrap-table.com/code/marceloverdijk/3247

Maybe this is not the right way to add custom buttons to the buttons toolbar?
Is there another way to add custom buttons and being able to order them?

**Comment by UtechtDustin** [comment]
As described in the [documentation](https://bootstrap-table.com/docs/api/table-options/#buttonstoolbar) the `data-buttons-toolbar` option just allows you to "move" the buttons toolbar. Which means  your not able to add a button to that toolbar!
Im dont think we have a way to add custom button to that toolbar.

If we would have a way to do that, the `buttonsOrder` option would be not sort it correctly.
Because the the `buttonsOrder` option currently only sort the "default" buttons, i guess.

**Comment by marceloverdijk** [comment]
> Im dont think we have a way to add custom button to that toolbar.

OK, that’s clear. 
Should I create another issue with a feature request to be able to add custom buttons to the toolbar?

**Comment by marceloverdijk** [comment]
Let's close this one as it is expected behaviour.
