### ISSUE TITLE
x-editable with bootstrap 4 field datetime is not working. anybody having idea about it.

### ISSUE THREAD

**Issue by priya171** [wenzhixin/bootstrap-table#5101]
**Bootstraptable version(s) affected**:

**Description**  

**Example**  

**Possible  (optional)**  

**Additional context**

**Comment by UtechtDustin** [comment]
Please fill out our issue template.

**Comment by minsis** [comment]
I'll provide the example here. This would be for bootstrap 4 only since x-editable is no longer supported there has been no changes to support bootstrap 4.

The datepicker filter control is broken with the x-editable library.
https://live.bootstrap-table.com/code/minsis/4930

I suspect its because the x-editable library basically overrides the popover functions that bootstrap uses. So I dont think its the datepicker per se, but in fact the popover functions.

**Comment by djhvscf** [comment]
@minsis could you create a new issue for this scenario?

**Comment by wenzhixin** [comment]
https://blog.bootstrap-table.com/2019/10/06/use-editable-in-bootstrap-v4/
