### ISSUE TITLE
OData Support

### ISSUE THREAD

**Issue by mehmetalidumlu** [wenzhixin/bootstrap-table#5109]
Hi,
Can i use odata link in ajax request? We modified js file for odata request in previous version, but it not fully compatible. 

Thanks..

**Comment by UtechtDustin** [comment]
Could you please provide us an odata link ? :-)

**Comment by djhvscf** [comment]
I'm not very familiar with odata. Could you, please, share your customizations made?

**Comment by mehmetalidumlu** [comment]
There is download link. We used BootstrapTable V1.11.0 for this upgrade. We think that it can be further advanced.

[BootstrapTable OData.zip](https://github.com/wenzhixin/bootstrap-table/files/4818996/BootstrapTable.OData.zip)

**Comment by djhvscf** [comment]
I will looking into it. In the meantime if you could create a pull request, it would be great

**Comment by wenzhixin** [comment]
Please provide more information about OData?

**Comment by UtechtDustin** [comment]
I close this issue because we got no response from you within 7 days.
If you still interested in that feature, please provide more informations about OData.

**Comment by mattosaurus** [comment]
Hi, this is something that I would also be interested in.

Essentially OData is an attempt at a standardised way of consuming data from a REST API, it seems like it should be abble to integrate pretty nicely with bootstrap-table and indeed I've managed to get it working in a basic way already.

The basic URL format for OData is https://services.odata.org/V4/(S(5oeaak4vgrnseygfl1scsv0g))/TripPinServiceRW/People, where People is the table being querried. Through use of the [count](https://www.odata.org/getting-started/basic-tutorial/#count) [top and skip](https://www.odata.org/getting-started/basic-tutorial/#topskip) parameters we can page through the results and retrieve the total number of available results.

https://services.odata.org/V4/(S(5oeaak4vgrnseygfl1scsv0g))/TripPinServiceRW/People?$count=true&$top=10&$skip=0

Currently this can be made to work with bootstrap-table with a bit of tweaking (the count value in the returned JSON doesn't work correctly but the principle is correct).

```
<div class="row">
    <div class="col">
        <table id="auditTable"
               data-toggle="table"
               data-pagination="true"
               data-side-pagination="server"
               data-search="true"
               data-query-params="queryParams"
               data-response-handler="responseHandler"
               data-url="https://services.odata.org/V4/(S(5oeaak4vgrnseygfl1scsv0g))/TripPinServiceRW/People">
            <thead>
                <tr>
                    <th data-field="UserName" data-sortable="true">User Name</th>
                    <th data-field="FirstName" data-sortable="true">First Name</th>
                    <th data-field="LastName" data-sortable="true">Last Name</th>
                    <th data-field="Gender" data-sortable="true">Gender</th>
            </thead>
        </table>
    </div>
</div>
```

```
<script>
	function queryParams(params) {
		return {
			$top: params.limit,
			$skip: params.offset,
			$search: params.searchText,
			$sort: params.sortName,
			$order: params.sortOrder,
			$count: true
		};
	}

	function responseHandler(res) {
		return {
			total: res['@@odata.count'],
			rows: res.value
		};
	}
</script>
```

There ar a couple of other OData features that I think would integrate very nicely with bootstrap-table but which I think would require a bit more of a low level integration than the code above, these are the $select and $filter functionality.

### $select/$expand
It's possible to request specific fields rather than the complete table to be returned in the response.

https://services.odata.org/V4/(S(5oeaak4vgrnseygfl1scsv0g))/TripPinServiceRW/People?$count=true&$top=10&$skip=0&$select=UserName,FirstName,LastName,Gender

This also works with child tables using $expand/$select

https://services.odata.org/V4/(S(5oeaak4vgrnseygfl1scsv0g))/TripPinServiceRW/People?$count=true&$top=10&$skip=0&$expand=Trips($select=TripId,Name).

Ideally the table headers could be used to compose the $select parameter of the querystring, with nested fields being requested via $expand as required.

### $filter
OData could also integrate nicely with the bootstrap-table filter extension as the $filter parameter allows various filter methods such as [equals and contains](https://www.odata.org/odata-services/).

https://services.odata.org/TripPinRESTierService/(S(41olxx4xphtud20lhvqfhqkm))/Airports?$filter=contains(Location/Address,%20%27San%20Francisco%27)

Unfortunatly my javascript skills aren't good enough to produce a PR with this functionality but I'd be happy to help out on the OData side of things if this was something you were interested in adding (the sample OData service above doesn't seem to work completly as expected so it might be necessary for me to set up a fully functioning test version).

There's currently a [DataTables OData plugin](https://github.com/michele-b/Datatables-OData-v4-plugin) which may provide some direction as to how this could potentially work.

**Comment by UtechtDustin** [comment]
@mattosaurus

Thank you for the informations :-)

**Comment by mattosaurus** [comment]
Ok, so I've created an example OData API based on the standard Microsoft Adventureworks database which demonstrates all of the functionality that I think bootstrap-table could make use of.

https://datofyodata.azurewebsites.net/api/products?$count=true&$top=10&$skip=0&$select=name,color,size,listprice&$expand=productcategory($select=name)&$filter=contains(ProductCategory/Name, 'bike') and color eq 'red'&$orderby=size desc

There's also a basic demo site available [here](https://datofyodata.azurewebsites.net).

**Comment by wenzhixin** [comment]
I think you can return JSON format to support ODATA.
https://stackoverflow.com/questions/3468563/how-to-return-json-format-from-odata
