### ISSUE TITLE
Sticky header does not work

### ISSUE THREAD

**Issue by urtvs** [wenzhixin/bootstrap-table#5127]
Hi
I am using tables that created in html.
I set up data attribute
data-stickyHeader="true"
data-stickyHeaderOffsetLeft="3em"
data-stickyHeaderOffsetRight="3em"

But it does not works. What i am doing wrong?
Thanks a lot
https://live.bootstrap-table.com/code/urtvs/3638

**Comment by djhvscf** [comment]
Example: https://live.bootstrap-table.com/code/djhvscf/3639

Basically you need to use like: 
`data-sticky-header="true" data-sticky-header-offset-left="3em" data-sticky-header-offset-right="3em"` instead of `data-stickyheader="true" data-stickyheaderoffsetleft="3em" data-stickyheaderoffsetright="3em"`

**Comment by urtvs** [comment]
Look table fits for content
https://i.imgur.com/u6AVCw7.png
And when i scroll down sticky header shows for all page width
https://i.imgur.com/7bA88Fg.png

Its also not possible to fix with sticky header?
Thanks
