### ISSUE TITLE
<tr id> is lost after row sort.

### ISSUE THREAD

**Issue by ethompsy** [wenzhixin/bootstrap-table#513]
Hello,

I have struggled with this issue for a while. I use `data-sortable="true"` in my tables. I also need to use a `.click()` event that uses the row id of the clicked row to reload JSON data from an endpoint. I set the row id in the table to be the index of the data I want to load. 

I have tried creating an event like this:
    
    $messageTable = $('#message-table').bootstrapTable({
        ... blah blah this part works...
    });
    $('#message-table tr').click(function () {
        $('#connection-details').load('/connected/' + $(this).attr('id'));
    });

Initially this works. However, `$(this).attr('id')` becomes `Undefined` after a sort.

How can this be fixed?

***NOTE***: I know about the `onClickRow: function (row) {},` feature of the bootstrapTable, but there is no way I can find to use the row id from there. It never seems to be accessible. If anyone has an idea to do it this way it would be hugely preferable to an extra `.click()` function.

**Comment by djhvscf** [comment]
I think this may help you (http://issues.wenzhixin.net.cn/bootstrap-table/#415.html)

**Comment by webtweakers** [comment]
I think @ethompsy refers to the fact that any data-attributes on the `<tr>` tag are replaced with a data-attribute from bootstrap-table.

So if you have something like this:

```
<tr data-id="3" data-name="alpha">...</tr>
<tr data-id="5" data-name="beta">...</tr>
...
```

Then, when using bootstrap-table, you will end up with this in your html:

```
<tr data-index="0">...</tr>
<tr data-index="1">...</tr>
...
```

Obviously and unfortunately this will break other functionality that is depending on those original data-attributes to exist on the `<tr>` tag.

I noticed that this happens immediately, even before sorting the table (I'm using 1.7.0).

I'm not sure this is intentional or a bug or if it's even possible to retain custom data-attributes on the `<tr>` tag when sorting the table. I was hoping to use bootstrap-table in a project, but this side-effect makes that impossible. :(

**Comment by djhvscf** [comment]
use the uniqueId table options for do that

**Comment by webtweakers** [comment]
@djhvscf How would I use that to achieve something like this:

```
<tr data-index="0" data-id="3" data-name="alpha">...</tr>
<tr data-index="1" data-id="5" data-name="beta">...</tr>
...
```

As in: I want to retain my own custom data-attributes, and bootstrap-table is free to ADD it's own - but not REMOVE mine.

**Comment by ethompsy** [comment]
Looking at the docs I think it would work like this:

    <tr data-unique-id="your_unique_value1"> ... </tr>
    <tr data-unique-id="your_unique_value2"> ... </tr>

I solved this for my use by adding the value to the JSON response from my data URL, but not displaying it in the table. Then, I accessed the field with `row['whatever_i_wanna_call_it']` in the onClick function.

You can also access this in any other function that takes row, rows, or data as input.

**Comment by webtweakers** [comment]
Thanks @ethompsy, I will investigate that JSON solution later...

**Comment by djhvscf** [comment]
Close this issue becuase @ethompsy solved his issue
