### ISSUE TITLE
optional columns and automatic switch to cardview for responsive design?

### ISSUE THREAD

**Issue by docho** [wenzhixin/bootstrap-table#514]
Hi wenzhixin,
it would be great, if one could tell some columns that they are optional, so they are hidden when the window size is to small / get hidden one after another if you resize the browser window.
And as soon as no more optional columns can be hidden but the window still is / gets smaller, the table should switch to cardview.

**Comment by c-pohl** [comment]
You could easily achive this via jQuery and bootstrap-table Methods.

Use jQuery to check the window width and show/hide a column:
```javascript
$(window).on('resize', function(event){
	var windowSize = $(window).width(); // Could've done $(this).width()
    if(windowSize < 300){
        //Add your javascript for small screens here
    	$table.bootstrapTable('hideColumn', 'Stars');
    } else if(windowSize < 768){
        //Add your javascript for large screens here
    	$table.bootstrapTable('showColumn', 'Stars');
    } else {
        //Add your javascript for larger screens here
    	$table.bootstrapTable('toggleView');
    }
});
```
Use `toggleView` instead of `showColumn` method to switch to cardview.

Further information & examples:
* http://jsfiddle.net/remibreton/Aurk8/ (changing css via jquery.resize)
* http://www.coalmarch.com/blog/how-to-execute-javascript-based-on-screen-size-using-jquery
* http://issues.wenzhixin.net.cn/bootstrap-table/#methods/showColumn-hideCoulumn.html
* http://issues.wenzhixin.net.cn/bootstrap-table/#methods/toggleView.html

**Comment by docho** [comment]
Thanks, I'll give it a try!

**Comment by tedbakers** [comment]
you can apply the hidden-xs, hidden-sm, etc., using the columns class property to hide hte columns on resize but it doesn't manage the cardview switch
