### ISSUE TITLE
cell-input extension missing

### ISSUE THREAD

**Issue by haohetao** [wenzhixin/bootstrap-table#5179]
I'm using this extension in my project,, but I can't find it after updating

**Comment by wenzhixin** [comment]
We have removed this extension in the latest version. I think we can use editable instead?

**Comment by UtechtDustin** [comment]
ref #4957

**Comment by haohetao** [comment]
@wenzhixin 
editable只能是弹出框，cell-input是直接编辑，效果不一样，使用的场景不一样
我倒觉得cell-input需要加强以支持不同的input类型，比如checkbox,datepicker,spinner,select2
这是我的一个例子
![图片](https://user-images.githubusercontent.com/4592571/87491695-6706d700-c67b-11ea-960d-9f16d1d555e7.png)

**Comment by UtechtDustin** [comment]
@haohetao 
The editable plugin supports also the inline editing, the the documentation of them: https://vitalets.github.io/x-editable/docs.html
Example: https://live.bootstrap-table.com/code/UtechtDustin/4168
**Hint:** The example currently dont work on the editor because there is a issue (but you can see how you have to configure the inline mode.

@wenzhixin could you please check why the editable extension dont work on the editor ? 
I guess there is a missing dependency or there is race condition.

**Comment by wenzhixin** [comment]
https://blog.bootstrap-table.com/2019/10/06/use-editable-in-bootstrap-v4/
v3: https://live.bootstrap-table.com/code/wenzhixin/4170
