### ISSUE TITLE
Refresh/reload table

### ISSUE THREAD

**Issue by Scnck** [wenzhixin/bootstrap-table#5194]
Hi,

what is the proper why of refreshing that table without loosing scrolling positions etc?

**Comment by UtechtDustin** [comment]
Currently its not possible to refresh the table without losing the scroll position.
Because of the way how the bootstrap-table is working the table will be rerendered.

The only way you could try is to get the scroll position, refresh the table and scroll to that position.
Example: https://live.bootstrap-table.com/code/UtechtDustin/4074
Hint: This is just an example, the better way would be to use a event e.g. postBody  to scroll to the position. The setTimeout would be slower.

**Comment by wenzhixin** [comment]
Consider as `feature`.

**Comment by wenzhixin** [comment]
This [PR](https://github.com/wenzhixin/bootstrap-table/pull/7193) added a `fixedScroll` option to solve this problem.
https://examples.bootstrap-table.com/index.html#options/fixed-scroll.html
