### ISSUE TITLE
Uncaught TypeError: Invalid attempt to spread non-iterable instance

### ISSUE THREAD

**Issue by moghribalakrishna** [wenzhixin/bootstrap-table#5212]
jquery-3.3.1.min.js:2 Uncaught TypeError: Invalid attempt to spread non-iterable instance
    at bootstrap-table.min.js:10
    at er (bootstrap-table.min.js:10)
    at Object.calculateObjectValue (bootstrap-table.min.js:10)
    at bootstrap-table.min.js:10
    at Array.forEach (<anonymous>)
    at e.value (bootstrap-table.min.js:10)
    at e.value (bootstrap-table.min.js:10)
    at e.value (bootstrap-table.min.js:10)
    at new e (bootstrap-table.min.js:10)
    at HTMLTableElement.<anonymous> (bootstrap-table.min.js:10)

 
I have tried play with bootstrap version-4 & 3, b-table version 16 & 17 but still the same error.
  Don't know future consequences of this error, do fix this asap or let us know, its seriousness.

Reproducing:
https://bootstrap-table.com/docs/getting-started/introduction
 this example is also throwing the same error.

**Comment by wenzhixin** [comment]
I cannot reproduce this bug, please provide more information.

**Comment by djhvscf** [comment]
I cannot reproduce this bug, please provide more information.

**Comment by UtechtDustin** [comment]
I close this issue, because we got no response from yoi within 7 days.
Also we cant reproduce the bug.

**Comment by einfallstoll** [comment]
Leaving this here, in case anyone has this issue as well. I could track it down to this line:
https://github.com/wenzhixin/bootstrap-table/blob/248905f9421559d9ba1dea3b3624e04490e61117/src/utils/index.js#L171

In my case `calculateObjectValue (self, name, args, defaultValue)` was called with `undefined, operateEvents, undefined, undefined` where `operateEvents` was the value of the [event handler](https://bootstrap-table.com/docs/api/column-options/#events) which was set to a function which not exists.

**Comment by wankhairi93** [comment]
Hi, I had same problem.

bootstrap-table.min.js:10 Uncaught TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at bootstrap-table.min.js:10
    at l (bootstrap-table.min.js:10)
    at t.value (bootstrap-table.min.js:10)
    at t.value (bootstrap-table.min.js:10)
    at HTMLTableElement.<anonymous> (bootstrap-table.min.js:10)
    at Function.each (jquery.min.js:2)
    at S.fn.init.each (jquery.min.js:2)
    at S.fn.init.i.default.fn.bootstrapTable (bootstrap-table.min.js:10)
    at Object.success (--------:238)
    at c (jquery.min.js:2)

JSON : {d: "[{\"RowNo\":1},{\"RowNo\":2},{\"RowNo\":3},{\"RowNo\":4},{\"RowNo\":5},{\"RowNo\":6},{\"RowNo\":7}]"}

I just want to put json into $table.bootStarp({data:json}). Suddenly, i have this message error. How can i fix this problem? Btw, I use jQuery v3.6.0

**Comment by gadget00** [comment]
I can confirm that when upgrading BT to 1.38.3 I started to get this error as well.  Had to back to old version for my code to work again

**Comment by gadget00** [comment]
> Leaving this here, in case anyone has this issue as well. I could track it down to this line:
> https://github.com/wenzhixin/bootstrap-table/blob/248905f9421559d9ba1dea3b3624e04490e61117/src/utils/index.js#L171
> 
> In my case `calculateObjectValue (self, name, args, defaultValue)` was called with `undefined, operateEvents, undefined, undefined` where `operateEvents` was the value of the [event handler](https://bootstrap-table.com/docs/api/column-options/#events) which was set to a function which not exists.

where you able to fix this?

**Comment by freyp577** [comment]
I had this too, and I am not sure if it is covered by what was said above, so here my scenario
we upgraded to bootstrap-table 1.19.1 (but still using old bootstrap v3)
since then  certain HTML templates with bootstrap-table objects configured (declaratively) cause this error during loading

in the template we have
```
<table id="tableKonvertierauftraege"
...
    <th data-field="aktion" data-formatter="konvauftraege_formatter_edit"
       data-events="konvauftraege_events_edit"
```

but the handler for konvauftraege_events_edit is missing, not defined

we get the error in bootstrap-table.js on line 3592
 calculateObjectValue: function calculateObjectValue(self, name, args, defaultValue) ...
 
 with name = 'konvauftraege_events_edit'
 
 note that the same construct worked without an error with older version of BT
 
 we would like if the event handler that is missing would be shown in the error message
 TypeError: Invalid attempt to spread non-iterable instance.
 is not helpful to find and fix the problem
