### ISSUE TITLE
New method: setPageSize

### ISSUE THREAD

**Issue by gabrielchl** [wenzhixin/bootstrap-table#5272]
**Description**  
Introduce a new method to set page size, likely named setPageSize / updatePageSize / togglePageSize.

**Comment by gabrielchl** [comment]
Oh it's the same thing, just different possible names for the function.

Currently, we can change the page size using refresh settings, however, it causes the whole table to reload.

**Comment by UtechtDustin** [comment]
Oh okay, then we cant help out sorry.
The main problem is the history of the bootstrap-table, currently we HAVE to redraw the whole table because of the internal workflow.
We will try to rewrite that, but this is a HUGE task, that will take some time.

So until this is done you can use the [refreshOptions method](https://bootstrap-table.com/docs/api/methods/#refreshoptions).
Example: https://live.bootstrap-table.com/code/UtechtDustin/4444
