### ISSUE TITLE
Style injection problems with CSP

### ISSUE THREAD

**Issue by francogp** [wenzhixin/bootstrap-table#5285]
**Bootstraptable version(s) affected**:
1.17.1

**Description**  

The library uses injected "style" instead of classes and this cause this error:

```
jquery.js:5032 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-4bn8MXTmJDi8sto78UOuJ4zKFK8=' https:". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution.


buildFragment | @ | jquery.js:5032
-- | -- | --
  | domManip | @ | jquery.js:6073
  | append | @ | jquery.js:6264
  | (anonymous) | @ | jquery.js:6358
  | access | @ | jquery.js:4167
  | html | @ | jquery.js:6325
  | initHeader | @ | bootstrap-table.js:4471
  | init | @ | bootstrap-table.js:4184
  | BootstrapTable | @ | bootstrap-table.js:4174
  | (anonymous) | @ | bootstrap-table.js:7521
  | each | @ | jquery.js:381
  | each | @ | jquery.js:203
  | $.fn.bootstrapTable | @ | bootstrap-table.js:7498
  | initDatabaseTable | @ | databaseTools.js:211
  | refreshDatabaseTable | @ | databaseTools.js:244
  | window.onload | @ | (index):362


```

**Possible  (optional)**  

migrate style to class

**Comment by UtechtDustin** [comment]
I dont think this is a bug or relevant problem.
You got this message because of your CSP configuration, which means you can easily allow the bootstrap-table to use styles (Read the error message).
Also we cant migrate all styles to classes e.g. dynamic width, the height option etc.

**Comment by RogerHost** [comment]
I've read the error message.  And there's nothing there that will help.  Using a hash requires a hash code for EVERY POSSIBLE inline style that bootstrap-table could generate.  Clearly not an option.  Also can't use a nonce value, since your code that generates elements would need to know what nonce value to use.  And you're not interested in making changes for CSP.

That leaves unsafe-inline.  Which is .. unsafe.  The whole point of implementing CSP is to increase resistance to attack.  I'm not inclined to do the work to implement CSP and then undermine the security of my site just to allow bootstrap-table to run.

What I'm hearing you say is that you don't care about security.  Which is a shame.  I like bootstrap-table, but it's time to move to another solution.

**Comment by gsmethells** [comment]
@RogerHost did you find another option that you ended up liking? If so, what was it?

**Comment by gsmethells** [comment]
@UtechtDustin you are basically making your project unusable for security conscious projects -- which honestly ought to be every one of them.
