### ISSUE TITLE
升级1.18.0后出现横向滚动条

### ISSUE THREAD

**Issue by angelfind** [wenzhixin/bootstrap-table#5348]
bootstrap v4.5.2 + bootstrap-table 1.18.0
问题: bootstrap-table 当表格所有列的表头文字总和撑开后大于当前页面宽度(或某一行文字总和超过当前页面宽度)的时候, 不仅是表格内部出现横向滚动条. **page body 也会出现横向滚动条. body向右滚动后一片空白**. 之前的版本是不会出现body滚动条的.

测试页面可以直接用live.bootstrap-table.com在线调试页面即可复现该问题.
测试方法(打开在线调试页面):
https://live.bootstrap-table.com/example/options/table-ajax.html

左侧的table-tr默认只有3列td, 复制这3列td, 把表头增加到12列(td越多效果越明显), 然后点击run, 右侧预览效果就能看到table内部有横向滚动条, **然后page body也有横向滚动条, 向右滚动一片空白区域**. 这样会带来一个问题 (手机端响应式的时候, 如果页面触发了bootstrap 的alert消息窗口, 整个页面body会居中显示 [说明page body总宽度包含该表格宽度和页面右侧的空白区域] , 页面居中后得用手滑动屏幕回滚到页面左上角. 用户体验就不友好了.)

**Comment by snoopy72** [comment]
May i please ask you politly to write in english ?

Trying to read your issue is as impossible to me as maybe my mother tongue for you - but only english written issues are available for all other users. There are several unreadable issues and (unfortuanable) examples in kanji.

**Comment by UtechtDustin** [comment]
The problem is that the loading div will overflow, @djhvscf could you check that (your better in css then me).
To reproduce it, just use the example above, resize the preview so the column width is larger then the viewport.
Now you should see the third scrollbar at the bottom of the.
![Bildschirmfoto von 2020-10-01 22-09-58](https://user-images.githubusercontent.com/13292481/94858139-e1512700-0432-11eb-9785-2669f0e7a5e0.png)

**Comment by djhvscf** [comment]
I was able to reproduce it. Working on a fix for it

**Comment by angelfind** [comment]
@snoopy72, I'm very sorry, I don't know how to describe this bug in English. And thanks to @UtechtDustin for helping to describe the problem.

**Comment by snoopy72** [comment]
@angelfind no problem and reason to apologize ;) there are several issue in kanji and my comment should only lay open the problem to help when most other dont understand the problem .. not by intellect but from reading ;)
