### ISSUE TITLE
data-page-list="[10, 25, 50, 100, 200, All]" not working

### ISSUE THREAD

**Issue by picks44** [wenzhixin/bootstrap-table#5356]
**Bootstraptable version(s) affected**:
v1.18.0

**Description**  
data-page-list="[10, 25, 50, 100, 200, All]" not working on my table (I only see the options 10,25 and 50, even if I remove the data attribute from the config)

**Comment by UtechtDustin** [comment]
Please provide us an example (using our [editor](https://live.bootstrap-table.com)), our [example](https://live.bootstrap-table.com/example/options/page-list.html) for this options works fine for me.

**Comment by UtechtDustin** [comment]
You dont see the other options, because your table dont have that much entries/rows.
You set [smartDisplay](https://bootstrap-table.com/docs/api/table-options/#smartdisplay) to `false`, to see all options also if there are not enough rows.

Example: https://live.bootstrap-table.com/code/UtechtDustin/4995

**Comment by picks44** [comment]
OK. IMO it is disturbing not to find the "all" option, even with the smart display activated...

**Comment by UtechtDustin** [comment]
I agree, the `all` option should be visible.
