### ISSUE TITLE
insertRow after searching

### ISSUE THREAD

**Issue by mhaque02** [wenzhixin/bootstrap-table#5377]
Version: 1.17.0+

When the search field has text in it and is active, the insertRow does not work and no new row is inserted.

https://live.bootstrap-table.com/code/mhaque02/5070

**Comment by wenzhixin** [comment]
That's because the inserted row is also filtered, you can enter `1` for a test:
https://live.bootstrap-table.com/code/wenzhixin/5078

**Comment by UtechtDustin** [comment]
I guess the real problem is that his example using `data-url` and `data-side-pagination="server"`.
So he is searching something e.g. `test`, then he append rows (which are appended but not shown because of the search).
Now clear the search input, the bootstrap-table fetchs the data from the server and the appended Data is gone.
The better way would be to append the data on the server side then calling the `refresh` and/or `append` method.
