### ISSUE TITLE
How to change the backgroud color of specific row by external button action?

### ISSUE THREAD

**Issue by oarque** [wenzhixin/bootstrap-table#5386]
**Description**  
Thanks

**Example (optional)**

**Comment by UtechtDustin** [comment]
You have two options:

- Update the Background with normal dom manipulation (raw javascript or Jquery), this is option is not that perfect because you have to redo it every time the table has been rerendered (e.g. via a event)
- Use the [rowStyle](https://bootstrap-table.com/docs/api/table-options/#rowstyle).

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by UtechtDustin** [comment]
I will close this issue as we don't get a response from you within the last 7(+) days!
