### ISSUE TITLE
Metro4 Support

### ISSUE THREAD

**Issue by mehmetalidumlu** [wenzhixin/bootstrap-table#5511]
Hi, 
BootstrapTable supports only Bootstrap, Semantic UI, Bulma, Material Design, Foundation.
Is it in your plans to provide support for Metro4?
Thanks...

There is Metro4 Link: https://metroui.org.ua/m4q-about.html

**Comment by djhvscf** [comment]
It looks like a feature. Let's keep open and tagged as feature.

**Comment by UtechtDustin** [comment]
@djhvscf @mehmetalidumlu how popular is metro4 ?
Are there stats about the uses (counts) ?

I never heared about this and if this is a smaller unpopular framework it dont make to support it. Because it would increase the time to maintenance or improve the bootstrap-table, if there only a few users of metro4 there it would not make sense (in my opinion)

**Comment by wenzhixin** [comment]
I agree with @UtechtDustin.
https://github.com/olton/Metro-UI-CSS
If more people need it later, consider supporting it.
