### ISSUE TITLE
Search highlight destroys content of action button columns

### ISSUE THREAD

**Issue by VolkerSPE** [wenzhixin/bootstrap-table#5534]
**Bootstraptable version(s) affected**
1.18.1

**Description**
Problem with searchHighlightFormatter in action columns.
The searchHighlightFormatter is executed on columns containing HTML like columns with action buttons.

**Example**
Open online editor with 'https://live.bootstrap-table.com/example/welcome.html'. Add attribute 'data-search-highlight="true"' to the 'table'-tag. Run the example. Enter a capital letter 'i' into the search field. The action column will show destroyed HTML as the searchHighlightFormatter added the 'mark'-tags.

**Possible solution**
Perhaps an action column can be attributed with 'searchable: false' and the searchHighlightFormatter ignores all columns marked as not searchable.

**Comment by kaperusov** [comment]
> Perhaps an action column can be attributed with 'searchable: false' and the searchHighlightFormatter ignores all columns marked as not searchable.

Yes, but if we open example with formatted values, e.g.:

[https://live.bootstrap-table.com/example/welcomes/from-html.html ](https://live.bootstrap-table.com/example/welcomes/from-html.html)

Add a 'data-search-highlight="true"' attribute to the 'table'-tag and typing an uppercase 'a' into the search field, the name column will show destroyed HTML... But that field must be searchable.

**Comment by VolkerSPE** [comment]
**@kaperusov** Thanks a lot for looking on the problem!

Your solution is what I first thought to do to cure the problem by writing a custom highlight formatter. 

This fix works fine as long as the tables are rather small. On larger tables with thousands of rows there is a significant impact on run time - even on slower hardware. The setup of a DOM parser and the parsing itself together with the regular expression is too complex.

In my concrete project the HTML tags within row cells are injected by a custom formatter. Taking this into account there is a possible fix of the problem by changing the sequence of processing in function 'initRow'.

I've done a modification that first calls the (custom) search highlight formatter (at this point there is no HTML markup) and then passes the result to the (custom) formatter for this specific row cell (who does the HTML markup to the already marked cell content). 

This works perfect for me - but I know it doesn't work for your example with a static initialization of table cell content.

Nevertheless perhaps 'initRow' can be modified as described as it gives users with a dynamic table content a chance to handle this highlight problem very effective (in sense of run time). I think dynamic table content is the majority of use cases out in the field.

Seems there is no simple solution that fits to all the needs.

**Comment by kaperusov** [comment]
Thanks for your detailed look at my solution.

I became interested in this problem, because in my project I did my own search string highlighting, because at that time there was no 'data-search-highlight = "true"' option in the bootstrap table. I found out about this from your issue. Thanks a lot. 

The solution with the DOM parser works perfect for me.
My example with static initialization of the contents of a table cell is just an example that well demonstrated the need to search in a column containing html. Of course, dynamic table content is the majority of use cases.

Of course, on thousands of table records, the parser will be slow. I thought about it. But it seems strange to me to give the user 1000 or more records on one page and try to format them on fly. 

On the other hand, why not? Let them wait. ;-)

If this is really needed, everyone can customize the formatter for their needs. As you did it (and I in my own project).

Your solution with 'initRow' looks pretty good. But I also cannot say how universal it is for the project as a whole. This needs to be appreciated by some of the main developers.

Anyway, I added a search attribute check, which really wasn't there. As you suggested. Hope this will be helpful. : )
