### ISSUE TITLE
Limit text height in a row?

### ISSUE THREAD

**Issue by RossAWaddell** [wenzhixin/bootstrap-table#5551]
I've been able to limit the width of a column using CSS & ellipsis, but how do I limit the maximum height of a row? Two columns in my table can have multiple text lines and I want to limit the height of each row to just 3 or 4 lines.

[https://live.bootstrap-table.com/code/RossAWaddell/6226](url)

**EDIT**: I copied and pasted this link from the online editor but for some reason it just takes be back to the main GitHub page. How do I find all the online editor examples I've created?

**Comment by RossAWaddell** [comment]
[https://live.bootstrap-table.com/code/RossAWaddell/6229](url)

**Comment by atomkind** [comment]
Like allwys, we need to break it down - understanding CSS, boxing elements and what HTML-Tags can have which attributes and styles.

First: How do you structure your cells?
Of course, every cell has different content. One might have just 1 element, one have a large Text and one have some buttons or what not.

If you have a long text WITHOUT line-breaks (`<br />`) AND have your `.tblColEllipsis` class, it will display the whole long text in only 1 row because of the `white-space: nowrap;` in your CSS.
If it's inside an `<p>` Element, the ellipsis '...' does not appear because the `.tblColEllipsis` class is on the `<td>` and not on the `<p>`.
(see example)

Secound - try and error...
As i tried i realized thar this is not that easy... but found a way, maybe it helps.
The `.tblColEllipsis` NEED the `whitespace: nowrap;`, otherwise it wont work. This means, you will have the `...` on every line, that is too long.

SOLUTION:
1) size your <td>
2) add a <div> or <p> arround the content (this is a so called "wrapper"..)
3) give wrapper height and width 100% + overflow: hidden! 

To set the height (of the whole row!) use CSS selector `#table>tbody>tr>td` - this selects all cells inside your table-body and does not affect other table-cells like tables inside your table-cell. (the `tr>td` selects only `td` elements that are direct child of `tr` ).
Give em a `height: 100px;` or what you need
Consider: bootstraptable CSS set a `padding: .75rem` to every cell! (this is always added so the height ist not exactly 100px, it is 100px + 0.75rem at the top + 0.75rem at the bottom)
Maybe you give your elements also a `line-height` of 50px for example. So (in theory..) only 2 lines would be shown.
Have a wrapper arround the table-cell-content, give it `height: 100%; width: 100%; overflow: hidden;` and thats it.

[https://live.bootstrap-table.com/code/atomkind/6267](https://live.bootstrap-table.com/code/atomkind/6267)

Remember, if you dont have the wrapper arround any table-cell-content and this content will be higher or longer than you want it to be, it will break the whole row because all cells take the hight of the heighest content.

---

By the way - mostly all browsers have developer-tools, most you can open it whith F12, there you can select the elements, see the CSS and test -on the fly- by editing directly! (in Safari its alt+cmd+c)

And your links here to the live-examples, you click the link button and `[](url)` will appear - inside the `[]` you type your link text and REPLACE `url` whith the link! Just like HTML `<a>`-Tag! <a href="`url`">`[]`</a>

---

that took a bit time :-P

**Comment by RossAWaddell** [comment]
> Like allways, we need to break it down - understanding CSS, boxing elements and what HTML-Tags can have which attributes and styles.
> 
> First: How do you structure your cells?
> Of course, every cell has different content. One might have just 1 element, one have a large Text and one have some buttons or what not.
> 
> If you have a long text WITHOUT line-breaks (`<br />`) AND have your `.tblColEllipsis` class, it will display the whole long text in only 1 row because of the `white-space: nowrap;` in your CSS.
> If it's inside an `<p>` Element, the ellipsis '...' does not appear because the `.tblColEllipsis` class is on the `<td>` and not on the `<p>`.
> (see example)
> 
> Secound - try and error...
> As i tried i realized thar this is not that easy... but found a way, maybe it helps.
> The `.tblColEllipsis` NEED the `whitespace: nowrap;`, otherwise it wont work. This means, you will have the `...` on every line, that is too long.
> 
> SOLUTION:
> 
> 1. size your `<td>`
> 2. add a `<div>` or `<p>` arround the content (this is a so called "wrapper"..)
> 3. give wrapper height and width 100% + overflow: hidden!
> 
> To set the height (of the whole row!) use CSS selector `#table>tbody>tr>td` - this selects all cells inside your table-body and does not affect other table-cells like tables inside your table-cell. (the `tr>td` selects only `td` elements that are direct child of `tr` ).
> Give em a `height: 100px;` or what you need
> Consider: bootstraptable CSS set a `padding: .75rem` to every cell! (this is always added so the height ist not exactly 100px, it is 100px + 0.75rem at the top + 0.75rem at the bottom)
> Maybe you give your elements also a `line-height` of 50px for example. So (in theory..) only 2 lines would be shown.
> Have a wrapper arround the table-cell-content, give it `height: 100%; width: 100%; overflow: hidden;` and thats it.
> 
> https://live.bootstrap-table.com/code/atomkind/6267
> 
> Remember, if you dont have the wrapper arround any table-cell-content and this content will be higher or longer than you want it to be, it will break the whole row because all cells take the hight of the heighest content.
> 
> By the way - mostly all browsers have developer-tools, most you can open it whith F12, there you can select the elements, see the CSS and test -on the fly- by editing directly! (in Safari its alt+cmd+c)
> 
> And your links here to the live-examples, you click the link button and `[](url)` will appear - inside the `[]` you type your link text and REPLACE `url` whith the link! Just like HTML `<a>`-Tag! `<a href="**_url_**">**_[]_**</a>`
> 
> that took a bit time :-P

Thanks. I'll try your solution.

BTW, my issue with the online editor is not how to add a URL to a post (I did that) but when I clicked it earlier it just takes me to the main Github page for this, not my saved online editor example. Also, I don't know how to find all the ones I've created - if I go back to my other posts and click the link, it also takes me to the main Github page. Curiouser and curiouser.

**Comment by atomkind** [comment]
I also searched for my own eyamples but didn't find an option to show all my own saved eyamples, could be a possible new "feature" in the future if we make this wish popular with a new post, maybe as "load" button next to the "save" button ;-)

I searched one of your last posts and i can see you havent replaced (`url`) with the link. In issure 5518 your link goes to `github.com/wenzhixin/bootstrap-table/issues/url` and `/url` tells me, you havent replaced it `[](url)` .
If there is no "http*" in the `url` part, it links the text in `[]` to the /issues/ of github/wenzhixin/bootstrap-table  site.
I did the same on my first posts :-)

`[see issure 5518](5518)` links to `https://github.com/wenzhixin/bootstrap-table/issues/5518`:
[see issure 5518](5518)

and
`[link text you want](https://live.bootstrap-table.com/code/atomkind/6267)` links to my last example (`https://live.bootstrap-table.com/code/atomkind/6267`):
[link text you want](https://live.bootstrap-table.com/code/atomkind/6267)

**Comment by RossAWaddell** [comment]
My text won't be inside a <p> tag so it doesn't appear to work for me, even when limiting the height to 20px

[https://live.bootstrap-table.com/code/RossAWaddell/6297](https://live.bootstrap-table.com/code/RossAWaddell/6297)

**Comment by RossAWaddell** [comment]
Thanks!
