### ISSUE TITLE
Multiple Checkbox in Row

### ISSUE THREAD

**Issue by mehmetalidumlu** [wenzhixin/bootstrap-table#5680]
**Bootstraptable version(s) affected**:
1.18.3

**Description**  
Hi, when i click a checkbox then select all checkbox in that row. Can you help with this error? Thank you so much

**Example**  
https://live.bootstrap-table.com/code/mehmetalidumlu/7350

**Comment by OzzieIsaacs** [comment]
I think this is a duplicate of  #1069. I had the same problem at solved it via the `formatter` option as suggested there

**Comment by mehmetalidumlu** [comment]
Thanks @OzzieIsaacs ,
I had seen this example before, but it was difficult to manage. For this reason, I think I will use Editable. Still, thank you for your interest.

Take care of yourself

**Comment by Alchoder** [comment]
I had a similar problem,  I needed to have a table filled with checkboxes

so tried to change a bit the js file to do so, but I might (probably) have broken some features, but since i'm using this lib only for this purpose...

in version 1.21.0
My goal is to use `onClickCell` event to call `updateCell` and manually change the value of the field.
Clicking on the cell is updating the value as well.

line 7063 => I changed the data-index from `i` to `column.field` , it avoids from selecting all checkboxes of a row
```text = [_this7.options.cardView ? "<div class=\"card-view ".concat(c, "\">") : "<td class=\"bs-checkbox ".concat(c, "\"").concat(class_).concat(style_, ">"), "<label>\n            <input\n            data-index=\"".concat(column.field, "\"\n            name=\"").concat(_this7.options.selectItemName, "\"\n            type=\"").concat(type, "\"\n            ").concat(Utils.sprintf('value="%s"', item[_this7.options.idField]), "\n            ").concat(Utils.sprintf('checked="%s"', isChecked ? 'checked' : undefined), "\n            ").concat(Utils.sprintf('disabled="%s"', isDisabled ? 'disabled' : undefined), " />\n            <span></span>\n            </label>"), _this7.header.formatters[j] && typeof value === 'string' ? value : '', _this7.options.cardView ? '</div>' : '</td>'].join('');```

then I change the 'onCheck' event to make it call the 'onClickCell' (i know it's ugly)
line 7246
I changed the whole function to make it call the click-cell event instead
```
this.$selectItem.off('click').on('click', function (e) {
          e.stopImmediatePropagation();
          var $this = $__default["default"](e.currentTarget);

          //_this9._toggleCheck($this.prop('checked'), $this.data('index'));
                
          var $td = $__default["default"](e.currentTarget.parentElement.parentElement)
          var index = $td[0].cellIndex;
          var fields = _this9.getVisibleFields();
          var field = fields[index - Utils.getDetailViewIndexOffset(_this9.options)];

          var $tr = $td.parent();
          var rowIndex = $tr.data('index');
          var item = _this9.data[rowIndex];
          var column = _this9.columns[_this9.fieldsColumnsIndex[field]];
          var value = Utils.getItemField(item, field, _this9.options.escape, column.escape);

          _this9.trigger(e.type === 'click' ? 'click-cell' : 'dbl-click-cell', field, value, item, $td);

        });
```

with that i'm able to change the value at the click on the cell and at the check on the check box

```
$('#table').bootstrapTable({
            checkboxHeader:false,
            columns: columns,
            data: data,
            onClickCell: (field, value, row, el)=> {
                $('#table').bootstrapTable('updateCell', {index: data.findIndex(x => x.firstColumnValue == row.firstColumnValue), field: field, value: !value, reinit: false})
                el[0].firstChild.firstElementChild.checked = !value;
            }
        }); 
```

![examples](https://user-images.githubusercontent.com/45818215/186454902-041c0b71-7f4b-4a0f-8922-2bea5034b8c4.gif)
