### ISSUE TITLE
mobile responsive

### ISSUE THREAD

**Issue by mozts2005** [wenzhixin/bootstrap-table#594]
I would like to see a way to make the tables mobile responsive.

when the screen is a given size switch to using the card view automatically.

**Comment by djhvscf** [comment]
Good idea! :+1:

**Comment by rfossella** [comment]
Yes, this is a good idea.  There is a "toggleView" method, but it seems you'd have to check the size or contents of the table to see if your should toggle to cardview AND also remember state so that when the view is large again it returns back to the view you want - i.e. cardview or tableview.

mytable.bootstrapTable('toggleView');  // toggle cardview

**Comment by wenzhixin** [comment]
OK, now you need to toggle it manually.
