### ISSUE TITLE
Multiple table export

### ISSUE THREAD

**Issue by dasilvacn** [wenzhixin/bootstrap-table#5966]
### Description

Request to export all same class but multiple tables on a screen in a single excel with bootstrap table export

**Comment by UtechtDustin** [comment]
It seems this is not possible with the [tableExport dependency](https://github.com/hhurz/tableExport.jquery.plugin).
If you have multiple tables which should be exported in one excel you should do this on the backend of your application.
This also makes sense because nobody want table under table under table, you have to style it somehow :-)
