### ISSUE TITLE
UniqueId with double quotes -> unrecognized expression

### ISSUE THREAD

**Issue by s72817** [wenzhixin/bootstrap-table#6043]
### Bootstraptable version(s) affected

1.19.1

### Description

When I give a string with double quotes as value and set the key of the value as uniqueId, the table is not working.
See example. The escape function isnt working.

### Example(s)

https://live.bootstrap-table.com/code/s72817/10424

### Possible Solutions

Go back to v1.18.3

**Comment by UtechtDustin** [comment]
The issue is that use used `name` as unique id, which means your `My "Title"` will be written to a `data attribute` and break the html.
You always should use safe unique ids as example alphanumeric id's.

We could escape the data, create a hash or use base64. But this would cost performance, which is unnecessary, because unique ids should be alphanumeric (or just numbers).

I added a warning in the PR #6050.

**Comment by s72817** [comment]
I understand, but why is it working with the old v1.18?

**Comment by UtechtDustin** [comment]
We could check that, but it was a lucky coincidence i guess.
I don't think its necessary to check, because of the explaination above :-)

**Comment by s72817** [comment]
Solved by using encodeURIComponent(string);
Thanks for the help :)
