### ISSUE TITLE
Filter control: Word is part of another word

### ISSUE THREAD

**Issue by sebastiangehrt** [wenzhixin/bootstrap-table#6121]
### Bootstraptable version(s) affected

1.20.0

### Description

If the word is part of another word, the filter will display both values and not only the word selected in the filter

### Example(s)

https://live.bootstrap-table.com/code/sebastiangehrt/11361

Filter on "Schwimmen" --> You will get "Schwimmen" and "Rettungs**schwimmen**"

**Comment by UtechtDustin** [comment]
Hallo @sebastiangehrt, da hast du absolut recht.
Es macht nicht all zu viel Sinn das bei `Schwimmen` auch `Rettungsschwimmen` angezeigt wird.

@djhvscf could you check this ?
I don't know if we always should compare the whole word (for selects filtering), but at least a options should exists.

**Comment by djhvscf** [comment]
You can use filterStrict mode. See this example: https://live.bootstrap-table.com/code/djhvscf/11387

**Comment by UtechtDustin** [comment]
@djhvscf i think it makes sense to set the filterStrict option to `true` as default for select's.
99% of the cases you want to filter strictly with select's or not ?

**Comment by djhvscf** [comment]
I agree @UtechtDustin

**Comment by UtechtDustin** [comment]
I'm not sure how we can solve this issue.
The default value is `false` which means we can't change
```
if (column.filterStrictSearch)
```
to
```
if (column.filterStrictSearch || column.filterControl === 'select')
```
Because then nobody could use none-strict selects.
We also can't check if someone explicit added for the `filterStrictSearch: false`, because we merge the options. That means we don't know if the option comes from the default options or from the passed options.
So my idea was to add a new key `passed` to the internal `column object`, so we can differentiate if the option was passed by user or by default value.

@djhvscf I'm not sure if this is the best solution, please check #6298
