### ISSUE TITLE
bootstrap3 large columns ,the header is displayed messed up

### ISSUE THREAD

**Issue by luoqifa** [wenzhixin/bootstrap-table#6335]
### Bootstraptable version(s) affected

1.20.2

### Description

move to the far right, resize the window or click on the column to sort。

### Example(s)

https://live.bootstrap-table.com/code/luoqifa/12444

### Additional Context

jquery 3.6
bootstrap 3.3.7
bootstrap-table 1.20.2

**Comment by luoqifa** [comment]
bootstrap 4 and bootstrap 5 versions are OK

**Comment by wenzhixin** [comment]
This is because the CSS implementation of bootstrap3 is different from bootstrap4 and 5, but 3 is no longer maintained, so it is not intended to be added to the code.

You can add a new file(`bootstrap-table-bootstrap3.js`) to solve the problem:
```js
var _resetView = BootstrapTable.prototype.resetView

BootstrapTable.prototype.resetView = function (params) {
  _resetView.apply(this, [params])

  setTimeout(() => {
    // only for bootstrap3
    this.$tableBody.trigger('scroll')
  }, 100)
}
```

Online Example: https://live.bootstrap-table.com/code/wenzhixin/15896
