### ISSUE TITLE
Fix table height

### ISSUE THREAD

**Issue by afbruno** [wenzhixin/bootstrap-table#641]
Is it possible to fix the height of the table.
In the current version, even if I set the date-height attribute, the table automatically adjusts its height according to the number of lines when I perform some action, such as, select the page, filter column, etc.
Thank you a lot!

**Comment by dabros** [comment]
@afbruno - im actually not quite sure what you mean by 'fix the height'?

Did you want to override tr height, thead or tbody or something - because it takes the default tr/td height and then uses the max_num_rows (or whatever) to print up to X rows

just affect the base styles for that table, ie: 

```css
.my-table tr td{ height:15px; }
```

Then it will use that

Can you please provide a fiddle of what your trying to do if this doesnt answer your question

**Comment by djhvscf** [comment]
If the solution by @dabros is not working then reopen this issue, @afbruno

**Comment by pedrosalpr** [comment]
Modify in the css
<pre> .fixed-table-body {
    overflow-x: auto;
    overflow-y: auto;
    height: auto; /* 100%*/
}</code>

It worked for me.

**Comment by afbruno** [comment]
Didn't work for me. 
What I did was adjust the height after each rendering event.

var fixedHeight = 500;
my-table.bootstrapTable(options).on('post-body.bs.table', function() {
	$(this).closest('.fixed-table-container').css('height', fixedHeight + 'px');
	});

Thus, the table height keeps fixed at 500px even without many rows after any updates.

Thx
