### ISSUE TITLE
How can I use data in a row one after the other?

### ISSUE THREAD

**Issue by mstftuncel** [wenzhixin/bootstrap-table#6499]
### Description

Hi.
I have API. I want to use data like below:

{    
"instructions": [
        {
            "name": "test",
            "checked": false
        },
        {
            "name": "test1",
            "checked": false
        }
    ],
...
}.

I use table like this:
$(function () {

    $table.bootstrapTable({
      url: API_URL,
      showRefresh: true,
      showColumns: true,
      search: true,
      toolbar: '.toolbar',
      columns: [
        {
          field: 'instructions',
          title: 'instructions',
          align: 'center', 
        },
...

If I use like that, i take answer like that in table:
[object Object],[object Object].

I want to show one data in each row:
[object Object]
[object Object]

Can I do? 
Thanks for answers.

**Comment by UtechtDustin** [comment]
To use the Array `instructions` you have to use the [responseHandler option](https://bootstrap-table.com/docs/api/table-options/#responsehandler).
Similar Example for the `responseHandler`: https://live.bootstrap-table.com/example/options/response-handler.html

As `field` you have to use `name` instead of `instructions`.
Does this answer your question ?

**Comment by UtechtDustin** [comment]
I'm closing this PR as wen don't get any response from you.
