### ISSUE TITLE
Can you provide a unique ID on the row (TR) if you load data through a URL?

### ISSUE THREAD

**Issue by vicentor** [wenzhixin/bootstrap-table#658]
I put the issue on StackOverflow:
http://stackoverflow.com/questions/29287376/can-you-provide-a-unique-id-on-the-row-tr-if-you-load-data-through-a-url

**Comment by djhvscf** [comment]
Something like this: https://github.com/wenzhixin/bootstrap-table/issues/586 ??

**Comment by vicentor** [comment]
Yeah! It's very similar! If that is not supported in any way, how can you identify a row to do further actions with it? Assuming the row is a row from my MySQL table?

**Comment by cherhui** [comment]
can you place "id_account":"1" into your column and use it as your unique identifier?

**Comment by vicentor** [comment]
It's a plausible workaround. I could put the UID in the first column and hide it. It's more HTML markup though.

**Comment by djhvscf** [comment]
I'm working on a solution.. I will do a pull request.. @vicentor

**Comment by djhvscf** [comment]
In progress to merge the solution @vicentor

**Comment by wenzhixin** [comment]
Merged.

**Comment by vicentor** [comment]
Great! How can it be used? Is it available in 1.7?

**Comment by djhvscf** [comment]
Yes, it is avaiable.. In your table options you have to set data-unique-id="your-id" 
http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options

**Comment by Airn5475** [comment]
I updated my project to 1.8 to pick up this change.  The only way I was able to get the data-uniqueid attribute on the TR element was to include it as a column.

Do we really have to include an "id" column in the table in order to utilize the data-unique-id option or am I just not using this right?

**Comment by djhvscf** [comment]
You have to use in the <table> tag.. like this: <table id="yourTableId" data-toggle="table" data-unique-id="yourUniqueId"....>

**Comment by Airn5475** [comment]
@djhvscf Yeah I added that part.
```html
<table data-toggle="table" data-unique-id="RecordID">
```
However, the data-uniqueid attribute isn't appearing on the TR element like below.
```html
<tr data-index="0" data-uniqueid="12345">
```
The only way I can get it to appear is to include a column that has the ID in it.
```html
<th data-field="RecordID">Record ID</th>
```

**Comment by djhvscf** [comment]
See this: http://jsfiddle.net/djhvscf/e3nk137y/1822/ 
The data-unique-id option will be rendered like: data-uniqueid

**Comment by Airn5475** [comment]
@djhvscf thanks for your example.  I actually had something out of line on on my end.

**Comment by KulanthaivelChinnadurai** [comment]
I am using data-unique-id="ID" in my table. My server may return duplicate values.(Return same object more than 1 times).
 When I append the rows into bootstrap table same Id objects are getting added again. 
how to avoid that...

**Comment by wenzhixin** [comment]
It is better to provide an uniqueness ID.

**Comment by KulanthaivelChinnadurai** [comment]
This is my table. I am loading the data dynamicaly from server. Here Job ID will be unique. 
![table](https://cloud.githubusercontent.com/assets/12044331/9223127/031424be-4115-11e5-861a-c0dcc6c555fd.png)

when I create a new record server will send the details 
When I edit a record that time also server will send the details.
Server can send multiple(no limit) records at a time. (Job ID will be unique for all records.).
Whenever the server send records,I don't want to use append function.
My Requirement is 
1)If the table is already having the record then I need to update the row with new values(ID will be unique. Remaining details may be changed.) 
2)If the table is not containing the record then I want to append a new row. (New record I want to create)
Is it possible to achieve this.
I don't want to go for iterating the table.
Because server will be sending bulk data. 
For updating the row iteration may be ok. but for creating record if I check the entire table and creating rows one by one means it will take long time.

I need to capture the ID of the table records which is already there and update only that particular rows. Remaining ID which are not available in the UI i need to append the rows 

Any idea to achieve this..

**Comment by wenzhixin** [comment]
You can do it like this, for example:
```js
function handleJob(job) {
    var index = inArray(job, allJobs); // check job exists
    if (index === -1) {
        $table.bootstrapTable('prepend', job);
        return;
    }
    if (job.state === 'deleted') {
        $table.bootstrapTable('remove', {
            field: 'id',
            values: [job.id]
        });
    } else {
        $table.bootstrapTable('updateRow', {
            index: index,
            row: job
        });
    }
}
```

**Comment by MeMurillo** [comment]
Thank you wenzhixin!
I use this (in my js (button click method linked)) to add 1:

function masProducido(index, cantProd){
    $('#tabla').bootstrapTable('updateRow', {
            index: index,
            row: {
                CantidadProducida: cantProd + 1
            }
        });
}

Regards.
