### ISSUE TITLE
Use own url other than mentioned url for data-url.

### ISSUE THREAD

**Issue by prasadchitti** [wenzhixin/bootstrap-table#6678]
### Description

I would like to use own URL where hosting JSON on different site such as https://www.jsonkeeper.com/b/A4MR at data-url.
but this is not wokring if I just replace the URL. Please suggest me steps to achieve the solution.

**Comment by UtechtDustin** [comment]
The request is blocked by [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS), `jsonkeeper.com` don't send the cors header. That means the browser will stop the request.   
For example https://api.npoint.io/1bf6801f5389b3e440bb would work, because they set the cors header(s) e.g. `access-control-allow-origin: *`

Example: https://live.bootstrap-table.com/code/UtechtDustin/14634
