### ISSUE TITLE
Indian Currency Not Showing In Pdf Export

### ISSUE THREAD

**Issue by ShreeSoftech-Rupesh** [wenzhixin/bootstrap-table#6898]
### Description

indian currency not show in pdf

![Screenshot from 2023-07-13 16-49-24](https://github.com/wenzhixin/bootstrap-table/assets/92097236/651616c1-358a-4b14-b2b1-99a0748877be)

### Example(s)

https://live.bootstrap-table.com/code/ShreeSoftech-Rupesh/15888

**Comment by wenzhixin** [comment]
If Indian currency is not showing in PDF export, it could be due to a font issue. Here are some steps you can try to resolve the issue:

* Check if the font you are using supports Indian currency symbols. If not, try using a different font that supports Indian currency symbols.
* If you are using a custom font, make sure it is embedded in the PDF file. Some PDF viewers may not have the font installed on their system, which could cause the symbols to be replaced with a default symbol.

If none of these steps resolve the issue, you can create a new issue to the export repo: https://github.com/hhurz/tableExport.jquery.plugin.
