### ISSUE TITLE
`data-filter-data` column option does not load filter values

### ISSUE THREAD

**Issue by paulinevos** [wenzhixin/bootstrap-table#6943]
### Bootstraptable version(s) affected

1.22.1

### Description

The `data-filter-data` column option doesn't load the specified values. I've attempted with `var:`, `func:` and `obj:`, but none of them seem to work (unless I'm misusing this option?)

### Example(s)

https://live.bootstrap-table.com/code/paulinevos/16085

### Possible Solutions

I haven't tried debugging this yet but can help out with debugging/fixing should you want me to.

**Comment by paulinevos** [comment]
I'll close this because running locally and debugging I've figured out the variables and objects are supposed to be in the global scope. The usage isn't super clear to me from the docs. Should I open a PR to improve the docs?

**Comment by hepcat72** [comment]
How the heck did you get this to work? My variables/objects are global, but I can never get the lists to populate, even using your example code.

**Comment by hepcat72** [comment]
OK. I used breakpoints on the BST filter code, where it was raising a TypeError, to figure out that despite me logging to the console that my variable existed (in the same scope I was initializing the table), BST was only looking at the keys of the "window" object (and not any deeper), but I was declaring my variable inside the `DOMContentLoaded` listener function - because my select list content is from JSON parsed from another element, so I had to declare the variable outside the listener, and set it inside the `DOMContentLoaded` listener function in order for things to work.  E.g.

```
    {{ filter_select_lists|json_script:"filter_select_lists" }}  <!-- Django -->
    <script>
        const filterSelectOptions = {};

        document.addEventListener("DOMContentLoaded", function(){

            let filterSelectOptionsElem = document.getElementById("filter_select_lists");
            globalThis.filterSelectOptions = JSON.parse(filterSelectOptionsElem.textContent);

            $('#{{ table_id }}').bootstrapTable(...)
    </script>
```

Now I'm on to the next issue.  2 of my 6 select lists don't seem to work...  I suspect that it is the template decorations?  The underlying django filter is working and the results appear briefly, but then BST clears them all away...  Ugh.

**Comment by hepcat72** [comment]
Oh geez.  For some reason, it was defaulting `data-filter-strict-search` to `true`.  The docs say the default is `false`, but when I explicitly set it to `false`, it started working. I'm guessing maybe there are other settings that can change that default that I'm unaware of?
