### ISSUE TITLE
actionEvents not working in custom view

### ISSUE THREAD

**Issue by ShreeSoftech-Rupesh** [wenzhixin/bootstrap-table#7319]
### Description

I'm trying to implement a custom view in my project. Everything works perfectly, but the action events are not functioning.

### Example(s)

here is [example](https://live.bootstrap-table.com/code/ShreeSoftech-Rupesh/17576)

**Comment by wenzhixin** [comment]
Because the custom view contains a custom HTML template and does not involve `tr` or `th` elements, the column `events` you have set up here will not take effect and will only apply to the table view. 

So that you know, you will need to add the `click` events within the custom view yourself.
A working example: https://live.bootstrap-table.com/code/wenzhixin/17588
