### ISSUE TITLE
About checkall and checkboxHeader

### ISSUE THREAD

**Issue by sleefd** [wenzhixin/bootstrap-table#745]
There is an application scenario below which I think is more general.

If I click the  checkbox in table head ,I just want to select all the checkboxes in  the correspond column, not all checkboxes in the table.
This can be done by adding a new column attribute or change the checkAll_ function in code.

And I also want a column which has a table head title ,but all tds are checkboxes. 
So I think the  checkboxHeader attribute should be added to the column, not the options.

What 's your opinion?

**Comment by sleefd** [comment]
@wenzhixin

**Comment by wenzhixin** [comment]
Hi @sleefd , in our plugin, the most important thing we use checkbox or radio is to select the columns instead of show the column state, because we will put our `idField` to checkbox or radio input, so I think if you want to show checkbox in other column, the better way is to use the `formatter` option to do that. Thanks for anyway, close this issue.
