### ISSUE TITLE
Column width (data-width) not working when table has scroll

### ISSUE THREAD

**Issue by Thang1PV** [wenzhixin/bootstrap-table#7551]
### Bootstraptable version(s) affected

1.23.0

### Description

Column width (data-width) not working when table has scroll

### Example(s)

https://live.bootstrap-table.com/code/Thang1PV/18242

**Comment by Thang1PV** [comment]
Hi, anyone can help me ?

**Comment by wenzhixin** [comment]
You can set the class with `min-width` to solve your problem: https://live.bootstrap-table.com/code/wenzhixin/18349.

---

Answer by GPT:

1. Content Width Priority: Table cell width is greatly influenced by the content within the cells. If the content’s width exceeds 100px, the browser will adjust the width to fit the content. min-width ensures that the width cannot be smaller than the specified value, even if the content requires less space, whereas width is more of an ideal value that might be overridden by the content’s size.

2. Table Layout Mode:

- By default, tables use table-layout: auto, which dynamically adjusts column widths based on content. In this mode, width may not be honored because the browser prioritizes displaying the full content.
- Setting table-layout: fixed forces the table to respect the width property, but content might be truncated or wrapped.

4. Priority of min-width: min-width enforces a minimum width, ensuring that the cell is at least that wide, even if the content is smaller. On the other hand, width is flexible and might be overridden if the overall table needs to adjust its layout.

Solutions

- Use min-width: If you need to guarantee a minimum width for columns, min-width is the best choice.
- Set table-layout: fixed: To ensure the table respects the width setting, you can apply table-layout: fixed. This may cause content to be truncated or wrapped to fit the width.
- Adjust Content: Ensure the content fits within the width setting or allow it to wrap to match the width constraints.

```css
table {
  table-layout: fixed;
  width: 100%;
}

th, td {
  min-width: 100px;
}
```

This configuration ensures that columns are at least 100px wide and won’t shrink smaller than that even if the content allows it.
