### ISSUE TITLE
I would like to be able to search where any words in search exists anywhere in row not just exact match (i.e. split(' ') to array)

### ISSUE THREAD

**Issue by JayAtCornwallCollege** [wenzhixin/bootstrap-table#900]

**Comment by djhvscf** [comment]
This feature is not supported but any pull request is welcome

**Comment by wenzhixin** [comment]
For example?

**Comment by jtrumbull** [comment]
@JayAtCornwallCollege: Do you mean like keyword searching for multiple results -for example you want to search `Item 0, Item 188` and get two results from the [this example](http://issues.wenzhixin.net.cn/bootstrap-table/)? Or do you mean you want to search `188 Item` and get one result?

**Comment by JayAtCornwallCollege** [comment]
A combination of both.  In the example entering 'Item 0 188' would initially return all rows because they all include 'item'.  The user would logically realize that eliminating 'item' leaving '0 188' the search would not find traditionally a row containing '0 188' but the new way would return rows containing 0 and 188.  They would get more rows than they want.  Then the user may enter 'item 0 item 188' and the search algorithm should be able to return rows containing 'item 0' and 'item 188' Not sure how to do this though.  maybe a too complex request, best to keep it simple.  perhaps the use of commas may help

**Comment by wenzhixin** [comment]
It seems very complex, I think it is hard to implement this feature.

**Comment by jtrumbull** [comment]
@JayAtCornwallCollege: As you both have mentioned, this would be a very complex system. But a good explanation never hurt! ..well, it might not be good, but it'll be an explanation.

In your example of `Item 0 188`, you are using __space__ as a delimiter, to find `"item" || "0" || "188"` in _any_ row. The inherent problem is:

- __User 1__ wants to search for any rows containing `"item" || "0" || "188"`.
- __User 2__ wants to search for `"Item 0 188"` literal.

In the above example, __User 2__ will not be satisfied. Even if you used a tiered system, where the keyword approach is only attempted if the standard search returns "No matching records", __User 1__ will not be satisfied if `"Item 0 188"` exists in a row. __Space__ is probably not the best delimiter. You, the end developer, would know what the best delimiter would be, based on context of the data. Using `, ` (coma space) as the delimiter for further explanation, the next layer of complexity would be:

- __User 2__ now wants to search for `"Item, 0, 188"` literal.

You would need to devise a system for __User 2__ to escape the (coma space), as your system cannot know __User 2__'s intention -short of adding a checkbox to turn keyword searching on/off. This can be very tricky depending on how intelligence / computer savvy your target market is. Using a tooltip to explain the `Item\, 0\, 188` concept may cause an overwhelming amount of questions -this would be a risk vs reward analysis on your side. Which  leads to the next layer of complexity where:

- __User 2__ wants to search for the `"Item\, 0\, 188"` literal.

You can start to see how complicated this gets from the end developer's perceptive, who has an understanding of their data-set. Now imagine trying to abstract that system to fit a great number of scenarios from bootstrap-tables's perspective. Not to say that I don't like a good challenge, but to say that this task is probably better suited for one who understands the context of the data.

If the [filer-control](https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/filter-control) extension does not suit your needs and you wish to embark on this system, you can use this as a starting point:

```javascript
var $table = $('#table').bootstrapTable();
    
$table.on('search.bs.table', function(evnt, text){ // Fires after the standard search
	
	var table = $(this).data('bootstrap.table'), // The table instance
		delimiter = ", "
        keywords = text.split(delimiter),
		_filtered = table.data, // The results of the standard search
		data = table.options.data, // Your full data list
		filtered = [];
	
	// Your logic here -pushing records to `filtered`
	
	table.load(filtered);
	
});
```
\* _If you get a working prototype and wish to share the code, please post back here. I would love to see what you come up with._

In closing: I don't want to be biased by my experience, if you have ideas on how to implement this on an abstract level, please share. I'm a sucker for a clean interface, and agree this would be a great feature to simplify some projects that I've worked on. Otherwise, as stated above, I believe this better left to the end developer.

\- Cheers

**Comment by dabros** [comment]
@jtrumbull - titles a bit of a mouthfull, how about a better title, say "Partial Filter Matches"?

See #678

**Comment by wenzhixin** [comment]
OK, wonfix this issue, close it.
