### ISSUE TITLE
I find a bug when I use export func on the IE11

### ISSUE THREAD

**Issue by kyo313** [wenzhixin/bootstrap-table#956]
I find a bug when I use export func on the IE11 with follow page
http://issues.wenzhixin.net.cn/bootstrap-table/

**Comment by wenzhixin** [comment]
What is the bug? I am not using windows system, so I cannot test it now.
I will appreciate if some one can help to find out or fix the bug.

**Comment by djhvscf** [comment]
See this: http://stackoverflow.com/questions/2483771/how-can-i-convince-ie-to-simply-display-application-json-rather-than-offer-to-dow

**Comment by zardaloop** [comment]
Hi Dennis @djhvscf   How is that solve the issue for the people who do not change the registry on their computer and visit your website? I am not really convinced .

**Comment by wenzhixin** [comment]
It seems this bug is caused by the export dependent plugin.

**Comment by zardaloop** [comment]
@wenzhixin  yes you are right. The solution that @djhvscf  Dennis gave might work for an intranet where you have full control over all the computers within the network and you can apply a new policy rule from the server to all the clients. However that is not a solution for other people who visit your website from all over the world.
So I guess this issue should be reopen, since there is no solution to it yet.

Cheers.

**Comment by zardaloop** [comment]
Cool , thanks for reopening the issue. 
I though you might find this relevant. https://github.com/hhurz/tableExport.jquery.plugin/issues/15#issuecomment-110448473

**Comment by wenzhixin** [comment]
Please discuss this bug in hhurz/tableExport.jquery.plugin#15
